In [1]:
import json
data=[ {"video_id": "video_user7212", "user_id": "user7212", "date_created": "2024-05-17T11:59:52.812713", "video_key": "generated_videos/video_user7212/final_video.mp4", "video_type": "image", "video_parts": [{"key": 1, "duration": 2.53, "media_key": "datalake_media/image-still-life-562357_150.jpg-d915458b-a331-46e2-8da4-90c5cb8843c4", "audio_key": "generated_videos/video_user7212/audio1", "text": "Nutrition is the foundation of a healthy life.", "subtitles": "Nutrition is the foundation of a healthy life.", "video_part_key": "generated_videos/video_user7212/video_user7212part1.mp4"}, {"key": 2, "duration": 3.37, "media_key": "datalake_media/image-salad-2756467_150.jpg-3f1fc718-cfb2-46b6-b7e2-71d99da78ba1", "audio_key": "generated_videos/video_user7212/audio2", "text": "Balanced diets fuel our bodies, providing essential energy.", "subtitles": "Balanced diets fuel our bodies, providing essential energy.", "video_part_key": "generated_videos/video_user7212/video_user7212part2.mp4"}, {"key": 3, "duration": 1.93, "media_key": "datalake_media/image-joy-2483926_150.jpg-098c254a-cfff-41c4-986b-66c63f751c20", "audio_key": "generated_videos/video_user7212/audio3", "text": "Healthy fats support our brains.", "subtitles": "Healthy fats support our brains.", "video_part_key": "generated_videos/video_user7212/video_user7212part3.mp4"}]}, {"video_id": "video_user40911", "user_id": "user40911", "date_created": "2024-05-17T13:29:49.694623", "video_key": "generated_videos/video_user40911/final_video.mp4", "video_type": "image", "video_parts": [{"key": 1, "duration": 2.87, "media_key": "datalake_media/image-dna-4068826_150.jpg-e4b38802-e684-4814-8ffe-a2d61460dfb7", "audio_key": "generated_videos/video_user40911/audio1", "text": "Nutrition is the foundation of a healthy life.", "subtitles": "Nutrition is the foundation of a healthy life.", "video_part_key": "generated_videos/video_user40911/video_user40911part1.mp4"}]}, {"video_id": "video_user409111", "user_id": "user409111", "date_created": "2024-05-17T13:49:05.988910", "video_key": "generated_videos/video_user409111/final_video.mp4", "video_type": "image", "video_parts": [{"key": 1, "duration": 2.53, "media_key": "datalake_media/image-dna-4068826_150.jpg-e4b38802-e684-4814-8ffe-a2d61460dfb7", "audio_key": "generated_videos/video_user409111/audio1", "text": "Nutrition is the foundation of a healthy life.", "subtitles": "Nutrition is the foundation of a healthy life.", "video_part_key": "generated_videos/video_user409111/video_user409111part1.mp4"}, {"key": 2, "duration": 3.42, "media_key": "datalake_media/image-fruit-8750860_150.jpg-29b9c90c-d544-4da5-b871-fc0696a730c7", "audio_key": "generated_videos/video_user409111/audio2", "text": "Balanced diets fuel our bodies, providing essential energy.", "subtitles": "Balanced diets fuel our bodies, providing essential energy.", "video_part_key": "generated_videos/video_user409111/video_user409111part2.mp4"}, {"key": 3, "duration": 1.91, "media_key": "datalake_media/image-red-8268266_150.jpg-09243c46-e0d0-400f-8f92-95eb6f4593f0", "audio_key": "generated_videos/video_user409111/audio3", "text": "Healthy fats support our brains.", "subtitles": "Healthy fats support our brains.", "video_part_key": "generated_videos/video_user409111/video_user409111part3.mp4"}]}]


# Find the entry with "video_id": "video_user409111"
for entry in data:
    if entry.get("video_id") == "video_user409111":
        # Find the video_parts array
        video_parts = entry.get("video_parts")
        
        # Find the video_part with key 1
        for i, part in enumerate(video_parts):
            if part.get("key") == 1:
                # Create a new video_part object
                new_part = {
                    "key": part.get("key") + 1,
                    "duration": part.get("duration"),
                    "media_key": part.get("media_key"),
                    "audio_key": part.get("audio_key") + "new",
                    "text": part.get("text"),
                    "subtitles": part.get("subtitles"),
                    "video_part_key": part.get("video_part_key") + "new"
                }
                
                # Insert the new video_part after the existing video_part with key 1
                video_parts.insert(i + 1, new_part)
                
                break

data

[{'video_id': 'video_user7212',
  'user_id': 'user7212',
  'date_created': '2024-05-17T11:59:52.812713',
  'video_key': 'generated_videos/video_user7212/final_video.mp4',
  'video_type': 'image',
  'video_parts': [{'key': 1,
    'duration': 2.53,
    'media_key': 'datalake_media/image-still-life-562357_150.jpg-d915458b-a331-46e2-8da4-90c5cb8843c4',
    'audio_key': 'generated_videos/video_user7212/audio1',
    'text': 'Nutrition is the foundation of a healthy life.',
    'subtitles': 'Nutrition is the foundation of a healthy life.',
    'video_part_key': 'generated_videos/video_user7212/video_user7212part1.mp4'},
   {'key': 2,
    'duration': 3.37,
    'media_key': 'datalake_media/image-salad-2756467_150.jpg-3f1fc718-cfb2-46b6-b7e2-71d99da78ba1',
    'audio_key': 'generated_videos/video_user7212/audio2',
    'text': 'Balanced diets fuel our bodies, providing essential energy.',
    'subtitles': 'Balanced diets fuel our bodies, providing essential energy.',
    'video_part_key': 'generated_videos/video_user7212/video_user7212part2.mp4'},
   {'key': 3,
    'duration': 1.93,
    'media_key': 'datalake_media/image-joy-2483926_150.jpg-098c254a-cfff-41c4-986b-66c63f751c20',
    'audio_key': 'generated_videos/video_user7212/audio3',
    'text': 'Healthy fats support our brains.',
    'subtitles': 'Healthy fats support our brains.',
    'video_part_key': 'generated_videos/video_user7212/video_user7212part3.mp4'}]},
 {'video_id': 'video_user40911',
  'user_id': 'user40911',
  'date_created': '2024-05-17T13:29:49.694623',
  'video_key': 'generated_videos/video_user40911/final_video.mp4',
  'video_type': 'image',
  'video_parts': [{'key': 1,
    'duration': 2.87,
    'media_key': 'datalake_media/image-dna-4068826_150.jpg-e4b38802-e684-4814-8ffe-a2d61460dfb7',
    'audio_key': 'generated_videos/video_user40911/audio1',
    'text': 'Nutrition is the foundation of a healthy life.',
    'subtitles': 'Nutrition is the foundation of a healthy life.',
    'video_part_key': 'generated_videos/video_user40911/video_user40911part1.mp4'}]},
 {'video_id': 'video_user409111',
  'user_id': 'user409111',
  'date_created': '2024-05-17T13:49:05.988910',
  'video_key': 'generated_videos/video_user409111/final_video.mp4',
  'video_type': 'image',
  'video_parts': [{'key': 1,
    'duration': 2.53,
    'media_key': 'datalake_media/image-dna-4068826_150.jpg-e4b38802-e684-4814-8ffe-a2d61460dfb7',
    'audio_key': 'generated_videos/video_user409111/audio1',
    'text': 'Nutrition is the foundation of a healthy life.',
    'subtitles': 'Nutrition is the foundation of a healthy life.',
    'video_part_key': 'generated_videos/video_user409111/video_user409111part1.mp4'},
   {'key': 2,
    'duration': 2.53,
    'media_key': 'datalake_media/image-dna-4068826_150.jpg-e4b38802-e684-4814-8ffe-a2d61460dfb7',
    'audio_key': 'generated_videos/video_user409111/audio1new',
    'text': 'Nutrition is the foundation of a healthy life.',
    'subtitles': 'Nutrition is the foundation of a healthy life.',
    'video_part_key': 'generated_videos/video_user409111/video_user409111part1.mp4new'},
   {'key': 2,
    'duration': 3.42,
    'media_key': 'datalake_media/image-fruit-8750860_150.jpg-29b9c90c-d544-4da5-b871-fc0696a730c7',
    'audio_key': 'generated_videos/video_user409111/audio2',
    'text': 'Balanced diets fuel our bodies, providing essential energy.',
    'subtitles': 'Balanced diets fuel our bodies, providing essential energy.',
    'video_part_key': 'generated_videos/video_user409111/video_user409111part2.mp4'},
   {'key': 3,
    'duration': 1.91,
    'media_key': 'datalake_media/image-red-8268266_150.jpg-09243c46-e0d0-400f-8f92-95eb6f4593f0',
    'audio_key': 'generated_videos/video_user409111/audio3',
    'text': 'Healthy fats support our brains.',
    'subtitles': 'Healthy fats support our brains.',
    'video_part_key': 'generated_videos/video_user409111/video_user409111part3.mp4'}]}]

In [6]:
with open('data.json', 'w') as file:
    json.dump(data, file, indent=4)

In [20]:
import copy

original_metadata = [ {"video_id": "video_user7212", "user_id": "user7212", "date_created": "2024-05-17T11:59:52.812713", "video_key": "generated_videos/video_user7212/final_video.mp4", "video_type": "image", "video_parts": [{"key": 1, "duration": 2.53, "media_key": "datalake_media/image-still-life-562357_150.jpg-d915458b-a331-46e2-8da4-90c5cb8843c4", "audio_key": "generated_videos/video_user7212/audio1", "text": "Nutrition is the foundation of a healthy life.", "subtitles": "Nutrition is the foundation of a healthy life.", "video_part_key": "generated_videos/video_user7212/video_user7212part1.mp4"}, {"key": 2, "duration": 3.37, "media_key": "datalake_media/image-salad-2756467_150.jpg-3f1fc718-cfb2-46b6-b7e2-71d99da78ba1", "audio_key": "generated_videos/video_user7212/audio2", "text": "Balanced diets fuel our bodies, providing essential energy.", "subtitles": "Balanced diets fuel our bodies, providing essential energy.", "video_part_key": "generated_videos/video_user7212/video_user7212part2.mp4"}, {"key": 3, "duration": 1.93, "media_key": "datalake_media/image-joy-2483926_150.jpg-098c254a-cfff-41c4-986b-66c63f751c20", "audio_key": "generated_videos/video_user7212/audio3", "text": "Healthy fats support our brains.", "subtitles": "Healthy fats support our brains.", "video_part_key": "generated_videos/video_user7212/video_user7212part3.mp4"}]}, {"video_id": "video_user40911", "user_id": "user40911", "date_created": "2024-05-17T13:29:49.694623", "video_key": "generated_videos/video_user40911/final_video.mp4", "video_type": "image", "video_parts": [{"key": 1, "duration": 2.87, "media_key": "datalake_media/image-dna-4068826_150.jpg-e4b38802-e684-4814-8ffe-a2d61460dfb7", "audio_key": "generated_videos/video_user40911/audio1", "text": "Nutrition is the foundation of a healthy life.", "subtitles": "Nutrition is the foundation of a healthy life.", "video_part_key": "generated_videos/video_user40911/video_user40911part1.mp4"}]}, {"video_id": "video_user409111", "user_id": "user409111", "date_created": "2024-05-17T13:49:05.988910", "video_key": "generated_videos/video_user409111/final_video.mp4", "video_type": "image", "video_parts": [{"key": 1, "duration": 2.53, "media_key": "datalake_media/image-dna-4068826_150.jpg-e4b38802-e684-4814-8ffe-a2d61460dfb7", "audio_key": "generated_videos/video_user409111/audio1", "text": "Nutrition is the foundation of a healthy life.", "subtitles": "Nutrition is the foundation of a healthy life.", "video_part_key": "generated_videos/video_user409111/video_user409111part1.mp4"}, {"key": 2, "duration": 3.42, "media_key": "datalake_media/image-fruit-8750860_150.jpg-29b9c90c-d544-4da5-b871-fc0696a730c7", "audio_key": "generated_videos/video_user409111/audio2", "text": "Balanced diets fuel our bodies, providing essential energy.", "subtitles": "Balanced diets fuel our bodies, providing essential energy.", "video_part_key": "generated_videos/video_user409111/video_user409111part2.mp4"}, {"key": 3, "duration": 1.91, "media_key": "datalake_media/image-red-8268266_150.jpg-09243c46-e0d0-400f-8f92-95eb6f4593f0", "audio_key": "generated_videos/video_user409111/audio3", "text": "Healthy fats support our brains.", "subtitles": "Healthy fats support our brains.", "video_part_key": "generated_videos/video_user409111/video_user409111part3.mp4"}]}]


def add_video_part_and_update_keys(metadata, video_id, new_part,previous_key):
    for video in metadata:
        if video["video_id"] == video_id:
            for part in video["video_parts"]:
                if part["key"] > previous_key:
                    part["key"] += 1
            new_part_data = copy.deepcopy(new_part)
            new_part_data["key"] = previous_key+1
            video["video_parts"].insert(previous_key, new_part_data)
    return metadata

new_part_data = {
    "duration": 2.53,
    "media_key": "datalake_media/image-dna-4068826_150.jpg-e4b38802-e684-4814-8ffe-a2d61460dfb7",
    "audio_key": "generated_videos/video_user409111/audio1new",
    "text": "Nutrition is the foundation of a healthy life.",
    "subtitles": "Nutrition is the foundation of a healthy life.",
    "video_part_key": "generated_videos/video_user409111/video_user409111part1new.mp4"
}

updated_metadata = add_video_part_and_update_keys(original_metadata, "video_user409111", new_part_data,2)


with open('data.json', 'w') as file:
    json.dump(updated_metadata, file, indent=4)

In [22]:
import json
from botocore.exceptions import ClientError
from moviepy.editor import VideoFileClip, ImageClip, AudioFileClip, CompositeVideoClip
import tempfile
from io import BytesIO
from PIL import Image
import numpy as np
import requests
import uuid
import os
from datalake import put_image_in_s3
from text import create_text_updated_clip,def_translation

def update_text_in_json(s3,video_id, text_keys, new_texts):
    try:
        response = s3.get_object(Bucket='soulchain-dev1-output-video', Key='video_info.json')
        data = json.loads(response['Body'].read())
    except ClientError as e:
        if e.response['Error']['Code'] == 'NoSuchKey':
            data = []
        else:
            raise  

    video = next((v for v in data if v["video_id"] == video_id), None)

    if video:
        for text_key, new_text in zip(text_keys, new_texts):
            part = next((p for p in video["video_parts"] if p["key"] == text_key), None)
            if part:
                part["subtitles"] = new_text
    try:
        data = json.dumps(data)
        
        s3.put_object(Bucket='soulchain-dev1-output-video', Key=f"video_info.json", Body=data)
        print("JSON file successfully updated.")
    except Exception as e:
        print(f"Error while saving the JSON file: {e}")

    return data

In [1]:
import boto3
session = boto3.Session(region_name='eu-west-1')
s3 = session.client('s3',aws_access_key_id="AKIAUJXLE2HEOGWEMCEX",aws_secret_access_key="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")

# data=update_text_in_json(s3,"video_userimane",[1,2], ["Hello","Hi"])

/Users/fatimaezzahrasounnyslitine/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(

In [24]:
data

'[{"video_id": "video7000", "user_id": "user700", "date_created": "2024-05-15T11:30:49.930907", "video_key": "generated_videos/video7000/final_video.mp4", "video_type": "image", "video_parts": [{"key": 1, "duration": 2.77, "media_key": "datalake_media/image-digital-marketing-1725340_150.jpg-785e05fd-a610-4695-bc63-a660b1899a81", "audio_key": "generated_videos/video7000/audio1", "text": "Wondering how protein impacts blood sugar levels?", "subtitles": "Wondering how protein impacts blood sugar levels?", "video_part_key": "generated_videos/video7000/video7000_part_1.mp4"}]}, {"video_id": "video7000", "user_id": "user700", "date_created": "2024-05-15T11:56:49.517180", "video_key": "generated_videos/video7000/final_video.mp4", "video_type": "image", "video_parts": [{"key": 1, "duration": 2.82, "media_key": "datalake_media/image-bread-2796393_150.jpg-1b0ffe96-fbec-4bc3-9c6d-0e43965b52a7", "audio_key": "generated_videos/video7000/audio1", "text": "Wondering how protein impacts blood sugar levels?", "subtitles": "Wondering how protein impacts blood sugar levels?", "video_part_key": "generated_videos/video7000/video7000_part_1.mp4"}]}, {"video_id": "video_user4099", "user_id": "user4099", "date_created": "2024-05-16T16:29:43.877157", "video_key": "generated_videos/video_user4099/final_video.mp4", "video_type": "image", "video_parts": [{"key": 1, "duration": 2.59, "media_key": "datalake_media/image-dna-4068826_150.jpg-e4b38802-e684-4814-8ffe-a2d61460dfb7", "audio_key": "generated_videos/video_user4099/audio1", "text": "Nutrition is the foundation of a healthy\\u00a0life.", "subtitles": "Nutrition is the foundation of a healthy\\u00a0life.", "video_part_key": "generated_videos/video_user4099/video_user4099part1.mp4"}]}, {"video_id": "video_user40", "user_id": "user40", "date_created": "2024-05-16T16:35:00.524526", "video_key": "generated_videos/video_user40/final_video.mp4", "video_type": "image", "video_parts": [{"key": 1, "duration": 2.64, "media_key": "datalake_media/image-dna-4068826_150.jpg-e4b38802-e684-4814-8ffe-a2d61460dfb7", "audio_key": "generated_videos/video_user40/audio1", "text": "Nutrition is the foundation of a healthy\\u00a0life.", "subtitles": "Nutrition is the foundation of a healthy\\u00a0life.", "video_part_key": "generated_videos/video_user40/video_user40part1.mp4"}]}, {"video_id": "video_user40", "user_id": "user40", "date_created": "2024-05-16T16:41:20.582767", "video_key": "generated_videos/video_user40/final_video.mp4", "video_type": "image", "video_parts": [{"key": 1, "duration": 2.64, "media_key": "datalake_media/image-still-life-2366084_150.jpg-f769f30e-8922-4810-8aa9-853e58c03bbc", "audio_key": "generated_videos/video_user40/audio1", "text": "Nutrition is the foundation of a healthy\\u00a0life.", "subtitles": "Nutrition is the foundation of a healthy\\u00a0life.", "video_part_key": "generated_videos/video_user40/video_user40part1.mp4"}]}, {"video_id": "video_user40", "user_id": "user40", "date_created": "2024-05-16T16:42:23.136732", "video_key": "generated_videos/video_user40/final_video.mp4", "video_type": "image", "video_parts": [{"key": 1, "duration": 2.74, "media_key": "datalake_media/image-still-life-562357_150.jpg-d915458b-a331-46e2-8da4-90c5cb8843c4", "audio_key": "generated_videos/video_user40/audio1", "text": "Nutrition is the foundation of a healthy\\u00a0life.", "subtitles": "Nutrition is the foundation of a healthy\\u00a0life.", "video_part_key": "generated_videos/video_user40/video_user40part1.mp4"}]}, {"video_id": "video_user4099", "user_id": "user4099", "date_created": "2024-05-16T16:50:47.574779", "video_key": "generated_videos/video_user4099/final_video.mp4", "video_type": "image", "video_parts": [{"key": 1, "duration": 2.64, "media_key": "datalake_media/image-still-life-2366084_150.jpg-f769f30e-8922-4810-8aa9-853e58c03bbc", "audio_key": "generated_videos/video_user4099/audio1", "text": "Nutrition is the foundation of a healthy\\u00a0life.", "subtitles": "Nutrition is the foundation of a healthy\\u00a0life.", "video_part_key": "generated_videos/video_user4099/video_user4099part1.mp4"}]}, {"video_id": "video_user40", "user_id": "user40", "date_created": "2024-05-16T19:30:41.389043", "video_key": "generated_videos/video_user40/final_video.mp4", "video_type": "image", "video_parts": [{"key": 1, "duration": 2.64, "media_key": "datalake_media/image-banana-8719086_150.jpg-e83f2f66-99ca-4ac2-a2b4-6b145a6e717e", "audio_key": "generated_videos/video_user40/audio1", "text": "Nutrition is the foundation of a healthy\\u00a0life.", "subtitles": "Nutrition is the foundation of a healthy\\u00a0life.", "video_part_key": "generated_videos/video_user40/video_user40part1.mp4"}]}, {"video_id": "video_user40", "user_id": "user40", "date_created": "2024-05-16T19:36:34.215440", "video_key": "generated_videos/video_user40/final_video.mp4", "video_type": "image", "video_parts": [{"key": 1, "duration": 2.69, "media_key": "datalake_media/image-ai-generated-8637800_150.jpg-a24ec5c0-52e0-4e69-85ad-9fa77894a5ff", "audio_key": "generated_videos/video_user40/audio1", "text": "Nutrition is the foundation of a healthy\\u00a0life.", "subtitles": "Nutrition is the foundation of a healthy\\u00a0life.", "video_part_key": "generated_videos/video_user40/video_user40part1.mp4"}]}, {"video_id": "video_user4099", "user_id": "user4099", "date_created": "2024-05-16T20:03:18.384280", "video_key": "generated_videos/video_user4099/final_video.mp4", "video_type": "image", "video_parts": [{"key": 1, "duration": 2.64, "media_key": "datalake_media/image-still-life-562357_150.jpg-d915458b-a331-46e2-8da4-90c5cb8843c4", "audio_key": "generated_videos/video_user4099/audio1", "text": "Nutrition is the foundation of a healthy\\u00a0life.", "subtitles": "Nutrition is the foundation of a healthy\\u00a0life.", "video_part_key": "generated_videos/video_user4099/video_user4099part1.mp4"}]}, {"video_id": "video_user4091", "user_id": "user4091", "date_created": "2024-05-16T20:28:09.692443", "video_key": "generated_videos/video_user4091/final_video.mp4", "video_type": "image", "video_parts": [{"key": 1, "duration": 2.59, "media_key": "datalake_media/image-dna-4068826_150.jpg-e4b38802-e684-4814-8ffe-a2d61460dfb7", "audio_key": "generated_videos/video_user4091/audio1", "text": "Nutrition is the foundation of a healthy\\u00a0life.", "subtitles": "Nutrition is the foundation of a healthy\\u00a0life.", "video_part_key": "generated_videos/video_user4091/video_user4091part1.mp4"}]}, {"video_id": "video_user7000", "user_id": "user7000", "date_created": "2024-05-16T20:30:27.635979", "video_key": "generated_videos/video_user7000/final_video.mp4", "video_type": "image", "video_parts": [{"key": 1, "duration": 2.69, "media_key": "datalake_media/image-dna-4068826_150.jpg-e4b38802-e684-4814-8ffe-a2d61460dfb7", "audio_key": "generated_videos/video_user7000/audio1", "text": "Nutrition is the foundation of a healthy\\u00a0life.", "subtitles": "Nutrition is the foundation of a healthy\\u00a0life.", "video_part_key": "generated_videos/video_user7000/video_user7000part1.mp4"}]}, {"video_id": "video_user7000", "user_id": "user7000", "date_created": "2024-05-16T20:35:12.186730", "video_key": "generated_videos/video_user7000/final_video.mp4", "video_type": "image", "video_parts": [{"key": 1, "duration": 2.64, "media_key": "datalake_media/image-still-life-2366084_150.jpg-f769f30e-8922-4810-8aa9-853e58c03bbc", "audio_key": "generated_videos/video_user7000/audio1", "text": "Nutrition is the foundation of a healthy\\u00a0life.", "subtitles": "Nutrition is the foundation of a healthy\\u00a0life.", "video_part_key": "generated_videos/video_user7000/video_user7000part1.mp4"}]}, {"video_id": "video_user7000", "user_id": "user7000", "date_created": "2024-05-16T20:54:23.992244", "video_key": "generated_videos/video_user7000/final_video.mp4", "video_type": "image", "video_parts": [{"key": 1, "duration": 2.53, "media_key": "datalake_media/image-still-life-562357_150.jpg-d915458b-a331-46e2-8da4-90c5cb8843c4", "audio_key": "generated_videos/video_user7000/audio1", "text": "Nutrition is the foundation of a healthy\\u00a0life.", "subtitles": "Nutrition is the foundation of a healthy\\u00a0life.", "video_part_key": "generated_videos/video_user7000/video_user7000part1.mp4"}]}, {"video_id": "video_user7000", "user_id": "user7000", "date_created": "2024-05-16T21:01:11.981904", "video_key": "generated_videos/video_user7000/final_video.mp4", "video_type": "image", "video_parts": [{"key": 1, "duration": 2.64, "media_key": "datalake_media/image-banana-8719086_150.jpg-1eaedd69-f52b-4df5-90e6-8bc10481846f", "audio_key": "generated_videos/video_user7000/audio1", "text": "Nutrition is the foundation of a healthy\\u00a0life.", "subtitles": "Nutrition is the foundation of a healthy\\u00a0life.", "video_part_key": "generated_videos/video_user7000/video_user7000part1.mp4"}]}, {"video_id": "video_user7000", "user_id": "user7000", "date_created": "2024-05-16T21:27:10.468581", "video_key": "generated_videos/video_user7000/final_video.mp4", "video_type": "image", "video_parts": [{"key": 1, "duration": 2.51, "media_key": "datalake_media/image-ai-generated-8637800_150.jpg-de81e398-9ff3-4b5b-b9d9-8a22f0fc181a", "audio_key": "generated_videos/video_user7000/audio1", "text": "Nutrition is the foundation of a healthy\\u00a0life.", "subtitles": "Nutrition is the foundation of a healthy\\u00a0life.", "video_part_key": "generated_videos/video_user7000/video_user7000part1.mp4"}]}, {"video_id": "video_user70001", "user_id": "user70001", "date_created": "2024-05-16T21:33:20.612162", "video_key": "generated_videos/video_user70001/final_video.mp4", "video_type": "image", "video_parts": [{"key": 1, "duration": 2.69, "media_key": "datalake_media/image-dna-4068826_150.jpg-e4b38802-e684-4814-8ffe-a2d61460dfb7", "audio_key": "generated_videos/video_user70001/audio1", "text": "Nutrition is the foundation of a healthy\\u00a0life.", "subtitles": "Nutrition is the foundation of a healthy\\u00a0life.", "video_part_key": "generated_videos/video_user70001/video_user70001part1.mp4"}]}, {"video_id": "video_user70001", "user_id": "user70001", "date_created": "2024-05-16T22:23:37.771182", "video_key": "generated_videos/video_user70001/final_video.mp4", "video_type": "image", "video_parts": [{"key": 1, "duration": 2.74, "media_key": "datalake_media/image-still-life-2366084_150.jpg-f769f30e-8922-4810-8aa9-853e58c03bbc", "audio_key": "generated_videos/video_user70001/audio1", "text": "Nutrition is the foundation of a healthy\\u00a0life.", "subtitles": "Nutrition is the foundation of a healthy\\u00a0life.", "video_part_key": "generated_videos/video_user70001/video_user70001part1.mp4"}]}, {"video_id": "video_user70001", "user_id": "user70001", "date_created": "2024-05-16T22:27:28.285070", "video_key": "generated_videos/video_user70001/final_video.mp4", "video_type": "image", "video_parts": [{"key": 1, "duration": 2.51, "media_key": "datalake_media/image-still-life-562357_150.jpg-d915458b-a331-46e2-8da4-90c5cb8843c4", "audio_key": "generated_videos/video_user70001/audio1", "text": "Nutrition is the foundation of a healthy\\u00a0life.", "subtitles": "Nutrition is the foundation of a healthy\\u00a0life.", "video_part_key": "generated_videos/video_user70001/video_user70001part1.mp4"}]}, {"video_id": "video_user72", "user_id": "user72", "date_created": "2024-05-16T22:35:34.823055", "video_key": "generated_videos/video_user72/final_video.mp4", "video_type": "image", "video_parts": [{"key": 1, "duration": 2.59, "media_key": "datalake_media/image-dna-4068826_150.jpg-e4b38802-e684-4814-8ffe-a2d61460dfb7", "audio_key": "generated_videos/video_user72/audio1", "text": "Nutrition is the foundation of a healthy\\u00a0life.", "subtitles": "Nutrition is the foundation of a healthy\\u00a0life.", "video_part_key": "generated_videos/video_user72/video_user72part1.mp4"}]}, {"video_id": "video_user72", "user_id": "user72", "date_created": "2024-05-16T22:50:41.854295", "video_key": "generated_videos/video_user72/final_video.mp4", "video_type": "image", "video_parts": [{"key": 1, "duration": 2.53, "media_key": "datalake_media/image-still-life-2366084_150.jpg-f769f30e-8922-4810-8aa9-853e58c03bbc", "audio_key": "generated_videos/video_user72/audio1", "text": "Nutrition is the foundation of a healthy\\u00a0life.", "subtitles": "Nutrition is the foundation of a healthy\\u00a0life.", "video_part_key": "generated_videos/video_user72/video_user72part1.mp4"}]}, {"video_id": "video_user72", "user_id": "user72", "date_created": "2024-05-16T23:07:21.941597", "video_key": "generated_videos/video_user72/final_video.mp4", "video_type": "image", "video_parts": [{"key": 1, "duration": 2.53, "media_key": "datalake_media/image-still-life-562357_150.jpg-d915458b-a331-46e2-8da4-90c5cb8843c4", "audio_key": "generated_videos/video_user72/audio1", "text": "Nutrition is the foundation of a healthy\\u00a0life.", "subtitles": "Nutrition is the foundation of a healthy\\u00a0life.", "video_part_key": "generated_videos/video_user72/video_user72part1.mp4"}]}, {"video_id": "video_user721", "user_id": "user721", "date_created": "2024-05-16T23:21:54.414499", "video_key": "generated_videos/video_user721/final_video.mp4", "video_type": "image", "video_parts": [{"key": 1, "duration": 2.51, "media_key": "datalake_media/image-dna-4068826_150.jpg-e4b38802-e684-4814-8ffe-a2d61460dfb7", "audio_key": "generated_videos/video_user721/audio1", "text": "Nutrition is the foundation of a healthy\\u00a0life.", "subtitles": "Nutrition is the foundation of a healthy\\u00a0life.", "video_part_key": "generated_videos/video_user721/video_user721part1.mp4"}]}, {"video_id": "video_user721", "user_id": "user721", "date_created": "2024-05-16T23:29:47.004827", "video_key": "generated_videos/video_user721/final_video.mp4", "video_type": "image", "video_parts": [{"key": 1, "duration": 2.53, "media_key": "datalake_media/image-still-life-2366084_150.jpg-f769f30e-8922-4810-8aa9-853e58c03bbc", "audio_key": "generated_videos/video_user721/audio1", "text": "Nutrition is the foundation of a healthy\\u00a0life.", "subtitles": "Nutrition is the foundation of a healthy\\u00a0life.", "video_part_key": "generated_videos/video_user721/video_user721part1.mp4"}]}, {"video_id": "video_user721", "user_id": "user721", "date_created": "2024-05-16T23:38:58.363413", "video_key": "generated_videos/video_user721/final_video.mp4", "video_type": "image", "video_parts": [{"key": 1, "duration": 2.64, "media_key": "datalake_media/image-still-life-562357_150.jpg-d915458b-a331-46e2-8da4-90c5cb8843c4", "audio_key": "generated_videos/video_user721/audio1", "text": "Nutrition is the foundation of a healthy\\u00a0life.", "subtitles": "Nutrition is the foundation of a healthy\\u00a0life.", "video_part_key": "generated_videos/video_user721/video_user721part1.mp4"}]}, {"video_id": "video_user721", "user_id": "user721", "date_created": "2024-05-17T08:37:14.682547", "video_key": "generated_videos/video_user721/final_video.mp4", "video_type": "image", "video_parts": [{"key": 1, "duration": 2.64, "media_key": "datalake_media/image-banana-8719086_150.jpg-d0521b51-be2e-4bed-a6e6-a82d01810349", "audio_key": "generated_videos/video_user721/audio1", "text": "Nutrition is the foundation of a healthy\\u00a0life.", "subtitles": "Nutrition is the foundation of a healthy\\u00a0life.", "video_part_key": "generated_videos/video_user721/video_user721part1.mp4"}]}, {"video_id": "video_user721", "user_id": "user721", "date_created": "2024-05-17T09:32:39.846896", "video_key": "generated_videos/video_user721/final_video.mp4", "video_type": "image", "video_parts": [{"key": 1, "duration": 2.46, "media_key": "datalake_media/image-berries-3504149_150.jpg-4d467566-7e1e-424f-846a-a82c3971cc37", "audio_key": "generated_videos/video_user721/audio1", "text": "Nutrition is the foundation of a healthy\\u00a0life.", "subtitles": "Nutrition is the foundation of a healthy\\u00a0life.", "video_part_key": "generated_videos/video_user721/video_user721part1.mp4"}]}, {"video_id": "video_user7212", "user_id": "user7212", "date_created": "2024-05-17T09:41:55.732042", "video_key": "generated_videos/video_user7212/final_video.mp4", "video_type": "image", "video_parts": [{"key": 1, "duration": 2.51, "media_key": "datalake_media/image-dna-4068826_150.jpg-e4b38802-e684-4814-8ffe-a2d61460dfb7", "audio_key": "generated_videos/video_user7212/audio1", "text": "Nutrition is the foundation of a healthy\\u00a0life.", "subtitles": "Nutrition is the foundation of a healthy\\u00a0life.", "video_part_key": "generated_videos/video_user7212/video_user7212part1.mp4"}]}, {"video_id": "video_user7212", "user_id": "user7212", "date_created": "2024-05-17T09:49:23.720484", "video_key": "generated_videos/video_user7212/final_video.mp4", "video_type": "image", "video_parts": [{"key": 1, "duration": 2.51, "media_key": "datalake_media/image-still-life-2366084_150.jpg-f769f30e-8922-4810-8aa9-853e58c03bbc", "audio_key": "generated_videos/video_user7212/audio1", "text": "Nutrition is the foundation of a healthy life.", "subtitles": "Nutrition is the foundation of a healthy life.", "video_part_key": "generated_videos/video_user7212/video_user7212part1.mp4"}, {"key": 2, "duration": 3.37, "media_key": "datalake_media/image-fruit-8750860_150.jpg-ede4e307-b2a5-49df-a8ed-558344fa184b", "audio_key": "generated_videos/video_user7212/audio2", "text": "Balanced diets fuel our bodies, providing essential energy.", "subtitles": "Balanced diets fuel our bodies, providing essential energy.", "video_part_key": "generated_videos/video_user7212/video_user7212part2.mp4"}, {"key": 3, "duration": 1.93, "media_key": "datalake_media/image-red-8268266_150.jpg-02a098c9-7ea3-4dce-88a5-5ea9fde08c1e", "audio_key": "generated_videos/video_user7212/audio3", "text": "Healthy fats support\\u00a0our\\u00a0brains.", "subtitles": "Healthy fats support\\u00a0our\\u00a0brains.", "video_part_key": "generated_videos/video_user7212/video_user7212part3.mp4"}]}, {"video_id": "video_user4091", "user_id": "user4091", "date_created": "2024-05-17T09:53:58.976935", "video_key": "generated_videos/video_user4091/final_video.mp4", "video_type": "image", "video_parts": [{"key": 1, "duration": 2.59, "media_key": "datalake_media/image-still-life-2366084_150.jpg-f769f30e-8922-4810-8aa9-853e58c03bbc", "audio_key": "generated_videos/video_user4091/audio1", "text": "Nutrition is the foundation of a healthy life.", "subtitles": "Nutrition is the foundation of a healthy life.", "video_part_key": "generated_videos/video_user4091/video_user4091part1.mp4"}, {"key": 2, "duration": 3.34, "media_key": "datalake_media/image-fruit-8750860_150.jpg-9c597c76-58c5-49f6-93fe-1387170e2b2b", "audio_key": "generated_videos/video_user4091/audio2", "text": "Balanced diets fuel our bodies, providing essential energy.", "subtitles": "Balanced diets fuel our bodies, providing essential energy.", "video_part_key": "generated_videos/video_user4091/video_user4091part2.mp4"}, {"key": 3, "duration": 1.85, "media_key": "datalake_media/image-red-8268266_150.jpg-27bbbe84-e6a3-46b0-9dcd-02356b85d501", "audio_key": "generated_videos/video_user4091/audio3", "text": "Healthy fats support our brains.", "subtitles": "Healthy fats support our brains.", "video_part_key": "generated_videos/video_user4091/video_user4091part3.mp4"}]}, {"video_id": "video_user7212", "user_id": "user7212", "date_created": "2024-05-17T11:59:52.812713", "video_key": "generated_videos/video_user7212/final_video.mp4", "video_type": "image", "video_parts": [{"key": 1, "duration": 2.53, "media_key": "datalake_media/image-still-life-562357_150.jpg-d915458b-a331-46e2-8da4-90c5cb8843c4", "audio_key": "generated_videos/video_user7212/audio1", "text": "Nutrition is the foundation of a healthy life.", "subtitles": "Nutrition is the foundation of a healthy life.", "video_part_key": "generated_videos/video_user7212/video_user7212part1.mp4"}, {"key": 2, "duration": 3.37, "media_key": "datalake_media/image-salad-2756467_150.jpg-3f1fc718-cfb2-46b6-b7e2-71d

In [25]:
from datalake import put_image_in_s3

In [26]:
import json

In [6]:
import json
import boto3

def put_image_in_s3(media, bucket_name, object_key):
    s3 = boto3.client('s3', aws_access_key_id="AKIAUJXLE2HEOGWEMCEX", aws_secret_access_key="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", region_name='eu-west-1')

    try:
        s3.put_object(Bucket=bucket_name, Key=object_key, Body=media)
        print("Media uploaded successfully to S3")
    except Exception as e:
        print(f"An error occurred: {e}")

def read_and_upload_json(file_path, bucket_name, object_key):
    with open(file_path, 'r') as file:
        json_data = json.load(file)
    
    json_str = json.dumps(json_data)

    json_bytes = json_str.encode('utf-8')

    put_image_in_s3(json_bytes, bucket_name, object_key)

file_path = 'video_info.json'
bucket_name = 'soulchain-dev1-output-video'
object_key = 'video_info.json'

read_and_upload_json(file_path, bucket_name, object_key)

Media uploaded successfully to S3

In [27]:
from langdetect import detect
from text import get_argos

def update_text_in_json(s3,video_id, lang):
    all_parts_keys=[]
    try:
        response = s3.get_object(Bucket='soulchain-dev1-output-video', Key='video_info.json')

        data = json.loads(response['Body'].read())
    except ClientError as e:
        if e.response['Error']['Code'] == 'NoSuchKey':
            data = []
        else:
            raise
    
        
    video = next((v for v in data if v["video_id"] == video_id), None)

    all_keys = []
    if video and "video_parts" in video:
        all_keys = [part['key'] for part in video['video_parts']]


    if video:
        for text_key in all_keys:
            part = next((p for p in video["video_parts"] if p["key"] == text_key), None)
            if part:
                original_lang=detect(part["text"])
                original_lang = get_argos(original_lang)
                url_translation = "http://127.0.0.1:5003/translate"
                data_subs = {
                    "text": part["text"],
                    "source": original_lang,
                    "target": lang
                }
                print("data:", data_subs)
                response = requests.post(url_translation, json=data_subs)
                sentence=response.text
                part["subtitles"] = sentence

    try:
        data = json.dumps(data)
        s3.put_object(Bucket='soulchain-dev1-output-video', Key=f"video_info.json", Body=data)
        print("JSON file successfully updated.")
    except Exception as e:
        print(f"Error while saving the JSON file: {e}")

s3 = boto3.client('s3', aws_access_key_id="AKIAUJXLE2HEOGWEMCEX", aws_secret_access_key="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", region_name='eu-west-1')

update_text_in_json(s3, "video_user_test1", "French")

data: {'text': 'A balanced diet is essential for maintaining optimal health and well-being.', 'source': 'English', 'target': 'French'}
data: {'text': 'By including a variety of fruits, vegetables, whole grains, lean proteins, and healthy fats in your meals', 'source': 'English', 'target': 'French'}
data: {'text': ' you can ensure you are getting the necessary nutrients your body needs.', 'source': 'English', 'target': 'French'}
data: {'text': 'This diverse mix of foods provides vitamins, minerals', 'source': 'English', 'target': 'French'}
data: {'text': ' and antioxidants that support various bodily functions and help prevent diseases.', 'source': 'English', 'target': 'French'}
data: {'text': 'A balanced diet can help you manage your weight', 'source': 'English', 'target': 'French'}
data: {'text': ' boost your energy levels, and strengthen your immune system.', 'source': 'English', 'target': 'French'}
data: {'text': 'It also plays a crucial role in promoting healthy bones, teeth, and mental well-being.', 'source': 'English', 'target': 'French'}
data: {'text': 'Embracing a balanced diet is a cornerstone of a healthy lifestyle', 'source': 'English', 'target': 'French'}
data: {'text': ' offering a multitude of benefits for your overall health and vitality.', 'source': 'English', 'target': 'French'}
JSON file successfully updated.

In [32]:
def delete_scene(s3, video_id, scene_index):
    try:
        response = s3.get_object(Bucket='soulchain-dev1-output-video', Key='video_info.json')
        data = json.loads(response['Body'].read())
    except ClientError as e:
        if e.response['Error']['Code'] == 'NoSuchKey':
            print("No video_info.json file found.")
            return
        else:
            raise

    video = next((v for v in data if v["video_id"] == video_id), None)

    if video:
        for item in data:
            item['video_parts'] = [part for part in item['video_parts'] if part['key'] != scene_index]
             

    try:
        updated_data = json.dumps(data)
        s3.put_object(Bucket='soulchain-dev1-output-video', Key='video_info.json', Body=updated_data)
        print("JSON file successfully updated.")
    except Exception as e:
        print(f"Error while saving the JSON file: {e}")
    



delete_scene(s3, "video_user_test1", 2)

JSON file successfully updated.

In [39]:
def delete_scene(s3, video_id, scene_index):
    try:
        response = s3.get_object(Bucket='soulchain-dev1-output-video', Key='video_info.json')
        data = json.loads(response['Body'].read())
    except ClientError as e:
        if e.response['Error']['Code'] == 'NoSuchKey':
            print("No video_info.json file found.")
            return
        else:
            raise

    video = next((v for v in data if v["video_id"] == video_id), None)

    if video:
        for item in data:
            item['video_parts'] = [part for part in item['video_parts'] if part['key'] != scene_index]
             
    # try:
    #     updated_data = json.dumps(data)
    #     s3.put_object(Bucket='soulchain-dev1-output-video', Key='video_info.json', Body=updated_data)
    #     print("JSON file successfully updated.")
    # except Exception as e:
    #     print(f"Error while saving the JSON file: {e}")

    return data

delete_scene(s3,"video_user_test1",2)

[{'video_id': 'video_user_test1',
  'user_id': 'user_test1',
  'date_created': '2024-05-19T16:41:49.015610',
  'video_key': 'generated_videos/video_user_test1/final_video.mp4',
  'video_type': 'image',
  'video_parts': [{'key': 1,
    'duration': 4.18,
    'media_key': 'datalake_media/image-digital-marketing-1725340_150.jpg-785e05fd-a610-4695-bc63-a660b1899a81',
    'audio_key': 'generated_videos/video_user_test1/audio1',
    'text': 'A balanced diet is essential for maintaining optimal health and well-being.',
    'subtitles': 'Une alimentation équilibrée est essentielle pour maintenir une santé et un bien-être optimaux.',
    'video_part_key': 'generated_videos/video_user_test1/video_user_test1_part_1.mp4'},
   {'key': 3,
    'duration': 3.71,
    'media_key': 'datalake_media/image-food-366875_150.jpg-f0e09e54-05bc-4d56-a5eb-f22e6de7cf23',
    'audio_key': 'generated_videos/video_user_test1/audio3',
    'text': ' you can ensure you are getting the necessary nutrients your body needs.',
    'subtitles': 'vous pouvez vous assurer que vous allez obtenir les nutriments nécessaires dont votre corps a besoin.',
    'video_part_key': 'generated_videos/video_user_test1/video_user_test1_part_3.mp4'},
   {'key': 4,
    'duration': 3.19,
    'media_key': 'datalake_media/image-vitamins-7661774_150.jpg-9838811c-b35a-4769-9817-9f6f4903ced9',
    'audio_key': 'generated_videos/video_user_test1/audio4',
    'text': 'This diverse mix of foods provides vitamins, minerals',
    'subtitles': "Ce mélange diversifié d'aliments fournit des vitamines, des minéraux",
    'video_part_key': 'generated_videos/video_user_test1/video_user_test1_part_4.mp4'},
   {'key': 5,
    'duration': 4.68,
    'media_key': 'datalake_media/image-health-621356_150.jpg-87d96282-95ee-4a3b-be94-db291ebf7974',
    'audio_key': 'generated_videos/video_user_test1/audio5',
    'text': ' and antioxidants that support various bodily functions and help prevent diseases.',
    'subtitles': 'et antioxydants qui soutiennent diverses fonctions corporelles et aident à prévenir les maladies.',
    'video_part_key': 'generated_videos/video_user_test1/video_user_test1_part_5.mp4'},
   {'key': 6,
    'duration': 2.53,
    'media_key': 'datalake_media/image-man-3011213_150.jpg-46321a60-fc08-4bc9-905d-6a02ffcf853d',
    'audio_key': 'generated_videos/video_user_test1/audio6',
    'text': 'A balanced diet can help you manage your weight',
    'subtitles': 'Une alimentation équilibrée peut vous aider à gérer votre poids',
    'video_part_key': 'generated_videos/video_user_test1/video_user_test1_part_6.mp4'},
   {'key': 7,
    'duration': 3.47,
    'media_key': 'datalake_media/image-astronaut-1784245_150.jpg-0b77e274-1bce-4915-94d4-2fea79b01624',
    'audio_key': 'generated_videos/video_user_test1/audio7',
    'text': ' boost your energy levels, and strengthen your immune system.',
    'subtitles': "augmenter vos niveaux d'énergie et renforcer votre système immunitaire.",
    'video_part_key': 'generated_videos/video_user_test1/video_user_test1_part_7.mp4'},
   {'key': 8,
    'duration': 4.78,
    'media_key': 'datalake_media/image-salad-2068217_150.jpg-267e2def-04d3-437f-b3d0-7cc07c29636b',
    'audio_key': 'generated_videos/video_user_test1/audio8',
    'text': 'It also plays a crucial role in promoting healthy bones, teeth, and mental well-being.',
    'subtitles': 'Elle joue également un rôle crucial dans la promotion de la santé des os, des dents et du bien-être mental.',
    'video_part_key': 'generated_videos/video_user_test1/video_user_test1_part_8.mp4'},
   {'key': 9,
    'duration': 3.76,
    'media_key': 'datalake_media/image-scale-403585_150.jpg-607dfa8b-2007-47e9-be5d-7dd7d8715ad0',
    'audio_key': 'generated_videos/video_user_test1/audio9',
    'text': 'Embracing a balanced diet is a cornerstone of a healthy lifestyle',
    'subtitles': "Faire place à une alimentation équilibrée est la pierre angulaire d'un mode de vie sain",
    'video_part_key': 'generated_videos/video_user_test1/video_user_test1_part_9.mp4'},
   {'key': 10,
    'duration': 3.94,
    'media_key': 'datalake_media/image-a-change-in-lifestyle-1430599_150.jpg-0a6fdabb-fb8a-48f5-acef-ac0eff1f4053',
    'audio_key': 'generated_videos/video_user_test1/audio10',
    'text': ' offering a multitude of benefits for your overall health and vitality.',
    'subtitles': "offrant une multitude d'avantages pour votre santé globale et votre vitalité.",
    'video_part_key': 'generated_videos/video_user_test1/video_user_test1_part_10.mp4'}]},
 {'video_id': 'video_user1',
  'user_id': 'user1',
  'date_created': '2024-05-19T17:14:08.748200',
  'video_key': 'generated_videos/video_user1/final_video.mp4',
  'video_type': 'image',
  'video_parts': [{'key': 1,
    'duration': 6.73,
    'media_key': 'datalake_media/image-woman-591576_150.jpg-fd7a98bb-bc35-4f25-9c8f-5cefe47c0545',
    'audio_key': 'generated_videos/video_user1/audio1',
    'text': "Nature's tranquility envelops us, with whispering trees and singing birds.",
    'subtitles': "Nature's tranquility envelops us, with whispering trees and singing birds.",
    'video_part_key': 'generated_videos/video_user1/video_user1_part_1.mp4'},
   {'key': 3,
    'duration': 7.56,
    'media_key': 'datalake_media/image-mountains-615428_150.jpg-ac78af82-afb6-47da-a3d3-a1ae0683fb78',
    'audio_key': 'generated_videos/video_user1/audio3',
    'text': 'Majestic mountains reach for the sky, while stars twinkle overhead.',
    'subtitles': 'Majestic mountains reach for the sky, while stars twinkle overhead.',
    'video_part_key': 'generated_videos/video_user1/video_user1_part_3.mp4'},
   {'key': 4,
    'duration': 7.52,
    'media_key': 'datalake_media/image-loveourplanet-4851331_150.jpg-3c37bf5d-9e2b-44d0-8b91-d7e1c78df429',
    'audio_key': 'generated_videos/video_user1/audio4',
    'text': "In nature's embrace, peace reigns, offering a timeless sanctuary for all.",
    'subtitles': "In nature's embrace, peace reigns, offering a timeless sanctuary for all.",
    'video_part_key': 'generated_videos/video_user1/video_user1_part_4.mp4'}]}]

In [46]:
import json
import boto3
from botocore.exceptions import ClientError

def get_last_key(video):
    if video['video_parts']:
        return max(part['key'] for part in video['video_parts'])
    else:
        return 0

def add_video_part(s3, video_id, new_video_part):
    try:
        response = s3.get_object(Bucket='soulchain-dev1-output-video', Key='video_info.json')
        data = json.loads(response['Body'].read())
    except ClientError as e:
        if e.response['Error']['Code'] == 'NoSuchKey':
            print("No video_info.json file found.")
            return
        else:
            raise

    video = next((v for v in data if v["video_id"] == video_id), None)

    if video:
        last_key = get_last_key(video)
        new_video_part["key"] = last_key + 1
        new_video_part["video_part_key"] = f"generated_videos/{video_id}/{video_id}e_part_{last_key + 1}.mp4"
        new_video_part["audio_key"]=f"generated_videos/{video_id}/audio{last_key + 1}"
        video['video_parts'].append(new_video_part)
    else:
        print(f"No video found with video_id: {video_id}")
        return

    try:
        updated_data = json.dumps(data)
        s3.put_object(Bucket='soulchain-dev1-output-video', Key='video_info.json', Body=updated_data)
        print("JSON file successfully updated.")
    except Exception as e:
        print(f"Error while saving the JSON file: {e}")

    return video

# Example usage
video_id_to_add = 'video_userimane'
new_video_part = {
    "duration": 4.5,
    "media_key": "datalake_media/new_image.jpg",
    "text": "New video part text",
    "subtitles": "New video part subtitles"
}

s3 = boto3.client('s3', aws_access_key_id="AKIAUJXLE2HEOGWEMCEX", aws_secret_access_key="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", region_name='eu-west-1')

video=add_video_part(s3, "video_user_test1", new_video_part)

In [47]:
with open('video.json', 'w') as f:
    json.dump(video, f)

In [49]:
url = "https://soulchain-dev1-output-video.s3.amazonaws.com/datalake_media/image-maine-coon-694730_150.jpg-5f8069af-9883-4373-801b-13a155ecd0b8"
base_url = "https://soulchain-dev1-output-video.s3.amazonaws.com/"
modified_url = url.replace(base_url, "")
print(modified_url)

datalake_media/image-maine-coon-694730_150.jpg-5f8069af-9883-4373-801b-13a155ecd0b8

In [50]:

new_media_paths=["https://soulchain-dev1-output-video.s3.amazonaws.com/datalake_media/image-maine-coon-694730_150.jpg-5f8069af-9883-4373-801b-13a155ecd0b8","https://soulchain-dev1-output-video.s3.amazonaws.com/datalake_media/image-maine-coon-694730_150.jpg-5f8069af-9883-4373-801b-13a155ecd0b8"]
base_url = "https://soulchain-dev1-output-video.s3.amazonaws.com/"
new_media_paths = [url.replace(base_url, "") for url in new_media_paths]

In [51]:
new_media_paths

['datalake_media/image-maine-coon-694730_150.jpg-5f8069af-9883-4373-801b-13a155ecd0b8',
 'datalake_media/image-maine-coon-694730_150.jpg-5f8069af-9883-4373-801b-13a155ecd0b8']

In [1]:
from topic import find_topics  
from audio import audio_generation
import json
import boto3
from botocore.exceptions import ClientError
import pandas as pd
from image import make_video_from_images_test
from video import make_video_from_video_test



def get_last_key(video):
    if video['video_parts']:
        return max(part['key'] for part in video['video_parts'])
    else:
        return 0
    

def generate_video_for_scene(s3,metadata,text,media_type,lang,user_id,video_id,api_key,image_folder,final_video_width, final_video_height,sub,indx):
    df = find_topics(text)
   
    if media_type=='image':
        video_parts=make_video_from_images_test(s3,lang,df,user_id,video_id,api_key,image_folder, metadata,final_video_width, final_video_height,sub,indx)
    if media_type=='video':
        video_parts=make_video_from_images_test()

    return video_parts["video_parts"][0]

def add_video_part(s3, video_id, metadata, text, media_type, lang, user_id, api_key, image_folder, final_video_width, final_video_height, sub):
    try:
        response = s3.get_object(Bucket='soulchain-dev1-output-video', Key='video_info.json')
        data = json.loads(response['Body'].read())
    except ClientError as e:
        if e.response['Error']['Code'] == 'NoSuchKey':
            print("No video_info.json file found.")
            return
        else:
            raise

    video = next((v for v in data if v["video_id"] == video_id), None)

    if video:
        last_key = max(part['key'] for part in video['video_parts']) if video['video_parts'] else 0
        indx = last_key + 1
        new_video_part = generate_video_for_scene(s3,metadata,text,media_type,lang,user_id,video_id,api_key,image_folder,final_video_width, final_video_height,sub,indx)

        new_video_part["key"] = indx
        new_video_part["video_part_key"] = f"generated_videos/{video_id}/{video_id}_part_{indx}.mp4"
        new_video_part["audio_key"] = f"generated_videos/{video_id}/audio{indx}"
        video['video_parts'].append(new_video_part)
    else:
        print(f"No video found with video_id: {video_id}")
        return

    try:
        updated_data = json.dumps(data)
        s3.put_object(Bucket='soulchain-dev1-output-video', Key='video_info.json', Body=updated_data)
        print("JSON file successfully updated.")
    except Exception as e:
        print(f"Error while saving the JSON file: {e}")

    return video

/Users/fatimaezzahrasounnyslitine/Library/Python/3.9/lib/python/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [3]:
from datalake import read_metadata_from_s3
import json
import boto3
from botocore.exceptions import ClientError
import pandas as pd
metadata=read_metadata_from_s3("soulchain-dev1-output-video", "metadata.xlsx")
s3 = boto3.client('s3', aws_access_key_id="AKIAUJXLE2HEOGWEMCEX", aws_secret_access_key="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", region_name='eu-west-1')
pixabay_api_key = "41475535-6d87f1c0e99d7a58bc22bfbda"

video=add_video_part(s3, "video_user1", metadata, "In nature's embrace", "image", "None", "user1", pixabay_api_key, "data",1920 ,1080 , "True")

processed_image_paths:  ['datalake_media/image-ai-generated-8620359_150.png-9776a9ce-9644-4aa3-8015-16b034177095', 'datalake_media/image-flower-5039811_150.jpg-773b9040-b440-4a74-80f7-570dd0c2da62', 'datalake_media/image-mountains-615428_150.jpg-ac78af82-afb6-47da-a3d3-a1ae0683fb78', 'datalake_media/image-loveourplanet-4851331_150.jpg-3c37bf5d-9e2b-44d0-8b91-d7e1c78df429', 'datalake_media/image-zoo-8378189_150.jpg-6a215b7e-a261-4979-8cca-032f4150ceea', 'datalake_media/image-spring-2174750_150.jpg-5d4ae088-ca92-4280-a790-a8304c8a74ee']
finding in datalake
image_found and topic_found

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

creating text clip
In nature's embrace
ro

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

subtitles In nature's embrace
Moviepy - Building video /var/folders/ys/s5c8y6vx2n95hnjtr5vs5h000000gn/T/tmpim1_glz1.mp4.
MoviePy - Writing audio in tmpim1_glz1TEMP_MPY_wvf_snd.mp4

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

MoviePy - Done.
Moviepy - Writing video /var/folders/ys/s5c8y6vx2n95hnjtr5vs5h000000gn/T/tmpim1_glz1.mp4

Moviepy - Done !
Moviepy - video ready /var/folders/ys/s5c8y6vx2n95hnjtr5vs5h000000gn/T/tmpim1_glz1.mp4
Successfully uploaded the final video to S3.
JSON file successfully updated.

In [2]:
video

NameError: name 'video' is not defined

In [21]:
url =[ "https://soulchain-dev1-output-video.s3.eu-west-1.amazonaws.com/datalake_media/image-cat-5157628_150.png-b4a69beb-ce0d-4d0b-89c5-e9bccf68512b?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=AKIAUJXLE2HEOGWEMCEX%2F20240520%2Feu-west-1%2Fs3%2Faws4_request&X-Amz-Date=20240520T140211Z&X-Amz-Expires=180000&X-Amz-Signature=c7eaa75ad82bb9add061c23f4b35c4ee9dc2655e930cfb3562d61ab93c3db5f2&X-Amz-SignedHeaders=host&x-id=GetObject"]

start_index = url.find("datalake_media")

end_index = url.find("?", start_index)

if end_index != -1:
    relevant_part = url[start_index:end_index]
else:
    relevant_part = url[start_index:]

print(relevant_part)

datalake_media/image-cat-5157628_150.png-b4a69beb-ce0d-4d0b-89c5-e9bccf68512b

In [22]:
new_media_paths=[ "https://soulchain-dev1-output-video.s3.eu-west-1.amazonaws.com/datalake_media/image-cat-5157628_150.png-b4a69beb-ce0d-4d0b-89c5-e9bccf68512b?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=AKIAUJXLE2HEOGWEMCEX%2F20240520%2Feu-west-1%2Fs3%2Faws4_request&X-Amz-Date=20240520T140211Z&X-Amz-Expires=180000&X-Amz-Signature=c7eaa75ad82bb9add061c23f4b35c4ee9dc2655e930cfb3562d61ab93c3db5f2&X-Amz-SignedHeaders=host&x-id=GetObject"]

if new_media_paths and isinstance(new_media_paths, list):
    updated_media_paths = []
    
    for path in new_media_paths:
        start_index = path.find("datalake_media")
        
        if start_index != -1:
            end_index = path.find("?", start_index)
            
            if end_index != -1:
                updated_media_paths.append(path[start_index:end_index])
            else:
                updated_media_paths.append(path[start_index:])
    
    new_media_paths = updated_media_paths
else:
    new_media_paths = []

In [23]:
new_media_paths

['datalake_media/image-cat-5157628_150.png-b4a69beb-ce0d-4d0b-89c5-e9bccf68512b']

In [18]:
import requests
import os
import pandas as pd
from PIL import Image
from transformers import VisionEncoderDecoderModel, ViTImageProcessor, AutoTokenizer
from keybert import KeyBERT
from moviepy.editor import VideoFileClip
import cv2
import torch
from collections import Counter
from datalake import upload_file_to_s3, generate_download_url, download_file_from_s3, put_image_in_s3
import io
import uuid
import boto3
from pathlib import Path
from nltk.stem import PorterStemmer
from nltk.tokenize import word_tokenize
from nltk.corpus import wordnet
from datalake import read_metadata_from_s3




def stem_words(word,porter):
    stemmed_word = porter.stem(word) 
    return stemmed_word

def find_video_for_term(term, processed_terms, processed_video_paths, metadata, video_folder):

    topic_found = False
    video_found = False
    video_name = None
    metadata = metadata.dropna(subset=['keywords_description'])
    new_metadata = metadata[~metadata['path_datalake'].isin(processed_video_paths)]
    url_datalake_path = None 

    if term not in processed_terms:
        for idx, meta_row in new_metadata.iterrows():
            main_topic_stemmed = meta_row['main_topic']  # Assuming main_topic is a list of stemmed words
            # Check for exact match
            main_topic_list = eval(main_topic_stemmed)
            if term in main_topic_list:  
                video_name = meta_row['name']
                url_datalake_path = meta_row['path_datalake'] 
                if url_datalake_path is not None:
                    processed_terms.add(term)
                    topic_found = True
                    video_found = True
                break

    return topic_found, video_found, video_name, url_datalake_path


def get_video_duration(video_url):
    try:
        clip = VideoFileClip(video_url)
        duration = clip.duration
        clip.close()
        return duration
    except Exception as e:
        print(f"Error occurred while getting video duration: {str(e)}")
        return 0
    
def is_video_readable(file_path):
    try:
        cap = cv2.VideoCapture(file_path)
        
        if cap.isOpened():
            cap.release()  
            return True
        else:
            return False
    except Exception as e:
        print(f"Error: {e}")
        return False

def lexical_similarity(word1, word2):
    synsets1 = wordnet.synsets(word1)
    synsets2 = wordnet.synsets(word2)

    max_similarity = 0

    for synset1 in synsets1:
        for synset2 in synsets2:
            similarity = synset1.wup_similarity(synset2)  # Wu-Palmer Similarity
            if similarity is not None and similarity > max_similarity:
                max_similarity = similarity

    return max_similarity

def search_pixabay_video(query, api_key,processed_video_paths, per_page=3, safe_search=True):
    safe_search_param = 'true' if safe_search else 'false'
    processed_video_paths=[path.split('.mp4')[0].replace("datalake_media/video-", "") + '.mp4' if '.mp4' in path else path.replace("datalake_media/video-", "") for path in processed_video_paths]
    url = f'https://pixabay.com/api/videos/?key={api_key}&q={query}&per_page={per_page}&safesearch={safe_search_param}'
    response = requests.get(url)
    videos_data = response.json()['hits']

    if response.status_code == 200:
        hits = response.json()['hits']
        if hits:
            videos = []
            for resp in hits:
                print("tags",resp['tags'])
                url_resp = resp['videos']['large']['url']
                filename = url_resp.split('/')[-1].split('?')[0]
                keywords = resp['tags'].split(', ')
                topic_name = keywords[0]
                score = lexical_similarity(query, topic_name)
                print("Score between:", topic_name, " and ", query, " is ", score)
                if score ==0:
                    videos=[]
                    break
                if score >= 0.4:
                    if filename not in processed_video_paths:
                        videos.append(resp)
                    else:
                        print("filename ",filename, 'is already used')
                elif score <= 0.4:
                    current_page = 1
                    while len(videos) < 1:
                        current_page += 1
                        new_url = f'https://pixabay.com/api/videos/?key={api_key}&q={query}&per_page={per_page}&safesearch={safe_search_param}&page={current_page}'
                        new_response = requests.get(new_url)
                        if new_response.status_code == 200:
                            new_hits = new_response.json()['hits']
                            if not new_hits:
                                break  
                            for new_resp in new_hits:
                                new_preview_url = new_resp['videos']['large']['url']
                                new_filename = new_preview_url.split('/')[-1].split('?')[0]
                                print(new_filename)
                                new_keywords = new_resp['tags'].split(', ')
                                new_topic_name = new_keywords[0]
                                new_score = lexical_similarity(query, new_topic_name)
                                print("Score between:", new_topic_name, " and ", query, " is ", new_score)
                                if new_score >= 0.4:
                                    if new_filename not in processed_video_paths:
                                        videos.append(new_resp)
                                    else:
                                        print(new_filename,'file already in metadata')
                        else:
                            break
            return videos
        else:
            print(f"No videos found for query: {query}")
            return []
    else:
        print(f"Error: Failed to retrieve videos for query: {query}")
        return []


def download_media(media, video_folder,metadata):
    url = media['videos']['large']['url']
    filename = url.split('/')[-1].split('?')[0]
    print("filename is:", filename)
    if filename == '':
        s3_key = None
        print("filepath is None")
    else:
        os.makedirs(video_folder, exist_ok=True)
        filepath = os.path.join(video_folder, filename)
        with open(filepath, 'wb') as f:
            print(filepath)
            f.write(requests.get(url).content)
        video_opened =is_video_readable(filepath)
        if video_opened==True :
            output_bucket = "soulchain-dev1-output-video"
            s3_key = f"datalake_media/video-{filename}-{str(uuid.uuid4())}"
            put_image_in_s3(requests.get(url).content, output_bucket, s3_key)
        else: 
            s3_key=None

    return filename, s3_key

def create_video_dataframe(videos, keywords, term, folder,metadata):
    data = []
    for video in videos:
        if video is not None:
            name,path_datalake = download_media(video, folder,metadata)
            if name is not None and path_datalake is not None:  
                url = video['videos']['large']['url']
                data.append([name, keywords, url, 'video', term,path_datalake,0,0,'useful'])
    columns = ['name', 'keywords', 'url', 'type', 'term','path_datalake','count_usage','count_edit','media_state']
    return pd.DataFrame(data, columns=columns)

def stem_words_(words):
    porter = PorterStemmer()
    tokens = word_tokenize(words)
    stemmed_words = [porter.stem(word) for word in tokens]

    return stemmed_words

def find_main_terms(row, n=3):
    combined_keywords = row['topic_name']+[row['term']]+ row['keywords'] + row['keywords_description'] 
    stemmed_keywords = stem_words_(' '.join(combined_keywords))
    keyword_freq = pd.Series(stemmed_keywords).value_counts()
    print(keyword_freq)
    top_terms = keyword_freq.head(n).index.tolist()

    return top_terms

def search_videos_for_dataframe_pixabay(term, api_key, video_folder,metadata):
    video_dataframes = []
    used_terms = set()
    if term not in used_terms:
        videos = search_pixabay_video(term, api_key)
        if videos:
            for video in videos:
                keywords = video['tags'].split(', ')
                df_video = create_video_dataframe([video], keywords, term, video_folder,metadata)
                video_paths = df_video['name']
                #print("video_paths:", video_paths)
                print("video path:",video_paths)
                preds_string, description_keywords = generate_video_description(video_paths)
                df_video['description'] = preds_string
                df_video['keywords_description'] = description_keywords
                video_dataframes.append(df_video)
                
            used_terms.add(term)

    videos_df = pd.concat(video_dataframes, ignore_index=True)
    metadata_file = 'metadata.xlsx' #should change    
    merged_metadata = pd.concat([videos_df, metadata], ignore_index=True)
    merged_metadata['source'] = 'pixabay'
    merged_metadata.to_excel(metadata_file, index=False)
    
    return videos_df


def search_video_for_dataframe_pixabay_video(terms, api_key,video_folder,processed_video_paths):
    metadata=read_metadata_from_s3("soulchain-dev1-output-video", "metadata.xlsx")
    video_dataframes = []
    used_terms = set()
    for term in terms:
        if term not in used_terms:
            videos = search_pixabay_video(term, api_key,processed_video_paths)
            if videos:
                for video in videos:
                    keywords = video['tags'].split(', ')
                    keywords=str(keywords)
                    df_video = create_video_dataframe([video], keywords, term, video_folder, metadata)
                    video_paths = df_video['name']
                    #preds_string, description_keywords = generate_video_description(video_paths,video_folder)
                    df_video['description'] = ""
                    df_video['keywords_description'] = str([])
                    df_video['term']= df_video['term'].astype(str)
                    df_video['topic_name'] = df_video['name'].str.split('-').str[0].apply(lambda x: [x])
                    df_video['keywords_description'] = df_video['keywords_description'].apply(lambda x: eval(x))
                    df_video['keywords'] = df_video['keywords'].apply(lambda x: eval(x))
                    df_video['main_topic'] = df_video.apply(find_main_terms, axis=1)
                    video_dataframes.append(df_video)

                used_terms.add(term)
                break
        

    videos_df = pd.concat(video_dataframes, ignore_index=True)
    print(videos_df)
    merged_metadata = pd.concat([videos_df, metadata], ignore_index=True)
    merged_metadata['source'] = 'pixabay'

    video_path=videos_df['path_datalake'][0]

    with io.BytesIO() as buffer:
            merged_metadata.to_excel(buffer, index=False)
            buffer.seek(0)
            data_bytes = buffer.read() 
    put_image_in_s3(data_bytes,"soulchain-dev1-output-video", "metadata.xlsx")
         
    return  merged_metadata

In [21]:

df=search_video_for_dataframe_pixabay_video(["cat"], "41475535-6d87f1c0e99d7a58bc22bfbda","dat",[])

tags cat, sleep, pet
Score between: cat  and  cat  is  1.0
tags cat, orange cat, domestic cat
Score between: cat  and  cat  is  1.0
tags cat, animal, sleep
Score between: cat  and  cat  is  1.0
filename is: 39009-420224623_large.mp4
dat/39009-420224623_large.mp4
Media uploaded successfully to S3
cat      2
39009    1
sleep    1
pet      1
Name: count, dtype: int64
filename is: 179212-861403629_large.mp4
dat/179212-861403629_large.mp4
Media uploaded successfully to S3
cat       4
179212    1
orang     1
domest    1
Name: count, dtype: int64
filename is: 39010-420224640_large.mp4
dat/39010-420224640_large.mp4
Media uploaded successfully to S3
cat      2
39010    1
anim     1
sleep    1
Name: count, dtype: int64
                         name                         keywords  \
0   39009-420224623_large.mp4                [cat, sleep, pet]
1  179212-861403629_large.mp4  [cat, orange cat, domestic cat]
2   39010-420224640_large.mp4             [cat, animal, sleep]

                                                 url   type term  \
0  https://cdn.pixabay.com/video/2020/05/13/39009...  video  cat
1  https://cdn.pixabay.com/video/2023/09/05/17921...  video  cat
2  https://cdn.pixabay.com/video/2020/05/13/39010...  video  cat

                                       path_datalake  count_usage  count_edit  \
0  datalake_media/video-39009-420224623_large.mp4...            0           0
1  datalake_media/video-179212-861403629_large.mp...            0           0
2  datalake_media/video-39010-420224640_large.mp4...            0           0

  media_state description keywords_description topic_name  \
0      useful                               []    [39009]
1      useful                               []   [179212]
2      useful                               []    [39010]

             main_topic
0   [cat, 39009, sleep]
1  [cat, 179212, orang]
2    [cat, 39010, anim]
Media uploaded successfully to S3

In [22]:
df

,name,keywords,url,type,term,path_datalake,count_usage,count_edit,media_state,description,keywords_description,topic_name,main_topic,source,Unnamed: 0
0,39009-420224623_large.mp4,"[cat, sleep, pet]",https://cdn.pixabay.com/video/2020/05/13/39009...,video,cat,datalake_media/video-39009-420224623_large.mp4...,0,0,useful,,[],[39009],"[cat, 39009, sleep]",pixabay,NaN
1,179212-861403629_large.mp4,"[cat, orange cat, domestic cat]",https://cdn.pixabay.com/video/2023/09/05/17921...,video,cat,datalake_media/video-179212-861403629_large.mp...,0,0,useful,,[],[179212],"[cat, 179212, orang]",pixabay,NaN
2,39010-420224640_large.mp4,"[cat, animal, sleep]",https://cdn.pixabay.com/video/2020/05/13/39010...,video,cat,datalake_media/video-39010-420224640_large.mp4...,0,0,useful,,[],[39010],"[cat, 39010, anim]",pixabay,NaN
3,_cat_google,[],https://www.healthyeating.org/images/default-s...,image,NaN,datalake_media/image--03a5ddf4-4d3c-45ae-93ea-...,0,0,useful,,[],[],[''],pixabay,NaN
4,cat_image_google,[],https://cdn.britannica.com/70/234870-050-D4D02...,image,cat,datalake_media/image-cat-1b2b7ea0-4375-46b9-8f...,0,0,useful,,[],[],['cat'],pixabay,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4583,sunflower-3113318_150.jpg,"['sunflower', 'nature', 'flower background']",https://cdn.pixabay.com/photo/2018/01/28/11/24...,image,sunflower,datalake_media/image-sunflower-3113318_150.jpg...,0,0,useful,a close up picture of a flower in the sun,"['flower', 'sun', 'picture', 'close']",['sunflower'],"['sunflow', 'flower', 'natur']",pixabay,5197.0
4584,sunflower-1627193_150.jpg,"['sunflower', 'yellow', 'flower']",https://cdn.pixabay.com/photo/2016/08/28/23/24...,image,sunflower,datalake_media/image-sunflower-1627193_150.jpg...,0,0,useful,a close up view of a bunch of yellow flowers,"['flowers', 'yellow', 'view', 'bunch', 'close']",['sunflower'],"['sunflow', 'yellow', 'flower']",pixabay,5198.0
4585,sunflowers-59483.mp4,"['sunflowers', 'bees', 'field']",https://cdn.pixabay.com/vimeo/493557880/sunflo...,video,sunflower,datalake_media/video-sunflowers-59483.mp4-868f...,0,0,useful,a blue sky with a bunch of blue water,"['blue', 'sky', 'water', 'bunch']",['sunflowers'],"['sunflow', 'bee', 'field']",pixabay,5199.0
4586,squirrel-2717.mp4,"['squirrel', 'head', 'grey squirrel']",https://cdn.pixabay.com/vimeo/161687558/squirr...,video,sunflower,datalake_media/video-squirrel-2717.mp4-b61aec9...,0,0,useful,a small bird is perched on a tree branch,"['bird', 'tree', 'perched', 'branch', 'small']",['squirrel'],"['squirrel', 'sunflow', 'head']",pixabay,5200.0
4587,bird-9334.mp4,"['bird', 'sparrow', 'sunflower']",https://cdn.pixabay.com/vimeo/219173276/bird-9...,video,sunflower,datalake_media/video-bird-9334.mp4-02cbb64f-4f...,0,0,useful,a blue bird with a flower in it,"['bird', 'flower', 'blue']",['bird'],"['bird', 'sunflow', 'sparrow']",pixabay,5201.0

In [3]:
import base64
from datalake import put_image_in_s3

with open('audiotexte.txt', 'r') as file:
    base64_audio = file.read()

def upload_audio(video_id,audio_key,base64_audio):
    if base64_audio.startswith('data:audio/wav;base64,'):
        base64_audio = base64_audio.split(',')[1]

    audio_binary = base64.b64decode(base64_audio)
    put_image_in_s3(audio_binary,"soulchain-dev1-output-video",f"generated_videos/{video_id}/audio{audio_key}")

In [4]:
put_image_in_s3(audio_binary,"soulchain-dev1-output-video","audio33")

Media uploaded successfully to S3

In [4]:
import boto3
from moviepy.editor import AudioFileClip
import tempfile
s3 = boto3.client('s3', aws_access_key_id="AKIAUJXLE2HEOGWEMCEX",aws_secret_access_key="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",region_name='eu-west-1')

background_music_file="in_the_forest.mp3"
temp_audio_file = tempfile.NamedTemporaryFile(suffix='.mp3')

s3.download_file("soulchain-dev1-output-video", f"background_music/{background_music_file}", temp_audio_file.name)

background_music = AudioFileClip(background_music_file)

In [3]:
from topic import find_topics

df=find_topics("Nature's tranquility envelops us, with whispering trees and singing birds. Rivers flow gently, sunlight paints warmth, and flowers bloom vibrantly. Majestic mountains reach for the sky, while stars twinkle overhead. In nature's embrace, peace reigns, offering a timeless sanctuary for all.")

In [4]:
df

,id,original_sentence,sentence,topic,terms,sentence_part_id
0,1,"Nature's tranquility envelops us, with whisper...","Nature's tranquility envelops us, with whisper...",4,"[nature, birds, whispering, tranquility, trees]",0
1,2,"Rivers flow gently, sunlight paints warmth, an...","Rivers flow gently, sunlight paints warmth, an...",3,"[flowers, bloom, sunlight, rivers, vibrantly]",1
2,3,"Majestic mountains reach for the sky, while st...","Majestic mountains reach for the sky, while st...",4,"[mountains, sky, majestic, twinkle, stars]",2
3,4,"In nature's embrace, peace reigns, offering a ...","In nature's embrace, peace reigns, offering a ...",1,"[sanctuary, peace, timeless, embrace, nature]",3

In [20]:
from text import def_translation
from datetime import datetime, timedelta

lang="French"
video_id="video1"
user_id="user"

def split_text(s3,lang,df,user_id,video_id):

    try:
        response = s3.get_object(Bucket='soulchain-dev1-output-video', Key='video_info.json')

        existing_data_all = json.loads(response['Body'].read())
    except ClientError as e:
        if e.response['Error']['Code'] == 'NoSuchKey':
            existing_data_all = []
        else:
            raise
    indx=1
    topic_clips=[]
    video_parts=[]

    for index, row in df.iterrows():
        
        sentence = row['sentence']
        subtitles=def_translation(sentence,lang)
        key=f"generated_videos/{video_id}/{video_id}_part_{indx}.mp4"
        topic_clips.append(key)
        video_parts.append({
            'key':indx,
            'duration':0,
            'media_key': "",
            'audio_key': f"generated_videos/{video_id}/audio{indx}",
            'text':sentence,
            'subtitles':subtitles,
            'video_part_key': key
        })
        indx += 1

    date_created = datetime.now().isoformat() 
    output_data = {
        'video_id': video_id,
        'user_id': user_id,
        'date_created':date_created,
        'video_key':f"generated_videos/{video_id}/final_video.mp4",
        'video_type':'image',
        'video_parts': video_parts
        }
    
    existing_data_all.append(output_data)

    json_data = json.dumps(existing_data_all)
        
    s3.put_object(Bucket='soulchain-dev1-output-video', Key=f"video_info.json", Body=json_data)

English
data: {'text': "Nature's tranquility envelops us, with whispering trees and singing birds.", 'source': 'English', 'target': 'French'}
English
data: {'text': 'Rivers flow gently, sunlight paints warmth, and flowers bloom vibrantly.', 'source': 'English', 'target': 'French'}
English
data: {'text': 'Majestic mountains reach for the sky, while stars twinkle overhead.', 'source': 'English', 'target': 'French'}
English
data: {'text': "In nature's embrace, peace reigns, offering a timeless sanctuary for all.", 'source': 'English', 'target': 'French'}

In [21]:
output_data

{'video_id': 'video1',
 'user_id': 'user',
 'date_created': '2024-06-25T10:12:26.551848',
 'video_key': 'generated_videos/video1/final_video.mp4',
 'video_type': 'image',
 'video_parts': [{'key': 1,
   'duration': 0,
   'media_key': '',
   'audio_key': 'generated_videos/video1/audio1',
   'text': "Nature's tranquility envelops us, with whispering trees and singing birds.",
   'subtitles': 'La tranquillité de la nature nous enveloppe, avec des arbres murmurants et des oiseaux chantants.',
   'video_part_key': 'generated_videos/video1/video1_part_1.mp4'},
  {'key': 2,
   'duration': 0,
   'media_key': '',
   'audio_key': 'generated_videos/video1/audio2',
   'text': 'Rivers flow gently, sunlight paints warmth, and flowers bloom vibrantly.',
   'subtitles': 'Les rivières coulent doucement, le soleil peint la chaleur, et les fleurs fleurissent avec éclat.',
   'video_part_key': 'generated_videos/video1/video1_part_2.mp4'},
  {'key': 3,
   'duration': 0,
   'media_key': '',
   'audio_key': 'generated_videos/video1/audio3',
   'text': 'Majestic mountains reach for the sky, while stars twinkle overhead.',
   'subtitles': 'Des montagnes majestueuses atteignent le ciel, tandis que des étoiles brillent au-dessus.',
   'video_part_key': 'generated_videos/video1/video1_part_3.mp4'},
  {'key': 4,
   'duration': 0,
   'media_key': '',
   'audio_key': 'generated_videos/video1/audio4',
   'text': "In nature's embrace, peace reigns, offering a timeless sanctuary for all.",
   'subtitles': "Dans l'étreinte de la nature, la paix règne, offrant un sanctuaire intemporel pour tous.",
   'video_part_key': 'generated_videos/video1/video1_part_4.mp4'}]}

In [16]:
import json
from botocore.exceptions import ClientError
from moviepy.editor import VideoFileClip, ImageClip, AudioFileClip, CompositeVideoClip
import tempfile
from io import BytesIO
from PIL import Image
import numpy as np
import requests
import uuid
import os
import boto3
session = boto3.Session(region_name='eu-west-1')
s3 = session.client('s3',aws_access_key_id="AKIAUJXLE2HEM4YQVOSA",aws_secret_access_key="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")

try:
    response_audio = s3.get_object(Bucket='soulchain-dev1-output-video', Key="generated_videos/video_safir/audio4")
    audio_data = response_audio['Body'].read()
except Exception as e:
    print("Error reading audio from S3:", e)

with tempfile.NamedTemporaryFile(suffix='.mp3') as temp_file:
    temp_file.write(audio_data)
    temp_file.seek(0)  
    
    audio = AudioFileClip(temp_file.name)
    
    duration = audio.duration

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

In [17]:
duration

7.01

In [31]:
from text_to_media import find_media_best
import pandas as pd


df=pd.read_excel("metadata_mixkit_unsplash_pixabay.xlsx")

In [33]:
result=[]
df_video=df[df["type"]=="video"]
for index, row in df_video.iterrows():
    if "food" in row['keywords'] and "body" in row['keywords']:
        result.append(row)

result

[]

In [34]:
result=[]
df_image=df[df["type"]=="video"]
for index, row in df_image.iterrows():
    if "food" in row['keywords'] and "body" in row['keywords']:
        result.append(row)

result

[]

In [ ]:
def update_media_in_json(s3,video_id,metadata, media_keys, new_media_paths):
    try:
        response = s3.get_object(Bucket='soulchain-dev1-output-video', Key='video_info.json')
        data = json.loads(response['Body'].read())
    except ClientError as e:
        if e.response['Error']['Code'] == 'NoSuchKey':
            data = []
        else:
            raise  

    print(new_media_paths)

    video = next((v for v in data if v["video_id"] == video_id), None)

    all_keys = []
    if video and "video_parts" in video:
        all_keys = [part['key'] for part in video['video_parts']]

    if media_keys=="all":
        media_keys= all_keys

    if video:
        for media_key, new_image_path in zip(media_keys, new_media_paths):
            part = next((p for p in video["video_parts"] if p["key"] == media_key), None)
            if part:
                old_filepath=part["media_key"]
                # metadata=update_media(metadata,old_filepath)
                # metadata.to_excel('metadata_mixkit_unsplash_pixabay.xlsx', index=False)
                part["media_key"] = new_image_path
    else:
        print("video id not found")
    try:
        data = json.dumps(data)
        s3.put_object(Bucket='soulchain-dev1-output-video', Key=f"video_info.json", Body=data)
        print("JSON file successfully updated.")
    except Exception as e:
        print(f"Error while saving the JSON file: {e}")