In [19]:
import pandas as pd
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import CountVectorizer
import numpy as np
from datalake import read_metadata_from_s3
from topic import find_topics

metadata=read_metadata_from_s3("soulchain-dev1-output-video", "metadata.xlsx")
text="Nature's tranquility envelops us, with whispering trees and singing birds."

df=find_topics(text)
topics=df["terms"].iloc[0]

def preprocess_text(text):
    # Convert text to lowercase
    text = text.lower()
    
    # Tokenize the text
    word_tokens = word_tokenize(text)
    
    # Remove stop words and keep only alphanumeric tokens
    stop_words = set(stopwords.words('english'))
    filtered_words = [w for w in word_tokens if w.isalnum() and w not in stop_words]
    
    return filtered_words

def calculate_similarity(text1, text2):
    # Create a CountVectorizer object and fit_transform the texts
    vectorizer = CountVectorizer().fit_transform([text1, text2])
    
    # Convert the text data into vectors
    vectors = vectorizer.toarray()
    
    # Compute the cosine similarity between the vectors
    cosine_sim = cosine_similarity(vectors)
    
    # Return the similarity score between the first and second text
    return cosine_sim[0][1]

def find_media(topics, metadata):
    # Preprocess the list of topics into a single string
    preprocessed_topics = ' '.join(topics)
    
    best_score = 0
    best_media_index = -1

    for index, row in metadata.iterrows():
        # Assume keywords are stored as a list of strings in 'keywords' column
        human_keywords = ' '.join(eval(row['keywords']))
        
        # Calculate similarity between preprocessed topics and media keywords
        human_similarity = calculate_similarity(preprocessed_topics, human_keywords)
        
        # Update best score and index if a higher similarity is found
        if human_similarity > best_score:
            best_score = human_similarity
            best_media_index = index

    # Return the path of the best matching media
    if best_media_index != -1:
        best_media_metadata = metadata.iloc[best_media_index]
        return best_media_metadata["path_datalake"]
    else:
        return "No matching media found."
    
metadata_image = metadata[(metadata["type"] == 'image') & (metadata["media_state"] == 'useful')]

path_datalake=find_media(topics, metadata_image)
path_datalake

'datalake_media/image-bacteria-426997_150.jpg-b9dd7ac9-fc25-4259-ba7d-d61704838a6e'

In [15]:
metadata_image[metadata_image["path_datalake"]=='datalake_media/image-nature-3151869_150.jpg-ad2a9ecd-df01-4a13-95f5-939a63458cd1']

                       name                       keywords  ...   source Unnamed: 0
739  nature-3151869_150.jpg  ['nature', 'forest', 'trees']  ...  pixabay      453.0

[1 rows x 15 columns]

In [29]:
from topic import find_topics

df = find_topics("Nature's tranquility envelops us, with whispering trees and singing birds.")
topics=df["terms"][0]

In [30]:
topics

['nature', 'birds', 'whispering', 'tranquility', 'trees']

In [9]:
import pandas as pd
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import CountVectorizer
import numpy as np
from datalake import read_metadata_from_s3


metadata=read_metadata_from_s3("soulchain-dev1-output-video", "metadata.xlsx")
metadata = metadata[(metadata["type"] == 'image') & (metadata["media_state"] == 'useful')]

#topics = ["needs", "meals", "vegetables", "proteins", "body", "whole"]
topics =["nature", "birds", "whispering", "tranquility", "trees"]

def preprocess_text(text):
    stop_words = set(stopwords.words('english'))
    word_tokens = word_tokenize(text.lower())
    filtered_words = [w for w in word_tokens if w.isalnum() and w not in stop_words]
    return filtered_words

def calculate_similarity(topics, keywords):
    vectorizer = CountVectorizer().fit_transform([topics, keywords])
    vectors = vectorizer.toarray()
    cosine_sim = cosine_similarity(vectors)
    return cosine_sim[0][1]

preprocessed_topics = ' '.join(topics)

top_scores = []

for index, row in metadata.iterrows():
    human_keywords = ' '.join(eval(row['keywords']))
    ai_keywords = ' '.join(eval(row['keywords_description']))
    
    human_similarity = calculate_similarity(preprocessed_topics, human_keywords)
    ai_similarity = calculate_similarity(preprocessed_topics, ai_keywords)
    
    avg_similarity = (human_similarity + ai_similarity) / 2
    
    top_scores.append((avg_similarity, index))

top_scores.sort(reverse=True, key=lambda x: x[0])
top_3_scores = top_scores[:100]

for score, index in top_3_scores:
    best_image_metadata = metadata.iloc[index]
    print(f"Score: {score}")
    print(f"Path to image: {best_image_metadata['path_datalake']}")
    print()

Score: 0.35819888974716113
Path to image: datalake_media/image-board-5599231_150.png-c7970a18-9e8a-42e9-81b5-471e39e4f654

Score: 0.35819888974716113
Path to image: datalake_media/image-baby-7540912_150.jpg-6d5fc0f1-83a7-4755-8b87-e8927b40208d

Score: 0.2872133278819995
Path to image: datalake_media/image-fantasy-1481590_150.jpg-78095c96-a0b7-4847-b247-54a12d6ef22f

Score: 0.2872133278819995
Path to image: datalake_media/image-finger-2956974_150.jpg-25f76f17-72da-4e3b-bf80-870cf26d6dd9

Score: 0.25819888974716115
Path to image: datalake_media/image-nature-3733115_150.jpg-bd4b2ab9-c724-4f6d-9c84-4cfc970d0a09

Score: 0.25819888974716115
Path to image: datalake_media/image-bacteria-426997_150.jpg-b9dd7ac9-fc25-4259-ba7d-d61704838a6e

Score: 0.25819888974716115
Path to image: datalake_media/image-rocket-3122690_150.png-8fbe64a9-db0d-4a31-a496-01069dfc47ed

Score: 0.25819888974716115
Path to image: datalake_media/image-ribs-front-2931058_150.png-408f487c-327b-4935-80a7-eee3310d26af

Score: 0.25819888974716115
Path to image: datalake_media/image-newborn-6177485_150.jpg-c5819502-47f4-4d95-874b-ac97751394fe

Score: 0.24090284374857007
Path to image: datalake_media/image-half-moon-4900302_150.jpg-4ad038b5-12c0-44de-b8e3-b9e8e0b0e40b

In [2]:
from text_to_media import find_media_best
from datalake import read_metadata_from_s3

metadata=read_metadata_from_s3("soulchain-dev1-output-video", "metadata_mixkit_unsplash_pixabay.xlsx")
metadata_video = metadata[metadata["type"] == 'video']
metadata_video = metadata_video[metadata_video["media_state"] == 'useful'] 
topic_found, video_found,video_path = find_media_best(["diets", "balanced", "energy", "fuel", "bodies"], [], metadata_video)

In [3]:
video_path

'datalake_media/video-sport-a6adb60f-419d-4d6e-8d08-17ff883c3abf'

In [1]:
from nltk.corpus import wordnet

def find_synonyms(word):
    synonyms = set()
    
    for syn in wordnet.synsets(word):
        for lemma in syn.lemmas():
            synonyms.add(lemma.name())
    
    return synonyms

synonyms = find_synonyms("nutrient")
synonyms

{'alimental',
 'alimentary',
 'food',
 'nourishing',
 'nutrient',
 'nutritious',
 'nutritive'}

In [25]:
from nltk.corpus import wordnet

def find_synonyms(word):
    synonyms = set()
    
    for syn in wordnet.synsets(word):
        for lemma in syn.lemmas():
            synonyms.add(lemma.name())
    
    return synonyms

synonyms = find_synonyms("food")

In [26]:
synonyms

{'food',
 'food_for_thought',
 'intellectual_nourishment',
 'nutrient',
 'solid_food'}

In [1]:
import requests
import io
from io import BytesIO
import uuid
import boto3
from openpyxl import load_workbook
from botocore.exceptions import ClientError
import os
from pathlib import Path
import pandas as pd

/Users/fatimaezzahrasounnyslitine/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(

In [2]:
def read_metadata_from_s3(bucket_name, file_key):
    s3 = boto3.client('s3', aws_access_key_id="AKIAUJXLE2HEM4YQVOSA",aws_secret_access_key="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",region_name='eu-west-1')
    obj = s3.get_object(Bucket=bucket_name, Key=file_key)
    return pd.read_excel(BytesIO(obj['Body'].read()))

In [8]:
df=read_metadata_from_s3("soulchain-dev1-output-video", "metadata_mixkit_unsplash_pixabay.xlsx")
df.head()

,Unnamed: 0,name,keywords,url,type,term,path_datalake,description,keywords_description,source,size,count_usage,count_edit,media_state
0,0,bygTaBey1Xk.jpg,"['grass', 'shore', 'ocean', 'coast', 'beach', ...",https://images.unsplash.com/uploads/1413387620...,image,grass,datalake_media/image-bygTaBey1Xk.jpg-c8c7df3c-...,sea and rock cliff with grasses under cloudy sky,"['cliff', 'grasses', 'cloudy', 'sky', 'rock']",unsplash,horizontal,0,0,useful
1,1,gXSFnk2a9V4.jpg,"['blue', 'holiday', 'geographical feature', 'a...",https://images.unsplash.com/reserve/jEs6K0y1Sb...,image,blue,datalake_media/image-gXSFnk2a9V4.jpg-a0496092-...,aerial photography of seashore,"['seashore', 'aerial', 'photography']",unsplash,vertical,0,0,useful
2,2,grg6-DNJuaU.jpg,"['sea', 'jump', 'waves', 'summer', 'holiday', ...",https://images.unsplash.com/uploads/1412192004...,image,sea,datalake_media/image-grg6-DNJuaU.jpg-c2b853ee-...,man surfboarding on ocean wave during daytime,"['surfboarding', 'ocean', 'wave', 'daytime', '...",unsplash,horizontal,0,0,useful
3,3,sO42hhChB1c.jpg,"['ocean', 'waves', 'mist', 'water', 'foam', 'd...",https://images.unsplash.com/reserve/ijl3tATFRp...,image,ocean,datalake_media/image-sO42hhChB1c.jpg-586ba674-...,body of water,"['water', 'body']",unsplash,horizontal,0,0,useful
4,4,tkk8_HakQ98.jpg,"['dawn', 'scenery', 'glow', 'dune', 'sunlight'...",https://images.unsplash.com/reserve/6vaWXsQuSW...,image,dawn,datalake_media/image-tkk8_HakQ98.jpg-9f60f63f-...,car on desert during sunset,"['sunset', 'desert', 'car']",unsplash,horizontal,0,0,useful

In [9]:
s3 = boto3.client('s3', aws_access_key_id="AKIAUJXLE2HEM4YQVOSA",aws_secret_access_key="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",region_name='eu-west-1')
list_=0   

for index, row in df.iterrows():
    try:
        s3.head_object(Bucket="soulchain-dev1-output-video", Key=row["path_datalake"])
        list_=list_+1
        
    except s3.exceptions.ClientError as e:
        if e.response['Error']['Code'] == '404':
            print(f"{row} does not exist in S3 bucket.")
        else:
            print(f"Error checking {row} in S3 bucket: {e}")
    except Exception as ex:
        print(f"Unexpected error checking {row} in S3 bucket: {ex}")

Unnamed: 0                                                            494
name                                         Boxer bleeding after a fight
keywords                ['"medium shot"', '"sport"', '"athlete"', '"tr...
url                     https://assets.mixkit.co/videos/preview/mixkit...
type                                                                video
term                                                                sport
path_datalake           datalake_media/video-sport-48b6b38b-d2c6-47b2-...
description             Injured and bleeding boxer sitting in a corner...
keywords_description    ['boxer', 'injured', 'sitting', 'ring', 'bleed...
source                                                             mixkit
size                                                           horizontal
count_usage                                                             0
count_edit                                                              0
media_state                                                        useful
Name: 18840, dtype: object does not exist in S3 bucket.

In [10]:
list_

19340

In [11]:
df

,Unnamed: 0,name,keywords,url,type,term,path_datalake,description,keywords_description,source,size,count_usage,count_edit,media_state
0,0,bygTaBey1Xk.jpg,"['grass', 'shore', 'ocean', 'coast', 'beach', ...",https://images.unsplash.com/uploads/1413387620...,image,grass,datalake_media/image-bygTaBey1Xk.jpg-c8c7df3c-...,sea and rock cliff with grasses under cloudy sky,"['cliff', 'grasses', 'cloudy', 'sky', 'rock']",unsplash,horizontal,0,0,useful
1,1,gXSFnk2a9V4.jpg,"['blue', 'holiday', 'geographical feature', 'a...",https://images.unsplash.com/reserve/jEs6K0y1Sb...,image,blue,datalake_media/image-gXSFnk2a9V4.jpg-a0496092-...,aerial photography of seashore,"['seashore', 'aerial', 'photography']",unsplash,vertical,0,0,useful
2,2,grg6-DNJuaU.jpg,"['sea', 'jump', 'waves', 'summer', 'holiday', ...",https://images.unsplash.com/uploads/1412192004...,image,sea,datalake_media/image-grg6-DNJuaU.jpg-c2b853ee-...,man surfboarding on ocean wave during daytime,"['surfboarding', 'ocean', 'wave', 'daytime', '...",unsplash,horizontal,0,0,useful
3,3,sO42hhChB1c.jpg,"['ocean', 'waves', 'mist', 'water', 'foam', 'd...",https://images.unsplash.com/reserve/ijl3tATFRp...,image,ocean,datalake_media/image-sO42hhChB1c.jpg-586ba674-...,body of water,"['water', 'body']",unsplash,horizontal,0,0,useful
4,4,tkk8_HakQ98.jpg,"['dawn', 'scenery', 'glow', 'dune', 'sunlight'...",https://images.unsplash.com/reserve/6vaWXsQuSW...,image,dawn,datalake_media/image-tkk8_HakQ98.jpg-9f60f63f-...,car on desert during sunset,"['sunset', 'desert', 'car']",unsplash,horizontal,0,0,useful
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19336,495,Person eating salad with fork,"['""close up""', '""fruit""', '""dish""', '""salad""',...",https://assets.mixkit.co/videos/preview/mixkit...,video,fruit,datalake_media/video-fruit-889d663a-bdeb-4d0b-...,Fork taking a bite of salad with pear and waln...,"['salad', 'fork', 'walnuts', 'pear', 'bite']",mixkit,horizontal,0,0,useful
19337,496,Housewife choosing fruit at the market,"['""portrait""', '""fruit""', '""market""', '""farmer...",https://assets.mixkit.co/videos/preview/mixkit...,video,fruit,datalake_media/video-fruit-ea12d715-6d45-4ede-...,NaN,[],mixkit,horizontal,0,0,useful
19338,497,Raspberries in the hands of a person,"['""fruit""', '""fruits""', '""gardening""']",https://assets.mixkit.co/videos/preview/mixkit...,video,fruit,datalake_media/video-fruit-362ef810-41f5-4c43-...,NaN,[],mixkit,horizontal,0,0,useful
19339,498,Various fruits on shelves in the market,"['""fruit""', '""market""', '""fruits""', '""farmers ...",https://assets.mixkit.co/videos/preview/mixkit...,video,fruit,datalake_media/video-fruit-df9f2cbc-6b26-4568-...,NaN,[],mixkit,horizontal,0,0,useful
19340,499,Old woman with a basket of apples,"['""fruit""', '""elderly""', '""old woman""', '""elde...",https://assets.mixkit.co/videos/preview/mixkit...,video,fruit,datalake_media/video-fruit-052fd18b-4408-4554-...,NaN,[],mixkit,horizontal,0,0,useful