In [6]:
import pandas as pd
import cv2
from PIL import Image
import boto3
from io import BytesIO
from datalake import read_metadata_from_s3
import tempfile

# Initialize boto3 client for S3
session = boto3.Session(region_name='eu-west-1')
s3 = session.client('s3',aws_access_key_id="AKIAUJXLE2HEOGWEMCEX",aws_secret_access_key="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")
metadata=read_metadata_from_s3("soulchain-dev1-output-video", "metadata.xlsx")
metadata = metadata[metadata["type"] == 'video']

# Function to get dimensions of a video
def get_video_dimensions(video_path):
    try:
        cap = cv2.VideoCapture(video_path)
        width = cap.get(cv2.CAP_PROP_FRAME_WIDTH)
        height = cap.get(cv2.CAP_PROP_FRAME_HEIGHT)
        cap.release()
        return int(width), int(height)
    except Exception as e:
        print(f"Error getting video dimensions: {e}")
        return None, None

# Function to get dimensions of an image
def get_image_dimensions(image_path):
    try:
        image = Image.open(image_path)
        width, height = image.size
        return width, height
    except Exception as e:
        print(f"Error getting image dimensions: {e}")
        return None, None

# Iterate through the DataFrame and get dimensions
heights = []
widths = []

for index, row in metadata.iterrows():
    media_path = row['path_datalake']
    media_type = row['type']
    
    # Download media from S3
    bucket_name = 'soulchain-dev1-output-video'
    key = media_path  # Adjust key if necessary

    try:
        response = s3.get_object(Bucket=bucket_name, Key=key)
        media_data = response['Body'].read()

        if media_type == 'video':
            with tempfile.NamedTemporaryFile(delete=False) as temp_file:
                temp_file.write(media_data)
                temp_file.flush()
                width, height = get_video_dimensions(temp_file.name)
        elif media_type == 'image':
            image_stream = BytesIO(media_data)
            image = Image.open(image_stream)
            width, height = image.size
        else:
            width, height = None, None

    except Exception as e:
        print(f"Error fetching media from S3: {e}")
        width, height = None, None

    widths.append(width)
    heights.append(height)

metadata['width'] = widths
metadata['height'] = heights

metadata

OpenCV: Couldn't read video stream from file "/var/folders/ys/s5c8y6vx2n95hnjtr5vs5h000000gn/T/tmpfahw9pam"
OpenCV: Couldn't read video stream from file "/var/folders/ys/s5c8y6vx2n95hnjtr5vs5h000000gn/T/tmp4ht2o_3d"
OpenCV: Couldn't read video stream from file "/var/folders/ys/s5c8y6vx2n95hnjtr5vs5h000000gn/T/tmp57p1hu_t"

,name,keywords,url,type,term,path_datalake,description,keywords_description,source,topic_name,main_topic,count_usage,count_edit,media_state,Unnamed: 0,width,height
2,1496-147827939_medium.mp4,"['cooking', 'wok', 'squid']",https://cdn.pixabay.com/video/2015/12/03/1496-...,video,food,datalake_media/video-1496-147827939_medium.mp4...,,[],pixabay,[],['food'],1,0,useful,NaN,1920,1080
4,32932-394144366_large.mp4,"['food', 'bananas', 'fruits']",https://cdn.pixabay.com/video/2020/02/27/32932...,video,banan,datalake_media/video-32932-394144366_large.mp4...,,[],pixabay,[],['banan'],0,0,useful,NaN,3840,2160
5,127737-739309170_large.mp4,"['apple', 'fruit', 'tree']",https://cdn.pixabay.com/video/2022/08/13/12773...,video,fruits,datalake_media/video-127737-739309170_large.mp...,,[],pixabay,[],['fruits '],0,0,useful,NaN,3840,2160
9,1019-142621240_large.mp4,"['fruit salad', 'bowl', 'fruits']",https://cdn.pixabay.com/video/2015/10/16/1019-...,video,fruits,datalake_media/video-1019-142621240_large.mp4-...,,[],pixabay,[],['fruits '],0,0,useful,NaN,1920,1080
10,148288-793718093_large.mp4,"['strawberry', 'fruit', 'nutrition']",https://cdn.pixabay.com/video/2023/01/28/14828...,video,fruit,datalake_media/video-148288-793718093_large.mp...,,[],pixabay,[],['fruit'],0,0,useful,NaN,1920,1080
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
587,strawberry-148288.mp4,"['strawberry', 'fruit', 'nutrition']",https://cdn.pixabay.com/vimeo/793718093/strawb...,video,food,datalake_media/video-strawberry-148288.mp4-52f...,a flower in a blue vase with a blue background,"['flower', 'vase', 'blue', 'background']",pixabay,['strawberry'],"['strawberri', 'food', 'fruit']",0,0,useful,244.0,1920,1080
588,goat-2278.mp4,"['goat', 'livestock', 'food']",https://cdn.pixabay.com/vimeo/157183507/goat-2...,video,food,datalake_media/video-goat-2278.mp4-95a8a6f6-48...,a herd of sheep standing in a field,"['sheep', 'herd', 'field', 'standing']",pixabay,['goat'],"['goat', 'food', 'livestock']",0,0,useful,245.0,1280,720
4849,sunflowers-59483.mp4,"['sunflowers', 'bees', 'field']",https://cdn.pixabay.com/vimeo/493557880/sunflo...,video,sunflower,datalake_media/video-sunflowers-59483.mp4-868f...,a blue sky with a bunch of blue water,"['blue', 'sky', 'water', 'bunch']",pixabay,['sunflowers'],"['sunflow', 'bee', 'field']",0,0,useful,5199.0,0,0
4850,squirrel-2717.mp4,"['squirrel', 'head', 'grey squirrel']",https://cdn.pixabay.com/vimeo/161687558/squirr...,video,sunflower,datalake_media/video-squirrel-2717.mp4-b61aec9...,a small bird is perched on a tree branch,"['bird', 'tree', 'perched', 'branch', 'small']",pixabay,['squirrel'],"['squirrel', 'sunflow', 'head']",0,0,useful,5200.0,0,0
4851,bird-9334.mp4,"['bird', 'sparrow', 'sunflower']",https://cdn.pixabay.com/vimeo/219173276/bird-9...,video,sunflower,datalake_media/video-bird-9334.mp4-02cbb64f-4f...,a blue bird with a flower in it,"['bird', 'flower', 'blue']",pixabay,['bird'],"['bird', 'sunflow', 'sparrow']",0,0,useful,5201.0,0,0

In [7]:
metadata_video=metadata

In [8]:
metadata_video

,name,keywords,url,type,term,path_datalake,description,keywords_description,source,topic_name,main_topic,count_usage,count_edit,media_state,Unnamed: 0,width,height
2,1496-147827939_medium.mp4,"['cooking', 'wok', 'squid']",https://cdn.pixabay.com/video/2015/12/03/1496-...,video,food,datalake_media/video-1496-147827939_medium.mp4...,,[],pixabay,[],['food'],1,0,useful,NaN,1920,1080
4,32932-394144366_large.mp4,"['food', 'bananas', 'fruits']",https://cdn.pixabay.com/video/2020/02/27/32932...,video,banan,datalake_media/video-32932-394144366_large.mp4...,,[],pixabay,[],['banan'],0,0,useful,NaN,3840,2160
5,127737-739309170_large.mp4,"['apple', 'fruit', 'tree']",https://cdn.pixabay.com/video/2022/08/13/12773...,video,fruits,datalake_media/video-127737-739309170_large.mp...,,[],pixabay,[],['fruits '],0,0,useful,NaN,3840,2160
9,1019-142621240_large.mp4,"['fruit salad', 'bowl', 'fruits']",https://cdn.pixabay.com/video/2015/10/16/1019-...,video,fruits,datalake_media/video-1019-142621240_large.mp4-...,,[],pixabay,[],['fruits '],0,0,useful,NaN,1920,1080
10,148288-793718093_large.mp4,"['strawberry', 'fruit', 'nutrition']",https://cdn.pixabay.com/video/2023/01/28/14828...,video,fruit,datalake_media/video-148288-793718093_large.mp...,,[],pixabay,[],['fruit'],0,0,useful,NaN,1920,1080
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
587,strawberry-148288.mp4,"['strawberry', 'fruit', 'nutrition']",https://cdn.pixabay.com/vimeo/793718093/strawb...,video,food,datalake_media/video-strawberry-148288.mp4-52f...,a flower in a blue vase with a blue background,"['flower', 'vase', 'blue', 'background']",pixabay,['strawberry'],"['strawberri', 'food', 'fruit']",0,0,useful,244.0,1920,1080
588,goat-2278.mp4,"['goat', 'livestock', 'food']",https://cdn.pixabay.com/vimeo/157183507/goat-2...,video,food,datalake_media/video-goat-2278.mp4-95a8a6f6-48...,a herd of sheep standing in a field,"['sheep', 'herd', 'field', 'standing']",pixabay,['goat'],"['goat', 'food', 'livestock']",0,0,useful,245.0,1280,720
4849,sunflowers-59483.mp4,"['sunflowers', 'bees', 'field']",https://cdn.pixabay.com/vimeo/493557880/sunflo...,video,sunflower,datalake_media/video-sunflowers-59483.mp4-868f...,a blue sky with a bunch of blue water,"['blue', 'sky', 'water', 'bunch']",pixabay,['sunflowers'],"['sunflow', 'bee', 'field']",0,0,useful,5199.0,0,0
4850,squirrel-2717.mp4,"['squirrel', 'head', 'grey squirrel']",https://cdn.pixabay.com/vimeo/161687558/squirr...,video,sunflower,datalake_media/video-squirrel-2717.mp4-b61aec9...,a small bird is perched on a tree branch,"['bird', 'tree', 'perched', 'branch', 'small']",pixabay,['squirrel'],"['squirrel', 'sunflow', 'head']",0,0,useful,5200.0,0,0
4851,bird-9334.mp4,"['bird', 'sparrow', 'sunflower']",https://cdn.pixabay.com/vimeo/219173276/bird-9...,video,sunflower,datalake_media/video-bird-9334.mp4-02cbb64f-4f...,a blue bird with a flower in it,"['bird', 'flower', 'blue']",pixabay,['bird'],"['bird', 'sunflow', 'sparrow']",0,0,useful,5201.0,0,0

In [9]:
metadata_video.to_excel("metadata_video.xlsx")

In [21]:
final_metadata=pd.concat([metadata_video,metadata_image])

In [22]:
final_metadata=final_metadata.drop(columns=["main_topic","Unnamed: 0"])

In [23]:
import numpy as np
final_metadata['size'] = np.where(final_metadata['width'] == final_metadata['height'], 'square', 
             np.where(final_metadata['width'] > final_metadata['height'], 'horizontal', 'vertical'))

In [24]:
final_metadata

,name,keywords,url,type,term,path_datalake,description,keywords_description,source,topic_name,count_usage,count_edit,media_state,width,height,size
2,1496-147827939_medium.mp4,"['cooking', 'wok', 'squid']",https://cdn.pixabay.com/video/2015/12/03/1496-...,video,food,datalake_media/video-1496-147827939_medium.mp4...,,[],pixabay,[],1,0,useful,1920.0,1080.0,horizontal
4,32932-394144366_large.mp4,"['food', 'bananas', 'fruits']",https://cdn.pixabay.com/video/2020/02/27/32932...,video,banan,datalake_media/video-32932-394144366_large.mp4...,,[],pixabay,[],0,0,useful,3840.0,2160.0,horizontal
5,127737-739309170_large.mp4,"['apple', 'fruit', 'tree']",https://cdn.pixabay.com/video/2022/08/13/12773...,video,fruits,datalake_media/video-127737-739309170_large.mp...,,[],pixabay,[],0,0,useful,3840.0,2160.0,horizontal
9,1019-142621240_large.mp4,"['fruit salad', 'bowl', 'fruits']",https://cdn.pixabay.com/video/2015/10/16/1019-...,video,fruits,datalake_media/video-1019-142621240_large.mp4-...,,[],pixabay,[],0,0,useful,1920.0,1080.0,horizontal
10,148288-793718093_large.mp4,"['strawberry', 'fruit', 'nutrition']",https://cdn.pixabay.com/video/2023/01/28/14828...,video,fruit,datalake_media/video-148288-793718093_large.mp...,,[],pixabay,[],0,0,useful,1920.0,1080.0,horizontal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4844,raspberry-2023410_150.jpg,"['raspberry', 'berry', 'summer']",https://cdn.pixabay.com/photo/2017/01/31/09/31...,image,food,datalake_media/image-raspberry-2023410_150.jpg...,a bowl of fruit and a bowl of berries on a table,"['berries', 'fruit', 'bowl', 'table']",pixabay,['raspberry'],0,0,useful,947.0,1280.0,vertical
4845,persimmon-1914127_150.jpg,"['persimmon', 'fruits', 'orange']",https://cdn.pixabay.com/photo/2016/12/17/18/51...,image,food,datalake_media/image-persimmon-1914127_150.jpg...,a bowl of oranges sitting on top of a wooden t...,"['oranges', 'bowl', 'table', 'wooden', 'sitting']",pixabay,['persimmon'],0,0,useful,1065.0,1280.0,vertical
4846,sunflower-1127174_150.jpg,"['sunflower', 'flower', 'plant']",https://cdn.pixabay.com/photo/2016/01/08/05/24...,image,sunflower,datalake_media/image-sunflower-1127174_150.jpg...,a yellow flower in the middle of a sunny day,"['flower', 'yellow', 'sunny', 'day', 'middle']",pixabay,['sunflower'],0,0,useful,1280.0,853.0,horizontal
4847,sunflower-3113318_150.jpg,"['sunflower', 'nature', 'flower background']",https://cdn.pixabay.com/photo/2018/01/28/11/24...,image,sunflower,datalake_media/image-sunflower-3113318_150.jpg...,a close up picture of a flower in the sun,"['flower', 'sun', 'picture', 'close']",pixabay,['sunflower'],0,0,useful,1280.0,853.0,horizontal
4848,sunflower-1627193_150.jpg,"['sunflower', 'yellow', 'flower']",https://cdn.pixabay.com/photo/2016/08/28/23/24...,image,sunflower,datalake_media/image-sunflower-1627193_150.jpg...,a close up view of a bunch of yellow flowers,"['flowers', 'yellow', 'view', 'bunch', 'close']",pixabay,['sunflower'],0,0,useful,1280.0,853.0,horizontal

In [25]:
final_metadata=final_metadata.drop(columns=["width","height"])

In [27]:
final_metadata.to_excel("metadata_new.xlsx")

In [1]:
import cv2
import numpy as np

audio_file = "audio1.mp3"

image_file = "image.jpg"
image = cv2.imread(image_file)

# Get image dimensions
height, width, _ = image.shape

# Load audio using OpenCV
audio = cv2.VideoCapture(audio_file)

# Create VideoWriter object
fourcc = cv2.VideoWriter_fourcc(*'mp4v') # codec for video
fps = 30  # frames per second
video_writer = cv2.VideoWriter("output_video.mp4", fourcc, fps, (width, height))

# Initialize variables
frame_count = 0

# Read audio frames and write to video
while True:
    ret, frame = audio.read()
    if not ret:
        break

    # Resize audio frame to match image dimensions
    frame = cv2.resize(frame, (width, height))

    # Write audio frame to video
    video_writer.write(frame)

    # Increment frame count
    frame_count += 1

    # Uncomment the following line to see the progress
    # print("Frames processed: ", frame_count)

    # Break if audio ends
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

# Release VideoWriter and VideoCapture objects
video_writer.release()
audio.release()

# Close all OpenCV windows
cv2.destroyAllWindows()

OpenCV: Couldn't read video stream from file "audio1.mp3"

In [1]:
import requests
url_tts = "http://127.0.0.1:5013/tts/tts"
data = {
    "text": "This diverse mix of foods provides vitaminsthat support various bodily functions.",
}
response = requests.post(url_tts, json=data)

In [2]:
response