In [127]:
import pandas as pd

In [135]:
df= pd.read_excel("metadata_mixkit_unsplash_pixabay.xlsx")

In [136]:
df["type"].value_counts()

type
image    17068
video     2273
Name: count, dtype: int64

In [137]:
from text_to_media import find_media_best
df_image=df[df["type"]=="image"]

In [138]:
find_media_best(["nutrition"],[],df_image)

(True,
 True,
 'datalake_media/image-smoothie-3697014_150.jpg-c372f837-dd5c-4354-9aaa-5bd4f5f2f30d')

In [9]:
import nltk
from nltk import pos_tag
from nltk.tokenize import word_tokenize

# Download nltk data for pos_tag


# Define your keywords and words list
lexical_field_keywords = ["grass"]
words = ['grass', 'shore', 'ocean', 'coast', 'beach', 'sea', 'possibilities', 'peace', 'sunshine', 'sun', 'cliff', 'journey', 'bluff', 'limitless', 'land', 'outdoors', 'nature', 'clouds', 'cliffs', 'sky', 'shoreline', 'landform', 'scenery', 'aerial view', 'adventure', 'cape', 'island', 'rocky', 'coastline', 'water', 'geographical feature', 'green', 'sea waves', 'landscape', 'blue']

# Tokenize and tag words
tagged_words = pos_tag(word_tokenize(' '.join(words)))

# Filter out words that are not nouns
filtered_words = [word.lower() for word, tag in tagged_words if tag.startswith('N')]

# Filter out words that are not in the lexical field
filtered_words = [word for word in filtered_words if any(keyword in word for keyword in lexical_field_keywords)]

print(filtered_words)

['grass']

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /Users/fatimaezzahrasounnyslitine/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!

In [10]:
filtered_words

['grass']

In [139]:
import pandas as pd
from nltk import word_tokenize, pos_tag
from nltk.corpus import wordnet
from nltk.stem import WordNetLemmatizer

# Function to lemmatize words
def lemmatize_words(text):
    if pd.isnull(text):
        return ''
    lemmatizer = WordNetLemmatizer()
    lemmatized_words = []
    for word, pos in pos_tag(word_tokenize(text)):
        wordnet_pos = pos[0].lower()
        wordnet_pos = 'n' if wordnet_pos == 'j' else wordnet_pos
        wordnet_pos = 'v' if wordnet_pos == 'r' else wordnet_pos
        if wordnet_pos not in ['a', 'r', 'n', 'v']:
            wordnet_pos = 'n'
        lemma = lemmatizer.lemmatize(word, pos=wordnet_pos)
        lemmatized_words.append(lemma)
    return ' '.join(lemmatized_words)

# Apply lemmatization to each column
df['keywords_description'] = df['keywords_description'].apply(lambda x: lemmatize_words(x.lower()))
df['keywords'] = df['keywords'].apply(lambda x: lemmatize_words(x.lower()))
df['term'] = df['term'].apply(lambda x: lemmatize_words(str(x).lower()))

In [140]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19341 entries, 0 to 19340
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Unnamed: 0            19341 non-null  int64
 1   name                  19341 non-null  object
 2   keywords              19341 non-null  object
 3   url                   19341 non-null  object
 4   type                  19341 non-null  object
 5   term                  19341 non-null  object
 6   path_datalake         19341 non-null  object
 7   description           18265 non-null  object
 8   keywords_description  19341 non-null  object
 9   source                19341 non-null  object
 10  size                  19341 non-null  object
 11  count_usage           19341 non-null  int64
 12  count_edit            19341 non-null  int64
 13  media_state           19341 non-null  object
dtypes: int64(3), object(11)
memory usage: 2.1+ MB

In [122]:
df[["keywords"]].tail()

                                                keywords
19336  [ ' '' close up '' ' , ' '' fruit '' ' , ' '' ...
19337  [ ' '' portrait '' ' , ' '' fruit '' ' , ' '' ...
19338  [ ' '' fruit '' ' , ' '' fruit '' ' , ' '' gar...
19339  [ ' '' fruit '' ' , ' '' market '' ' , ' '' fr...
19340  [ ' '' fruit '' ' , ' '' elderly '' ' , ' '' o...

In [23]:
df[["keywords"]]

                                                keywords
0      [ 'grass ' , 'shore ' , 'ocean ' , 'coast ' , ...
1      [ 'blue ' , 'holiday ' , 'geographical feature...
2      [ 'sea ' , 'jump ' , 'waves ' , 'summer ' , 'h...
3      [ 'ocean ' , 'waves ' , 'mist ' , 'water ' , '...
4      [ 'dawn ' , 'scenery ' , 'glow ' , 'dune ' , '...
...                                                  ...
19336  [ ' '' close up '' ' , ' '' fruit '' ' , ' '' ...
19337  [ ' '' portrait '' ' , ' '' fruit '' ' , ' '' ...
19338  [ ' '' fruit '' ' , ' '' fruit '' ' , ' '' gar...
19339  [ ' '' fruit '' ' , ' '' market '' ' , ' '' fr...
19340  [ ' '' fruit '' ' , ' '' elderly '' ' , ' '' o...

[19341 rows x 1 columns]

In [100]:
import ast
import re

test=df[df["source"]=="mixkit"]

In [123]:
import re

def clean_keywords(keyword):
    # Use regular expression to remove non-alphabet characters
    cleaned_keyword = re.sub(r'[^a-zA-Z\s]', '', keyword)
    return cleaned_keyword

# Apply cleaning to keywords
df.loc[df["source"] == "mixkit", "keywords"] = df.loc[df["source"] == "mixkit", "keywords"].apply(clean_keywords)

In [124]:
df.loc[df["source"] == "mixkit", "keywords"] = df.loc[df["source"] == "mixkit", "keywords"].apply(lambda x: x.split())

In [125]:
df.loc[df["source"] == "mixkit", "keywords"] = df.loc[df["source"] == "mixkit", "keywords"].apply(lambda x: [f"'{word.strip().lower()}'" for word in x])

In [126]:
df

,Unnamed: 0,name,keywords,url,type,term,path_datalake,description,keywords_description,source,size,count_usage,count_edit,media_state
0,0,bygTaBey1Xk.jpg,"[ 'grass ' , 'shore ' , 'ocean ' , 'coast ' , ...",https://images.unsplash.com/uploads/1413387620...,image,grass,datalake_media/image-bygTaBey1Xk.jpg-c8c7df3c-...,sea and rock cliff with grasses under cloudy sky,"[ 'cliff ' , 'grasses ' , 'cloudy ' , 'sky ' ,...",unsplash,horizontal,0,0,useful
1,1,gXSFnk2a9V4.jpg,"[ 'blue ' , 'holiday ' , 'geographical feature...",https://images.unsplash.com/reserve/jEs6K0y1Sb...,image,blue,datalake_media/image-gXSFnk2a9V4.jpg-a0496092-...,aerial photography of seashore,"[ 'seashore ' , 'aerial ' , 'photography ' ]",unsplash,vertical,0,0,useful
2,2,grg6-DNJuaU.jpg,"[ 'sea ' , 'jump ' , 'waves ' , 'summer ' , 'h...",https://images.unsplash.com/uploads/1412192004...,image,sea,datalake_media/image-grg6-DNJuaU.jpg-c2b853ee-...,man surfboarding on ocean wave during daytime,"[ 'surfboarding ' , 'ocean ' , 'wave ' , 'dayt...",unsplash,horizontal,0,0,useful
3,3,sO42hhChB1c.jpg,"[ 'ocean ' , 'waves ' , 'mist ' , 'water ' , '...",https://images.unsplash.com/reserve/ijl3tATFRp...,image,ocean,datalake_media/image-sO42hhChB1c.jpg-586ba674-...,body of water,"[ 'water ' , 'body ' ]",unsplash,horizontal,0,0,useful
4,4,tkk8_HakQ98.jpg,"[ 'dawn ' , 'scenery ' , 'glow ' , 'dune ' , '...",https://images.unsplash.com/reserve/6vaWXsQuSW...,image,dawn,datalake_media/image-tkk8_HakQ98.jpg-9f60f63f-...,car on desert during sunset,"[ 'sunset ' , 'desert ' , 'car ' ]",unsplash,horizontal,0,0,useful
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19336,495,Person eating salad with fork,"['close', 'up', 'fruit', 'dish', 'salad', 'cut...",https://assets.mixkit.co/videos/preview/mixkit...,video,fruit,datalake_media/video-fruit-889d663a-bdeb-4d0b-...,Fork taking a bite of salad with pear and waln...,"[ 'salad ' , 'fork ' , 'walnuts ' , 'pear ' , ...",mixkit,horizontal,0,0,useful
19337,496,Housewife choosing fruit at the market,"['portrait', 'fruit', 'market', 'farmer', 'mar...",https://assets.mixkit.co/videos/preview/mixkit...,video,fruit,datalake_media/video-fruit-ea12d715-6d45-4ede-...,NaN,[ ],mixkit,horizontal,0,0,useful
19338,497,Raspberries in the hands of a person,"['fruit', 'fruit', 'gardening']",https://assets.mixkit.co/videos/preview/mixkit...,video,fruit,datalake_media/video-fruit-362ef810-41f5-4c43-...,NaN,[ ],mixkit,horizontal,0,0,useful
19339,498,Various fruits on shelves in the market,"['fruit', 'market', 'fruit', 'farmer', 'market']",https://assets.mixkit.co/videos/preview/mixkit...,video,fruit,datalake_media/video-fruit-df9f2cbc-6b26-4568-...,NaN,[ ],mixkit,horizontal,0,0,useful
19340,499,Old woman with a basket of apples,"['fruit', 'elderly', 'old', 'woman', 'elder', ...",https://assets.mixkit.co/videos/preview/mixkit...,video,fruit,datalake_media/video-fruit-052fd18b-4408-4554-...,NaN,[ ],mixkit,horizontal,0,0,useful

In [114]:
def remove_duplicates(string):
    words = string.split(', ')
    unique_words = list(set(words))
    return ', '.join(unique_words)

In [117]:
def remove_duplicates(keyword_list):
    unique_keywords = list(set(keyword_list))  # Convert the list to a set to remove duplicates, then back to a list
    return unique_keywords

# Apply the function to the 'keywords' column
df["keywords"] = df["keywords"].apply(remove_duplicates)

In [118]:
df

,Unnamed: 0,name,keywords,url,type,term,path_datalake,description,keywords_description,source,size,count_usage,count_edit,media_state
0,0,bygTaBey1Xk.jpg,"[e, o, p, w, , j, h, r, m, ], a, d, i, [, g, ...",https://images.unsplash.com/uploads/1413387620...,image,grass,datalake_media/image-bygTaBey1Xk.jpg-c8c7df3c-...,sea and rock cliff with grasses under cloudy sky,"[ 'cliff ' , 'grasses ' , 'cloudy ' , 'sky ' ,...",unsplash,horizontal,0,0,useful
1,1,gXSFnk2a9V4.jpg,"[e, o, p, w, , h, r, m, ], a, d, i, [, g, y, ...",https://images.unsplash.com/reserve/jEs6K0y1Sb...,image,blue,datalake_media/image-gXSFnk2a9V4.jpg-a0496092-...,aerial photography of seashore,"[ 'seashore ' , 'aerial ' , 'photography ' ]",unsplash,vertical,0,0,useful
2,2,grg6-DNJuaU.jpg,"[e, o, p, w, , j, h, r, m, ], a, d, i, [, g, ...",https://images.unsplash.com/uploads/1412192004...,image,sea,datalake_media/image-grg6-DNJuaU.jpg-c2b853ee-...,man surfboarding on ocean wave during daytime,"[ 'surfboarding ' , 'ocean ' , 'wave ' , 'dayt...",unsplash,horizontal,0,0,useful
3,3,sO42hhChB1c.jpg,"[e, o, p, w, , h, r, m, ], a, d, i, [, g, y, ...",https://images.unsplash.com/reserve/ijl3tATFRp...,image,ocean,datalake_media/image-sO42hhChB1c.jpg-586ba674-...,body of water,"[ 'water ' , 'body ' ]",unsplash,horizontal,0,0,useful
4,4,tkk8_HakQ98.jpg,"[e, o, p, w, , j, x, h, r, m, ], a, d, i, [, ...",https://images.unsplash.com/reserve/6vaWXsQuSW...,image,dawn,datalake_media/image-tkk8_HakQ98.jpg-9f60f63f-...,car on desert during sunset,"[ 'sunset ' , 'desert ' , 'car ' ]",unsplash,horizontal,0,0,useful
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19336,495,Person eating salad with fork,"['fruit', 'up', 'close', 'dish', 'salad', 'cut...",https://assets.mixkit.co/videos/preview/mixkit...,video,fruit,datalake_media/video-fruit-889d663a-bdeb-4d0b-...,Fork taking a bite of salad with pear and waln...,"[ 'salad ' , 'fork ' , 'walnuts ' , 'pear ' , ...",mixkit,horizontal,0,0,useful
19337,496,Housewife choosing fruit at the market,"['fruit', 'market', 'farmer', 'portrait']",https://assets.mixkit.co/videos/preview/mixkit...,video,fruit,datalake_media/video-fruit-ea12d715-6d45-4ede-...,NaN,[ ],mixkit,horizontal,0,0,useful
19338,497,Raspberries in the hands of a person,"['gardening', 'fruit']",https://assets.mixkit.co/videos/preview/mixkit...,video,fruit,datalake_media/video-fruit-362ef810-41f5-4c43-...,NaN,[ ],mixkit,horizontal,0,0,useful
19339,498,Various fruits on shelves in the market,"['market', 'farmer', 'fruit']",https://assets.mixkit.co/videos/preview/mixkit...,video,fruit,datalake_media/video-fruit-df9f2cbc-6b26-4568-...,NaN,[ ],mixkit,horizontal,0,0,useful
19340,499,Old woman with a basket of apples,"['apple', 'elder', 'fruit', 'woman', 'old', 'e...",https://assets.mixkit.co/videos/preview/mixkit...,video,fruit,datalake_media/video-fruit-052fd18b-4408-4554-...,NaN,[ ],mixkit,horizontal,0,0,useful

In [1]:
import pandas as pd 

metadata= pd.read_excel("metadata_mixkit_unsplash_pixabay.xlsx")

In [19]:
metadata

,Unnamed: 0,name,keywords,url,type,term,path_datalake,description,keywords_description,source,size,count_usage,count_edit,media_state
0,0,bygTaBey1Xk.jpg,"['grass', 'shore', 'ocean', 'coast', 'beach', ...",https://images.unsplash.com/uploads/1413387620...,image,grass,datalake_media/image-bygTaBey1Xk.jpg-c8c7df3c-...,sea and rock cliff with grasses under cloudy sky,"['cliff', 'grasses', 'cloudy', 'sky', 'rock']",unsplash,horizontal,0,0,useful
1,1,gXSFnk2a9V4.jpg,"['blue', 'holiday', 'geographical feature', 'a...",https://images.unsplash.com/reserve/jEs6K0y1Sb...,image,blue,datalake_media/image-gXSFnk2a9V4.jpg-a0496092-...,aerial photography of seashore,"['seashore', 'aerial', 'photography']",unsplash,vertical,0,0,useful
2,2,grg6-DNJuaU.jpg,"['sea', 'jump', 'waves', 'summer', 'holiday', ...",https://images.unsplash.com/uploads/1412192004...,image,sea,datalake_media/image-grg6-DNJuaU.jpg-c2b853ee-...,man surfboarding on ocean wave during daytime,"['surfboarding', 'ocean', 'wave', 'daytime', '...",unsplash,horizontal,0,0,useful
3,3,sO42hhChB1c.jpg,"['ocean', 'waves', 'mist', 'water', 'foam', 'd...",https://images.unsplash.com/reserve/ijl3tATFRp...,image,ocean,datalake_media/image-sO42hhChB1c.jpg-586ba674-...,body of water,"['water', 'body']",unsplash,horizontal,0,0,useful
4,4,tkk8_HakQ98.jpg,"['dawn', 'scenery', 'glow', 'dune', 'sunlight'...",https://images.unsplash.com/reserve/6vaWXsQuSW...,image,dawn,datalake_media/image-tkk8_HakQ98.jpg-9f60f63f-...,car on desert during sunset,"['sunset', 'desert', 'car']",unsplash,horizontal,0,0,useful
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19336,495,Person eating salad with fork,"['""close up""', '""fruit""', '""dish""', '""salad""',...",https://assets.mixkit.co/videos/preview/mixkit...,video,fruit,datalake_media/video-fruit-889d663a-bdeb-4d0b-...,Fork taking a bite of salad with pear and waln...,"['salad', 'fork', 'walnuts', 'pear', 'bite']",mixkit,horizontal,0,0,useful
19337,496,Housewife choosing fruit at the market,"['""portrait""', '""fruit""', '""market""', '""farmer...",https://assets.mixkit.co/videos/preview/mixkit...,video,fruit,datalake_media/video-fruit-ea12d715-6d45-4ede-...,NaN,[],mixkit,horizontal,0,0,useful
19338,497,Raspberries in the hands of a person,"['""fruit""', '""fruits""', '""gardening""']",https://assets.mixkit.co/videos/preview/mixkit...,video,fruit,datalake_media/video-fruit-362ef810-41f5-4c43-...,NaN,[],mixkit,horizontal,0,0,useful
19339,498,Various fruits on shelves in the market,"['""fruit""', '""market""', '""fruits""', '""farmers ...",https://assets.mixkit.co/videos/preview/mixkit...,video,fruit,datalake_media/video-fruit-df9f2cbc-6b26-4568-...,NaN,[],mixkit,horizontal,0,0,useful
19340,499,Old woman with a basket of apples,"['""fruit""', '""elderly""', '""old woman""', '""elde...",https://assets.mixkit.co/videos/preview/mixkit...,video,fruit,datalake_media/video-fruit-052fd18b-4408-4554-...,NaN,[],mixkit,horizontal,0,0,useful

In [13]:
test=metadata.iloc[2:3]

In [14]:
test

,Unnamed: 0,name,keywords,url,type,term,path_datalake,description,keywords_description,source,size,count_usage,count_edit,media_state
2,2,grg6-DNJuaU.jpg,"['sea', 'jump', 'waves', 'summer', 'holiday', ...",https://images.unsplash.com/uploads/1412192004...,image,sea,datalake_media/image-grg6-DNJuaU.jpg-c2b853ee-...,man surfboarding on ocean wave during daytime,"['surfboarding', 'ocean', 'wave', 'daytime', '...",unsplash,horizontal,0,0,useful

In [18]:
for index, row in test.iterrows():
    if "sea" in row["term"]:
        print(index)
        print('found')

2
found

In [ ]:
metadata["tendency_score"]=0

In [ ]:
metadata["main_topics"]

In [29]:
metadata_mixkit= metadata[metadata["source"]=="mixkit"]
list_keywords=[]

for index, row in metadata_mixkit.iterrows():
    quoted_keywords = ast.literal_eval(row["keywords"])
    metadata_mixkit.at[index, "keywords"] = [keyword.strip('"') for keyword in quoted_keywords]

In [30]:
metadata_mixkit

,Unnamed: 0,name,keywords,url,type,term,path_datalake,description,keywords_description,source,size,count_usage,count_edit,media_state
17351,0,Serving juice in a glass with some oranges on ...,"[close up, food, texture, drink, static shot, ...",https://assets.mixkit.co/videos/preview/mixkit...,video,food,datalake_media/video-food-1c3cb705-a78f-4371-8...,"Oranges, a glass and some ices in an image com...","['oranges', 'orange', 'glass', 'ices', 'juice']",mixkit,vertical,0,0,useful
17352,1,Woman flipping her egg omelet,"[close up, food, food preparation, cooking, ho...",https://assets.mixkit.co/videos/preview/mixkit...,video,food,datalake_media/video-food-d66ee76b-b4aa-4ba4-b...,Close up shot of a woman flipping her egg omel...,"['egg', 'omelet', 'breakfast', 'woman', 'flipp...",mixkit,horizontal,0,0,useful
17353,2,Video sequence of the coffee preparation process,"[food, food preparation, drink, coffee, cup, c...",https://assets.mixkit.co/videos/preview/mixkit...,video,food,datalake_media/video-food-7b82b478-a994-4192-b...,Sequence of some videos during the preparation...,"['coffee', 'beans', 'videos', 'cup', 'preparat...",mixkit,horizontal,0,0,useful
17354,3,Eating salad with a fork,"[close up, food, healthy lifestyle, healthy fo...",https://assets.mixkit.co/videos/preview/mixkit...,video,food,datalake_media/video-food-de07487e-b3d3-4975-8...,A person's hand eating healthy vegetable salad...,"['salad', 'eating', 'vegetable', 'fork', 'heal...",mixkit,horizontal,0,0,useful
17355,4,Rotating bowl with fruit on a white background,"[close up, food, texture, fruit, salad, strawb...",https://assets.mixkit.co/videos/preview/mixkit...,video,food,datalake_media/video-food-f837ec30-6aeb-4a66-b...,"Rotating glass bowl with fruit like kiwi, bana...","['bowl', 'fruit', 'honey', 'kiwi', 'strawberri...",mixkit,horizontal,0,0,useful
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19336,495,Person eating salad with fork,"[close up, fruit, dish, salad, cutlery]",https://assets.mixkit.co/videos/preview/mixkit...,video,fruit,datalake_media/video-fruit-889d663a-bdeb-4d0b-...,Fork taking a bite of salad with pear and waln...,"['salad', 'fork', 'walnuts', 'pear', 'bite']",mixkit,horizontal,0,0,useful
19337,496,Housewife choosing fruit at the market,"[portrait, fruit, market, farmers market]",https://assets.mixkit.co/videos/preview/mixkit...,video,fruit,datalake_media/video-fruit-ea12d715-6d45-4ede-...,NaN,[],mixkit,horizontal,0,0,useful
19338,497,Raspberries in the hands of a person,"[fruit, fruits, gardening]",https://assets.mixkit.co/videos/preview/mixkit...,video,fruit,datalake_media/video-fruit-362ef810-41f5-4c43-...,NaN,[],mixkit,horizontal,0,0,useful
19339,498,Various fruits on shelves in the market,"[fruit, market, fruits, farmers market]",https://assets.mixkit.co/videos/preview/mixkit...,video,fruit,datalake_media/video-fruit-df9f2cbc-6b26-4568-...,NaN,[],mixkit,horizontal,0,0,useful
19340,499,Old woman with a basket of apples,"[fruit, elderly, old woman, elder, fruits, apple]",https://assets.mixkit.co/videos/preview/mixkit...,video,fruit,datalake_media/video-fruit-052fd18b-4408-4554-...,NaN,[],mixkit,horizontal,0,0,useful

In [39]:
test

,Unnamed: 0,name,keywords,url,type,term,path_datalake,description,keywords_description,source,size,count_usage,count_edit,media_state
1,1,gXSFnk2a9V4.jpg,"['blue', 'holiday', 'geographical feature', 'a...",https://images.unsplash.com/reserve/jEs6K0y1Sb...,image,blue,datalake_media/image-gXSFnk2a9V4.jpg-a0496092-...,aerial photography of seashore,"['seashore', 'aerial', 'photography']",unsplash,vertical,0,0,useful
2,2,grg6-DNJuaU.jpg,"['sea', 'jump', 'waves', 'summer', 'holiday', ...",https://images.unsplash.com/uploads/1412192004...,image,sea,datalake_media/image-grg6-DNJuaU.jpg-c2b853ee-...,man surfboarding on ocean wave during daytime,"['surfboarding', 'ocean', 'wave', 'daytime', '...",unsplash,horizontal,0,0,useful
3,3,sO42hhChB1c.jpg,"['ocean', 'waves', 'mist', 'water', 'foam', 'd...",https://images.unsplash.com/reserve/ijl3tATFRp...,image,ocean,datalake_media/image-sO42hhChB1c.jpg-586ba674-...,body of water,"['water', 'body']",unsplash,horizontal,0,0,useful
4,4,tkk8_HakQ98.jpg,"['dawn', 'scenery', 'glow', 'dune', 'sunlight'...",https://images.unsplash.com/reserve/6vaWXsQuSW...,image,dawn,datalake_media/image-tkk8_HakQ98.jpg-9f60f63f-...,car on desert during sunset,"['sunset', 'desert', 'car']",unsplash,horizontal,0,0,useful

In [40]:
test=metadata.iloc[1:5]
for index, row in test.iterrows():
    if "holiday" in row["keywords"]:
        print(index)
        print('found')

1
found
2
found

In [ ]:

def read_metadata_from_s3(bucket_name, file_key):
    s3 = boto3.client('s3', aws_access_key_id="AKIAUJXLE2HEM4YQVOSA",aws_secret_access_key="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",region_name='eu-west-1')
    obj = s3.get_object(Bucket=bucket_name, Key=file_key)
    return pd.read_excel(BytesIO(obj['Body'].read()))

metadata=read_metadata_from_s3("soulchain-dev1-output-video", "metadata_mixkit_unsplash_pixabay.xlsx")

In [1]:
import pandas as pd
df1=pd.read_excel("metadata_video_1772_rest.xlsx")
df2=pd.read_excel("metadata_video_1772.xlsx")

In [5]:
df1=df1.drop(columns=["Unnamed: 0.1","Unnamed: 0"])

In [ ]:



import spacy

# Load the pre-trained spaCy model
nlp = spacy.load("en_core_web_sm")

# Define a set of stopwords
stopwords = ["video","body","black"]

# Function to extract nouns excluding stopwords
def extract_nouns(text):
    doc = nlp(text)
    keywords = [token.text for token in doc if token.pos_ == "NOUN" and token.text.lower() not in stopwords]
    return keywords
        
df['new_keywords'] = df['new_description'].apply(extract_nouns)



df['keywords'] = df['keywords'].apply(literal_eval)
df['keywords_description'] = df['keywords_description'].apply(literal_eval)

import nltk
from nltk.stem import WordNetLemmatizer

# Download WordNet if not already downloaded
nltk.download('wordnet')

# Initialize the WordNet lemmatizer
lemmatizer = WordNetLemmatizer()

# Function to lemmatize a list of words
def lemmatize_words(words):
    return [lemmatizer.lemmatize(word) for word in words]

# Assuming df['new_keywords'] contains lists of words, apply lemmatization
df['new_keywords'] = df['new_keywords'].apply(lemmatize_words)



import pandas as pd
from collections import Counter
from ast import literal_eval
import nltk
from nltk.stem import WordNetLemmatizer

def lemmatize_words(words):
    return [lemmatizer.lemmatize(word) for word in words]

# Function to find most frequent words and update missing ones
def process_keywords(row):
    if row["source"]=="pixabay":
        all_keywords = row['keywords'] + row['new_keywords']
    if row["source"]=="unsplash":
        all_keywords = row['keywords_description'] + row['new_keywords']
    else :
        all_keywords = row['keywords'] + row['keywords_description'] + row['new_keywords']

    normalized_keywords = lemmatize_words(all_keywords)
    word_counts = Counter(normalized_keywords)
    most_common_words = word_counts.most_common(5)  # Adjust as needed
    most_common_words_only = [word for word, _ in most_common_words]
    
    # Check and update missing words
    new_keywords_set = set(row['new_keywords'])
    current_most_common_set = set(most_common_words_only)
    missing_words = new_keywords_set - current_most_common_set
    
    if missing_words:
        most_common_words_only.extend(missing_words)
    
    return most_common_words_only

# Apply the function to each row
df['most_frequent_words'] = df.apply(process_keywords, axis=1)