In [4]:
import pandas as pd

meta_row=pd.read_excel("metadata copy.xlsx")

# Assuming url_datalake_path is your string
url_datalake_path = "datalake_media/image-fresh-fruits-2305192_150.jpg-d284f5aa-7d1e-4394-99c9-c71836360a5a"

# Find the index of ".jpg" in the string
jpg_index = url_datalake_path.find(".jpg")

if jpg_index != -1:
    url_datalake_path_new = url_datalake_path[:jpg_index + len(".jpg")]

datalake_media/image-fresh-fruits-2305192_150.jpg

In [5]:
i=set()
image_paths = ["hh","jjd"]
i.add(image_paths)

TypeError: unhashable type: 'list'

In [13]:
import json

# Load data from JSON file
with open('video_info-7.json', 'r') as file:
    existing_data = json.load(file)

existing_data = [entry for entry in existing_data if entry['user_id'] == "user1"]

# Extract image paths from video_parts
image_paths = []
for entry in existing_data:
    image_paths.extend([part['image_key'] for part in entry['video_parts']])

image_paths = [path[:path.find(".jpg") + len(".jpg")] if ".jpg" in path else path for path in image_paths]

print(image_paths)

['datalake_media/image-maldives-1993704_150.jpg', 'datalake_media/image-woman-3640935_150.jpg', 'datalake_media/image-winding-road-1556177_150.jpg', 'datalake_media/image-loveourplanet-4851331_150.jpg', 'datalake_media/image-berries-3504149_150.jpg', 'datalake_media/image-mental-health-4232031_150.jpg', 'datalake_media/image-salad-2068217_150.jpg', 'datalake_media/image-egg-slicer-647531_150.jpg', 'datalake_media/image-egg-24404_150.png-1f2a2357-2616-4015-847d-28ffdb2dbc37', 'datalake_media/image-berries-3504149_150.jpg', 'datalake_media/image-diet-695723_150.jpg', 'datalake_media/image-obesity-993126_150.jpg', 'datalake_media/image-vegetables-1085063_150.jpg', 'datalake_media/image-egg-24404_150.png-1f2a2357-2616-4015-847d-28ffdb2dbc37', 'datalake_media/image-healthy-7213383_150.jpg', 'datalake_media/image-diet-695723_150.jpg', 'datalake_media/image-fat-3313923_150.png-5cc9dc32-49a5-4bb5-a0a6-748a236dcee3', 'datalake_media/image-food-366875_150.jpg', 'datalake_media/image-fresh-fruits-2305192_150.jpg', 'datalake_media/image-berries-3504149_150.jpg', 'datalake_media/image-salad-2756467_150.jpg', 'datalake_media/image-pattern-1477380_150.png-b1ea4604-6d08-4f41-9be3-62c829e42030', 'datalake_media/image-berries-2277_150.jpg', 'datalake_media/image-fresh-fruits-2305192_150.jpg', 'datalake_media/image-healthy-7213383_150.jpg', 'datalake_media/image-diet-695723_150.jpg', 'datalake_media/image-fat-3313923_150.png-5cc9dc32-49a5-4bb5-a0a6-748a236dcee3', 'datalake_media/image-food-366875_150.jpg', 'datalake_media/image-fresh-fruits-2305192_150.jpg', 'datalake_media/image-food-1898194_150.jpg', 'datalake_media/image-diet-1949478_150.jpg', 'datalake_media/image-fat-3313923_150.png-288c7068-8ef6-4365-a86a-3e13bdea9405', 'datalake_media/image-vegetables-1085063_150.jpg', 'datalake_media/image-food-1898194_150.jpg', 'datalake_media/image-herbs-906140_150.jpg', 'datalake_media/image-fruit-3111745_150.jpg', 'datalake_media/image-fat-dog-4392363_150.jpg', 'datalake_media/image-berries-2277_150.jpg', 'datalake_media/image-herbs-906140_150.jpg', 'datalake_media/image-vegetables-3679075_150.jpg', 'datalake_media/image-fruit-3111745_150.jpg', 'datalake_media/image-butter-3411126_150.jpg', 'datalake_media/image-berries-2277_150.jpg', 'datalake_media/image-vegetables-2008578_150.png-48d6142b-49f3-42c3-a5b6-bea2ac71aee0']

In [29]:
import json

with open('video_info-8.json', 'r') as file:
    existing_data = json.load(file)

existing_data = [entry for entry in existing_data if entry['user_id'] == "user1"]

# Extract image paths from video_parts
image_paths = []
for entry in existing_data:
    image_paths.extend([part['image_key'] for part in entry['video_parts']])

# Remove prefix and extension from image paths
image_paths =[path.split('.jpg')[0].replace("datalake_media/image-", "") + '.jpg' if '.jpg' in path else path.replace("datalake_media/image-", "") for path in image_paths]


len(image_paths)

42

In [30]:
image_paths

['vegetables-1085063_150.jpg',
 'diet-695723_150.jpg',
 'father-22194_150.jpg',
 'snack-3579973_150.png-539e4e72-b9a8-422c-bae5-efd2afb6b4ac',
 'dna-4068826_150.jpg',
 'olive-oil-968657_150.jpg',
 'scale-403585_150.jpg',
 'depression-2826711_150.jpg',
 'food-366875_150.jpg',
 'still-life-2366084_150.jpg',
 'still-life-562357_150.jpg',
 'herbs-906140_150.jpg',
 'butter-3411126_150.jpg',
 'harmful-food-1803600_150.jpg',
 'herbs-906140_150.jpg',
 'berries-2277_150.jpg',
 'salad-2756467_150.jpg',
 'belly-2354_150.jpg',
 'berries-2277_150.jpg',
 'berries-2277_150.jpg',
 'berries-2277_150.jpg',
 'meal-1307604_150.jpg',
 'obesity-993126_150.jpg',
 'spaghetti-1932466_150.jpg',
 'onion-7434358_150.jpg',
 'berries-2277_150.jpg',
 'woman-3186730_150.jpg',
 'fat-3313923_150.png-7d1613e1-1983-4f7c-ae34-c8348524a2b1',
 'vegetables-752153_150.jpg',
 'berries-3504149_150.jpg',
 'tree-736885_150.jpg',
 'spring-2174750_150.jpg',
 'mountain-806915_150.jpg',
 'alpaca-5405469_150.jpg',
 'road-1072823_150.jpg',
 'blooming-4112348_150.jpg',
 'sky-4576072_150.jpg',
 'istanbul-1641539_150.jpg',
 'tree-736885_150.jpg',
 'baby-1151351_150.jpg',
 'signs-1172211_150.jpg',
 'man-845847_150.jpg']

In [1]:
import pandas as pd
metadata=pd.read_excel("metadata.xlsx")
#list =['datalake_media/image-vegetables-1085063_150.jpg-35dd8b2f-7644-432c-a47c-841f3f1d3e15', 'datalake_media/image-diet-695723_150.jpg-80cbbef6-f48c-4f5a-93e5-92413ab308a6', 'datalake_media/image-father-22194_150.jpg-431f5128-c2f6-4588-a7b0-ed64f3bb59c1', 'datalake_media/image-snack-3579973_150.png-539e4e72-b9a8-422c-bae5-efd2afb6b4ac', 'datalake_media/image-dna-4068826_150.jpg-e4b38802-e684-4814-8ffe-a2d61460dfb7', 'datalake_media/image-olive-oil-968657_150.jpg-cc99674b-ab5c-450a-a86c-4eb91cfa3a17', 'datalake_media/image-scale-403585_150.jpg-607dfa8b-2007-47e9-be5d-7dd7d8715ad0', 'datalake_media/image-depression-2826711_150.jpg-a98fe930-0906-43a1-86fa-9e485ea06582', 'datalake_media/image-food-366875_150.jpg-f0e09e54-05bc-4d56-a5eb-f22e6de7cf23', 'datalake_media/image-still-life-2366084_150.jpg-f769f30e-8922-4810-8aa9-853e58c03bbc', 'datalake_media/image-still-life-562357_150.jpg-d915458b-a331-46e2-8da4-90c5cb8843c4', 'datalake_media/image-herbs-906140_150.jpg-9883ec5f-181d-436a-b85c-a12e7ee97082', 'datalake_media/image-butter-3411126_150.jpg-e103ed27-d095-428f-929d-b44dadb98dd1', 'datalake_media/image-harmful-food-1803600_150.jpg-3bec5f5c-9ede-4dbd-a8d9-7e9599fa5c61', 'datalake_media/image-herbs-906140_150.jpg-e5436fc6-afdc-4601-b2a3-565b532d8109', 'datalake_media/image-berries-2277_150.jpg-de191284-7f59-404b-9998-e2432915af8b', 'datalake_media/image-salad-2756467_150.jpg-dbf7a749-1b1b-41a4-83c3-9fa78b75f22a', 'datalake_media/image-belly-2354_150.jpg-a8c8b1ca-4dc6-4090-a987-31f42bd83939', 'datalake_media/image-berries-2277_150.jpg-64978557-5c2c-42d4-b383-405fdcb5fdd7', 'datalake_media/image-berries-2277_150.jpg-02f716e6-65ce-4276-8e51-bbba2c6dbf98', 'datalake_media/image-berries-2277_150.jpg-a7fc2199-d0ca-4853-83d3-c1b899b15d20', 'datalake_media/image-meal-1307604_150.jpg-05d1136a-2e1d-4a47-b840-e1d0a28495bd', 'datalake_media/image-obesity-993126_150.jpg-4aecb3d1-74b5-44de-aa49-d55b401e3894', 'datalake_media/image-spaghetti-1932466_150.jpg-0020f3bb-f65a-4d47-a5f6-9627ea7df4b3', 'datalake_media/image-onion-7434358_150.jpg-9bbe22da-6855-469f-b12f-1d13adf5a322', 'datalake_media/image-berries-2277_150.jpg-325b785a-21c8-4943-9238-93564503179d', 'datalake_media/image-woman-3186730_150.jpg-73d802b6-206d-4857-ab89-8268ca0566c8', 'datalake_media/image-fat-3313923_150.png-7d1613e1-1983-4f7c-ae34-c8348524a2b1', 'datalake_media/image-vegetables-752153_150.jpg-21409b28-2ba3-41b4-a59b-e1df8715f9a8', 'datalake_media/image-berries-3504149_150.jpg-3a352ffa-9bce-4d0d-a30f-524c3454b590', 'datalake_media/image-tree-736885_150.jpg-913005d8-4bca-45bb-ba10-8c8e81cb7b98', 'datalake_media/image-spring-2174750_150.jpg-5d4ae088-ca92-4280-a790-a8304c8a74ee', 'datalake_media/image-mountain-806915_150.jpg-2bca67a6-1995-4b85-8c0f-afd180db52e7', 'datalake_media/image-alpaca-5405469_150.jpg-7d8e84da-3ecd-44a6-a17c-79429c8d38ed', 'datalake_media/image-road-1072823_150.jpg-bdcaac04-eec0-4572-a6cf-1dd44772dab2', 'datalake_media/image-blooming-4112348_150.jpg-3546b127-debc-4d29-825d-833963f50b6e', 'datalake_media/image-sky-4576072_150.jpg-f1c9fe55-2f53-42ed-b512-f9cdbb0aa74b', 'datalake_media/image-istanbul-1641539_150.jpg-c79c7114-b0cf-4e03-b923-8ea6fc3c6802', 'datalake_media/image-tree-736885_150.jpg-52b915eb-a047-48ad-8e77-c06cbfdd7829', 'datalake_media/image-baby-1151351_150.jpg-5208199a-0e4c-4abe-8fa9-57615dbaf6bf']
#processed_image_paths=[path.split('.jpg')[0].replace("datalake_media/image-", "") + '.jpg' if '.jpg' in path else path.replace("datalake_media/image-", "") for path in list]
metadata

,name,keywords,url,type,term,path_datalake,description,keywords_description,source
0,social-media-1360.mp4,"['social media', 'smart phone', 'mobile']",https://cdn.pixabay.com/vimeo/147055409/social...,video,phone,datalake_media/video-social-media-1360.mp4-e07...,a person holding a cell phone next to a cup,"['cup', 'phone', 'holding', 'person', 'cell']",pixabay
1,woman-38084.mp4,"['woman', 'phone', 'smartphone']",https://cdn.pixabay.com/vimeo/416330724/woman-...,video,phone,datalake_media/video-woman-38084.mp4-6979bca5-...,a woman holding a smart phone in her hand,"['woman', 'phone', 'hand', 'holding', 'smart']",pixabay
2,woman-174003.mp4,"['woman', 'social networking', 'post']",https://cdn.pixabay.com/vimeo/850361299/woman-...,video,phone,datalake_media/video-woman-174003.mp4-7f7eea97...,a woman holding a cell phone in her hand,"['woman', 'hand', 'phone', 'holding', 'cell']",pixabay
3,iphone-160307_150.png,"['iphone', 'cell phone', 'phone']",https://cdn.pixabay.com/photo/2013/07/13/12/46...,image,Smartphone,datalake_media/image-iphone-160307_150.png-6db...,a cell phone sitting on top of a table,"['phone', 'table', 'sitting', 'cell']",pixabay
4,mobile-phone-1875813_150.jpg,"['mobile phone', 'smartphone', 'hohenzollern c...",https://cdn.pixabay.com/photo/2016/12/01/18/17...,image,Smartphone,datalake_media/image-mobile-phone-1875813_150....,a model of a cell phone on a table,"['table', 'cell', 'model', 'phone']",pixabay
...,...,...,...,...,...,...,...,...,...
5197,sunflower-3113318_150.jpg,"['sunflower', 'nature', 'flower background']",https://cdn.pixabay.com/photo/2018/01/28/11/24...,image,sunflower,datalake_media/image-sunflower-3113318_150.jpg...,a close up picture of a flower in the sun,"['flower', 'sun', 'picture', 'close']",pixabay
5198,sunflower-1627193_150.jpg,"['sunflower', 'yellow', 'flower']",https://cdn.pixabay.com/photo/2016/08/28/23/24...,image,sunflower,datalake_media/image-sunflower-1627193_150.jpg...,a close up view of a bunch of yellow flowers,"['flowers', 'yellow', 'view', 'bunch', 'close']",pixabay
5199,sunflowers-59483.mp4,"['sunflowers', 'bees', 'field']",https://cdn.pixabay.com/vimeo/493557880/sunflo...,video,sunflower,datalake_media/video-sunflowers-59483.mp4-868f...,a blue sky with a bunch of blue water,"['blue', 'sky', 'water', 'bunch']",pixabay
5200,squirrel-2717.mp4,"['squirrel', 'head', 'grey squirrel']",https://cdn.pixabay.com/vimeo/161687558/squirr...,video,sunflower,datalake_media/video-squirrel-2717.mp4-b61aec9...,a small bird is perched on a tree branch,"['bird', 'tree', 'perched', 'branch', 'small']",pixabay
5201,bird-9334.mp4,"['bird', 'sparrow', 'sunflower']",https://cdn.pixabay.com/vimeo/219173276/bird-9...,video,sunflower,datalake_media/video-bird-9334.mp4-02cbb64f-4f...,a blue bird with a flower in it,"['bird', 'flower', 'blue']",pixabay

In [37]:
metadata = metadata[~metadata['name'].isin(processed_image_paths)]
metadata

if 'tree-736885_150.jpg' in image_paths:
    print("in dataframe")
else:
    image_paths.append('tree-736885_150.jpg')

print(image_paths)

in dataframe
['vegetables-1085063_150.jpg', 'diet-695723_150.jpg', 'father-22194_150.jpg', 'snack-3579973_150.png-539e4e72-b9a8-422c-bae5-efd2afb6b4ac', 'dna-4068826_150.jpg', 'olive-oil-968657_150.jpg', 'scale-403585_150.jpg', 'depression-2826711_150.jpg', 'food-366875_150.jpg', 'still-life-2366084_150.jpg', 'still-life-562357_150.jpg', 'herbs-906140_150.jpg', 'butter-3411126_150.jpg', 'harmful-food-1803600_150.jpg', 'herbs-906140_150.jpg', 'berries-2277_150.jpg', 'salad-2756467_150.jpg', 'belly-2354_150.jpg', 'berries-2277_150.jpg', 'berries-2277_150.jpg', 'berries-2277_150.jpg', 'meal-1307604_150.jpg', 'obesity-993126_150.jpg', 'spaghetti-1932466_150.jpg', 'onion-7434358_150.jpg', 'berries-2277_150.jpg', 'woman-3186730_150.jpg', 'fat-3313923_150.png-7d1613e1-1983-4f7c-ae34-c8348524a2b1', 'vegetables-752153_150.jpg', 'berries-3504149_150.jpg', 'tree-736885_150.jpg', 'spring-2174750_150.jpg', 'mountain-806915_150.jpg', 'alpaca-5405469_150.jpg', 'road-1072823_150.jpg', 'blooming-4112348_150.jpg', 'sky-4576072_150.jpg', 'istanbul-1641539_150.jpg', 'tree-736885_150.jpg', 'baby-1151351_150.jpg', 'signs-1172211_150.jpg', 'man-845847_150.jpg']

In [2]:
metadata = metadata.drop_duplicates(subset=['name'])
metadata.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4506 entries, 0 to 5201
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   name                  4506 non-null   object
 1   keywords              4506 non-null   object
 2   url                   4506 non-null   object
 3   type                  4506 non-null   object
 4   term                  4506 non-null   object
 5   path_datalake         4506 non-null   object
 6   description           4506 non-null   object
 7   keywords_description  4506 non-null   object
 8   source                4506 non-null   object
dtypes: object(9)
memory usage: 352.0+ KB

In [3]:
metadata.to_excel("metadata.xlsx")

In [4]:
from nltk.stem import PorterStemmer
import gensim.downloader as api
from gensim.models import KeyedVectors
from nltk.tokenize import word_tokenize

def stem_words_(words):
    porter = PorterStemmer()
    tokens = word_tokenize(words)
    stemmed_words = [porter.stem(word) for word in tokens]

    return stemmed_words

def find_main_terms(row, n=3):
    combined_keywords = row['topic_name']+[row['term']]+ row['keywords'] + row['keywords_description'] 
    stemmed_keywords = stem_words_(' '.join(combined_keywords))
    keyword_freq = pd.Series(stemmed_keywords).value_counts()
    print(keyword_freq)
    top_terms = keyword_freq.head(n).index.tolist()

    return top_terms

In [5]:
df_image=metadata
df_image['term']= df_image['term'].astype(str)
df_image['topic_name'] = df_image['name'].str.split('-').str[0].apply(lambda x: [x])
df_image['keywords_description'] = df_image['keywords_description'].apply(lambda x: eval(x))
df_image['keywords'] = df_image['keywords'].apply(lambda x: eval(x))
df_image['main_topic'] = df_image.apply(find_main_terms, axis=1)

/var/folders/ys/s5c8y6vx2n95hnjtr5vs5h000000gn/T/ipykernel_45175/1034972319.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_image['term']= df_image['term'].astype(str)
/var/folders/ys/s5c8y6vx2n95hnjtr5vs5h000000gn/T/ipykernel_45175/1034972319.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_image['topic_name'] = df_image['name'].str.split('-').str[0].apply(lambda x: [x])
/var/folders/ys/s5c8y6vx2n95hnjtr5vs5h000000gn/T/ipykernel_45175/1034972319.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_image['keywords_description'] = df_image['keywords_description'].apply(lambda x: eval(x))
/var/folders/ys/s5c8y6vx2n95hnjtr5vs5h000000gn/T/ipykernel_45175/1034972319.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_image['keywords'] = df_image['keywords'].apply(lambda x: eval(x))

phone     3
social    2
media     1
smart     1
mobil     1
cup       1
hold      1
person    1
cell      1
Name: count, dtype: int64
woman        3
phone        3
smartphon    1
hand         1
hold         1
smart        1
Name: count, dtype: int64
woman      3
phone      2
social     1
network    1
post       1
hand       1
hold       1
cell       1
Name: count, dtype: int64
phone        3
iphon        2
cell         2
smartphon    1
tabl         1
sit          1
Name: count, dtype: int64
mobil           2
smartphon       2
phone           2
hohenzollern    1
castl           1
tabl            1
cell            1
model           1
Name: count, dtype: int64
offic        2
smartphon    1
busi         1
account      1
sit          1
phone        1
tabl         1
person       1
cell         1
Name: count, dtype: int64
train        3
smartphon    2
track        2
railroad     1
phone        1
person       1
hold         1
Name: count, dtype: int64
smartphon      3
cellphon       1
touchscreen    1
appl           1
tabl           1
person         1
hold           1
Name: count, dtype: int64
iphon        2
smartphon    2
app          1
hand         1
phone        1
hold         1
person       1
cell         1
Name: count, dtype: int64
phone        3
smartphon    1
display      1
app          1
sticker      1
cell         1
Name: count, dtype: int64
coffe        3
smartphon    1
phone        1
paper        1
cup          1
sit          1
wooden       1
tabl         1
Name: count, dtype: int64
mobil        2
smartphon    2
hand         2
phone        1
wii          1
control      1
hold         1
person       1
Name: count, dtype: int64
mobil        2
smartphon    2
phone        2
keyboard     2
sit          1
cell         1
Name: count, dtype: int64
tablet       2
screen       2
smartphon    1
monitor      1
sticker      1
comput       1
bunch        1
Name: count, dtype: int64
desk         2
smartphon    2
iphon        1
laptop       1
tabl         1
comput       1
sit          1
white        1
Name: count, dtype: int64
iphon        2
hand         2
smartphon    1
screen       1
phone        1
hold         1
person       1
cell         1
Name: count, dtype: int64
busi         2
comput       2
smartphon    1
mobil        1
desk         1
laptop       1
wooden       1
sit          1
Name: count, dtype: int64
glass        2
phone        2
smartphon    1
book         1
wooden       1
sit          1
tabl         1
cell         1
Name: count, dtype: int64
music        2
smartphon    1
relax        1
anim         1
eleph        1
photo        1
black        1
white        1
Name: count, dtype: int64
watercolor    2
paint         2
smartphon     1
color         1
watermelon    1
pool          1
middl         1
Name: count, dtype: int64
offic        2
smartphon    2
desk         1
laptop       1
comput       1
wooden       1
tabl         1
sit          1
Name: count, dtype: int64
smartphon    3
appl         1
cellphon     1
tabl         1
phone        1
sit          1
cell         1
black        1
Name: count, dtype: int64
imac         2
smartphon    1
ipad         1
iphon        1
monitor      1
tabl         1
sit          1
comput       1
Name: count, dtype: int64
spice        2
smartphon    1
spoon        1
salt         1
tabl         1
wooden       1
top          1
lot          1
stuff        1
Name: count, dtype: int64
digit        2
smartphon    1
market       1
seo          1
googl        1
screen       1
phone        1
person       1
comput       1
hold         1
Name: count, dtype: int64
social       3
smartphon    1
media        1
commun       1
screen       1
phone        1
display      1
cell         1
Name: count, dtype: int64
social       2
smartphon    1
media        1
facebook     1
twitter      1
screen       1
phone        1
cell         1
show         1
white        1
Name: count, dtype: int64
social       2
smartphon    1
media        1
connect      1
concept      1
graffiti     1
wall         1
collag       1
color        1
Name: count, dtype: int64
telephon     2
smartphon    1
mobil        1
call         1
hand         1
phone        1
hold         1
person       1
cell         1
Name: count, dtype: int64
laptop       3
wordpress    2
smartphon    1
design       1
comput       1
wooden       1
tabl         1
sit          1
Name: count, dtype: int64
iphon        2
smartphon    1
hand         1
girl         1
shoe         1
bench        1
hold         1
woman        1
pair         1
Name: count, dtype: int64
mysteri      2
smartphon    1
island       1
dinosaur     1
mountain     1
water        1
rang         1
larg         1
bodi         1
Name: count, dtype: int64
miniatur      2
skateboard    2
smartphon     1
toy           1
tabl          1
phone         1
cell          1
Name: count, dtype: int64
mobil        2
phone        2
smartphon    1
samsung      1
wooden       1
sit          1
tabl         1
cell         1
Name: count, dtype: int64
mobil         3
phone         3
smartphon     1
background    1
blue          1
cell          1
shown         1
Name: count, dtype: int64
social       2
smartphon    2
media        1
facebook     1
tabl         1
keyboard     1
phone        1
cell         1
top          1
Name: count, dtype: int64
appl         2
smartphon    2
desk         1
laptop       1
comput       1
wooden       1
tabl         1
sit          1
Name: count, dtype: int64
mobil        2
smartphon    2
app          1
phone        1
tabl         1
cell         1
type         1
number       1
Name: count, dtype: int64
smartphon    3
hand         1
screen       1
crowd        1
person       1
phone        1
hold         1
cell         1
Name: count, dtype: int64
smartphon    3
app          1
news         1
hand         1
phone        1
hold         1
person       1
cell         1
Name: count, dtype: int64
telephon     2
smartphon    1
mobil        1
call         1
hand         1
phone        1
hold         1
cell         1
man          1
Name: count, dtype: int64
phone        3
smartphon    1
android      1
app          1
tabl         1
sit          1
cell         1
Name: count, dtype: int64
hand         3
smartphon    2
hold         2
phone        1
person       1
cell         1
Name: count, dtype: int64
laptop       2
smartphon    1
workspac     1
flat         1
design       1
screen       1
keyboard     1
mous         1
comput       1
Name: count, dtype: int64
appl         2
smartphon    1
iphon        1
notebook     1
laptop       1
comput       1
wooden       1
surfac       1
sit          1
Name: count, dtype: int64
technolog    2
laptop       2
smartphon    1
keyboard     1
comput       1
wooden       1
tabl         1
person       1
Name: count, dtype: int64
purs         2
bag          1
smartphon    1
pocket       1
leather      1
good         1
scissor      1
tabl         1
pair         1
Name: count, dtype: int64
hand         3
smartphon    2
phone        2
hold         1
person       1
cell         1
Name: count, dtype: int64
samsung      2
smartphon    2
hand         2
phone        1
hold         1
person       1
cell         1
Name: count, dtype: int64
internet     2
smartphon    2
whatsapp     1
phone        1
view         1
smart        1
close        1
Name: count, dtype: int64
woman        3
smartphon    2
technolog    1
phone        1
cell         1
look         1
Name: count, dtype: int64
man          4
phone        2
smartphon    1
black        1
mobil        1
build        1
cell         1
hold         1
Name: count, dtype: int64
brown         2
man           2
smartphon     1
leather       1
shoe          1
earphon       1
skateboard    1
lean          1
wall          1
Name: count, dtype: int64
fruit     3
bowl      3
fresh     2
nutrit    1
veget     1
tabl      1
wooden    1
Name: count, dtype: int64
veget      3
fruit      2
nutrit     1
food       1
tabl       1
varieti    1
Name: count, dtype: int64
oliv      3
nutrit    1
oil       1
food      1
juic      1
glass     1
orang     1
tabl      1
sit       1
Name: count, dtype: int64
tree        2
sunset      2
sun         1
cloud       1
umbrella    1
beach       1
Name: count, dtype: int64
woman    3
sun      1
girl     1
natur    1
beach    1
ocean    1
stand    1
Name: count, dtype: int64
ocean    3
sun      2
natur    1
sea      1
wave     1
set      1
Name: count, dtype: int64
coffe     3
cup       2
food      1
morn      1
pillow    1
sit       1
Name: count, dtype: int64
lunch      2
food       1
meal       1
peopl      1
laptop     1
kitchen    1
comput     1
person     1
use        1
Name: count, dtype: int64
dog      3
food     2
drink    1
pet      1
bowl     1
eat      1
black    1
Name: count, dtype: int64
wheat    3
field    2
food     1
natur    1
bird     1
grass    1
fli      1
bunch    1
Name: count, dtype: int64
coffe      2
food       1
bean       1
caffein    1
dirt       1
beach      1
rock       1
pile       1
Name: count, dtype: int64
field         3
food          1
cornfield     1
agricultur    1
grass         1
sky           1
background    1
bunch         1
Name: count, dtype: int64
pot      3
food     1
cook     1
steam    1
boil     1
stove    1
water    1
Name: count, dtype: int64
fruit     3
bowl      2
food      1
salad     1
flower    1
pink      1
purpl     1
fill      1
Name: count, dtype: int64
restaur    2
food       1
buffet     1
cuisin     1
vase       1
flower     1
blue       1
Name: count, dtype: int64
pasta      3
food       2
mix        1
sauc       1
blender    1
person     1
Name: count, dtype: int64
slice     2
food      1
chines    1
cabbag    1
tabl      1
surfac    1
blue      1
white     1
Name: count, dtype: int64
roast     2
food      1
pork      1
meat      1
flower    1
vase      1
Name: count, dtype: int64
fish         3
food         1
fisherman    1
sailboat     1
dock         1
wooden       1
Name: count, dtype: int64
run        2
food       2
sushi      2
japanes    1
plate      1
cake       1
blue       1
white      1
Name: count, dtype: int64
chop       2
food       1
cut        1
ingredi    1
tabl       1
object     1
sit        1
white      1
Name: count, dtype: int64
veget      2
food       1
beauti     1
wallpap    1
pea        1
blue       1
sky        1
object     1
light      1
singl      1
Name: count, dtype: int64
beef       2
food       1
patti      1
hamburg    1
cake       1
tabl       1
sit        1
wooden     1
blue       1
Name: count, dtype: int64
cook       2
food       2
meal       1
scissor    1
tabl       1
pair       1
Name: count, dtype: int64
roulad     2
food       1
cook       1
wrap       1
bowl       1
counter    1
blue       1
white      1
Name: count, dtype: int64
appl      2
food      1
rain      1
wind      1
bird      1
bench     1
sit       1
wooden    1
blue      1
Name: count, dtype: int64
swan     2
food     1
gull     1
duck     1
bird     1
flock    1
fli      1
water    1
bodi     1
Name: count, dtype: int64
wine       3
glass      3
restaur    2
food       1
tabl       1
Name: count, dtype: int64
food     3
flame    1
cook     1
spoon    1
stove    1
pot      1
Name: count, dtype: int64
squirrel    2
food        1
chipmunk    1
rodent      1
cat         1
tree        1
branch      1
sit         1
Name: count, dtype: int64
bird      3
food      1
forest    1
blue      1
tit       1
perch     1
branch    1
Name: count, dtype: int64
veget     3
stand     2
food      1
tomato    1
red       1
pile      1
man       1
Name: count, dtype: int64
deer     2
food     2
anim     2
pile     1
stand    1
rock     1
small    1
Name: count, dtype: int64
seoul     2
street    2
crowd     2
food      1
night     1
korea     1
peopl     1
stand     1
Name: count, dtype: int64
raspberri     2
food          1
berri         1
summer        1
flower        1
blue          1
plant         1
green         1
background    1
Name: count, dtype: int64
girl      2
food      1
eat       1
stuf      1
laptop    1
tabl      1
woman     1
sit       1
Name: count, dtype: int64
green    2
field    2
food     1
wheat    1
grass    1
bunch    1
tall     1
Name: count, dtype: int64
grain     2
food      1
barley    1
spike     1
grass     1
field     1
green     1
bunch     1
Name: count, dtype: int64
coffe     3
laptop    2
food      1
work      1
cup       1
sit       1
tabl      1
Name: count, dtype: int64
onion      2
food       1
cut        1
hand       1
scissor    1
wooden     1
tabl       1
pair       1
green      1
Name: count, dtype: int64
diet      2
food      1
to        1
lose      1
weight    1
slim      1
knife     1
cut       1
person    1
Name: count, dtype: int64
drink     2
food      1
café      1
clean     1
wall      1
hang      1
object    1
color     1
Name: count, dtype: int64
appl      2
food      1
rain      1
water     1
ball      1
ledg      1
sit       1
blue      1
yellow    1
Name: count, dtype: int64
breakfast    2
food         1
beauti       1
wallpap      1
hotel        1
blanket      1
lake         1
ground       1
Name: count, dtype: int64
rabbit    2
food      1
hare      1
bunni     1
bear      1
tree      1
brown     1
small     1
sit       1
Name: count, dtype: int64
grape    2
plant    2
food     1
vine     1
leaf     1
stem     1
green    1
Name: count, dtype: int64
steak     2
food      1
grill     1
meat      1
knife     1
wooden    1
stick     1
surfac    1
Name: count, dtype: int64
chop       2
food       2
veget      1
scissor    1
person     1
pair       1
hold       1
Name: count, dtype: int64
rabbit    3
anim      2
food      1
grassi    1
pile      1
dead      1
area      1
Name: count, dtype: int64
blue      2
food      2
colour    2
blurri    1
art       1
photo     1
piec      1
Name: count, dtype: int64
chef       2
food       1
restaur    1
3d         1
bow        1
stuf       1
anim       1
head       1
Name: count, dtype: int64
wine        2
food        1
grape       1
grapevin    1
flower      1
field       1
yellow      1
green       1
larg        1
Name: count, dtype: int64
cook        2
food        1
ecommerc    1
comput      1
kitchen     1
microwav    1
counter     1
blender     1
clock       1
Name: count, dtype: int64
fresh        2
food         1
fruit        1
blueberri    1
dessert      1
glass        1
flower       1
water        1
Name: count, dtype: int64
sizzl      2
food       1
steak      1
barbecu    1
ball       1
plastic    1
contain    1
fill       1
green      1
Name: count, dtype: int64
tit       2
bird      2
food      1
the       1
manger    1
branch    1
sit       1
small     1
Name: count, dtype: int64
rat       2
food      1
rodent    1
meal      1
cat       1
lay       1
bowl      1
water     1
Name: count, dtype: int64
cook       2
food       1
prawn      1
in         1
arrow      1
traffic    1
green      1
light      1
black      1
Name: count, dtype: int64
cook       2
potato     2
food       1
fish       1
contain    1
plastic    1
knife      1
Name: count, dtype: int64
bee       2
food      1
flight    1
beehiv    1
bird      1
perch     1
feeder    1
ledg      1
near      1
Name: count, dtype: int64
pizza    3
food     1
salt     1
spice    1
sit      1
tabl     1
Name: count, dtype: int64
monaco    2
street    2
food      1
citi      1
walk      1
scene     1
peopl     1
Name: count, dtype: int64
veget     2
food      2
cucumb    1
knife     1
cut       1
plant     1
board     1
green     1
Name: count, dtype: int64
rye           2
food          1
grain         1
ear           1
sky           1
tree          1
dark          1
background    1
Name: count, dtype: int64
hamburg    2
food       2
egg        1
cake       1
slice      1
Name: count, dtype: int64
fire     2
food     1
blue     1
plate    1
stove    1
burn     1
insid    1
Name: count, dtype: int64
cherri    2
glass     2
food      1
fruit     1
vase      1
flower    1
blue      1
water     1
Name: count, dtype: int64
rice          2
food          1
field         1
agricultur    1
thailand      1
carpet        1
rug           1
stripe        1
green         1
white         1
Name: count, dtype: int64
chaffinch    2
food         1
feed         1
bird         1
tree         1
leaf         1
Name: count, dtype: int64
chicken    2
food       1
hen        1
full       1
hd         1
bird       1
vase       1
blue       1
sit        1
white      1
Name: count, dtype: int64
coffe       3
espresso    2
food        1
machin      1
cup         1
sit         1
maker       1
Name: count, dtype: int64
wineglass    2
wine         2
food         1
red          1
vase         1
glass        1
reflect      1
person       1
face         1
Name: count, dtype: int64
grape    2
green    2
food     1
fruit    1
leaf     1
plant    1
Name: count, dtype: int64
honey    2
food     2
sweet    1
bottl    1
blue     1
sit      1
rock     1
Name: count, dtype: int64
beef      2
food      1
curri     1
dinner    1
photo     1
object    1
white     1
black     1
Name: count, dtype: int64
pig      2
food     1
cake     1
parti    1
bear     1
toy      1
train    1
Name: count, dtype: int64
appl     3
tree     2
food     1
fruit    1
green    1
fill     1
lot      1
Name: count, dtype: int64
pizza      3
food       1
oven       1
restaur    1
hydrant    1
lid        1
blue       1
Name: count, dtype: int64
tomato    2
food      1
red       1
veget     1
vase      1
flower    1
purpl     1
blue      1
fill      1
Name: count, dtype: int64
schnitzel    2
food         1
meat         1
cook         1
pan          1
liquid       1
pour         1
blue         1
Name: count, dtype: int64
lemonad    2
food       1
pour       1
liquid     1
glass      1
water      1
tabl       1
sit        1
Name: count, dtype: int64
meat       2
food       1
cook       1
kitchen    1
paper      1
sheet      1
surfac     1
blue       1
white      1
Name: count, dtype: int64
tea      2
food     1
drink    1
morn     1
coffe    1
cup      1
sit      1
book     1
tabl     1
Name: count, dtype: int64
beer       2
glass      2
food       1
beauti     1
wallpap    1
water      1
bench      1
sit        1
wooden     1
Name: count, dtype: int64
ave       2
food      1
bird      1
natur     1
blurri    1
photo     1
street    1
light     1
scene     1
Name: count, dtype: int64
anim       2
food       1
tit        1
volatil    1
pond       1
bird       1
sit        1
rock       1
Name: count, dtype: int64
tomato    2
food      2
red       1
blurri    1
photo     1
street    1
light     1
scene     1
Name: count, dtype: int64
bbq        2
food       2
barbecu    1
chicken    1
wing       1
pan        1
blue       1
fill       1
pair       1
Name: count, dtype: int64
chines    2
hot       2
pot       2
food      1
dirt      1
water     1
fill      1
lot       1
Name: count, dtype: int64
cola       2
food       2
chicken    1
wing       1
bowl       1
water      1
fill       1
Name: count, dtype: int64
chop      2
food      2
cook      1
prepar    1
cut       1
hand      1
person    1
piec      1
Name: count, dtype: int64
tomato    2
food      1
veget     1
fruit     1
flower    1
plate     1
blue      1
color     1
white     1
Name: count, dtype: int64
psychedel    2
food         1
abstract     1
colour       1
paint        1
flower       1
shadow       1
Name: count, dtype: int64
cereal    2
food      1
wheat     1
summer    1
tree      1
leav      1
blurri    1
photo     1
bunch     1
Name: count, dtype: int64
grape      2
food       1
blue       1
wine       1
harvest    1
leav       1
plant      1
bunch      1
Name: count, dtype: int64
hamburg      2
food         2
fast-food    1
figurin      1
ball         1
child        1
small        1
hold         1
Name: count, dtype: int64
fish       2
food       2
a          1
restaur    1
blurri     1
photo      1
street     1
light      1
scene      1
Name: count, dtype: int64
corn       2
food       1
seed       1
cereal     1
contain    1
blue       1
water      1
plastic    1
fill       1
Name: count, dtype: int64
appl      2
food      1
fruit     1
sweet     1
bird      1
blue      1
black     1
head      1
stripe    1

/var/folders/ys/s5c8y6vx2n95hnjtr5vs5h000000gn/T/ipykernel_45175/1034972319.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_image['main_topic'] = df_image.apply(find_main_terms, axis=1)

In [6]:
metadata["type"].value_counts()

type
image    4316
video     190
Name: count, dtype: int64

In [7]:
metadata

,name,keywords,url,type,term,path_datalake,description,keywords_description,source,topic_name,main_topic
0,social-media-1360.mp4,"[social media, smart phone, mobile]",https://cdn.pixabay.com/vimeo/147055409/social...,video,phone,datalake_media/video-social-media-1360.mp4-e07...,a person holding a cell phone next to a cup,"[cup, phone, holding, person, cell]",pixabay,[social],"[phone, social, media]"
1,woman-38084.mp4,"[woman, phone, smartphone]",https://cdn.pixabay.com/vimeo/416330724/woman-...,video,phone,datalake_media/video-woman-38084.mp4-6979bca5-...,a woman holding a smart phone in her hand,"[woman, phone, hand, holding, smart]",pixabay,[woman],"[woman, phone, smartphon]"
2,woman-174003.mp4,"[woman, social networking, post]",https://cdn.pixabay.com/vimeo/850361299/woman-...,video,phone,datalake_media/video-woman-174003.mp4-7f7eea97...,a woman holding a cell phone in her hand,"[woman, hand, phone, holding, cell]",pixabay,[woman],"[woman, phone, social]"
3,iphone-160307_150.png,"[iphone, cell phone, phone]",https://cdn.pixabay.com/photo/2013/07/13/12/46...,image,Smartphone,datalake_media/image-iphone-160307_150.png-6db...,a cell phone sitting on top of a table,"[phone, table, sitting, cell]",pixabay,[iphone],"[phone, iphon, cell]"
4,mobile-phone-1875813_150.jpg,"[mobile phone, smartphone, hohenzollern castle]",https://cdn.pixabay.com/photo/2016/12/01/18/17...,image,Smartphone,datalake_media/image-mobile-phone-1875813_150....,a model of a cell phone on a table,"[table, cell, model, phone]",pixabay,[mobile],"[mobil, smartphon, phone]"
...,...,...,...,...,...,...,...,...,...,...,...
5197,sunflower-3113318_150.jpg,"[sunflower, nature, flower background]",https://cdn.pixabay.com/photo/2018/01/28/11/24...,image,sunflower,datalake_media/image-sunflower-3113318_150.jpg...,a close up picture of a flower in the sun,"[flower, sun, picture, close]",pixabay,[sunflower],"[sunflow, flower, natur]"
5198,sunflower-1627193_150.jpg,"[sunflower, yellow, flower]",https://cdn.pixabay.com/photo/2016/08/28/23/24...,image,sunflower,datalake_media/image-sunflower-1627193_150.jpg...,a close up view of a bunch of yellow flowers,"[flowers, yellow, view, bunch, close]",pixabay,[sunflower],"[sunflow, yellow, flower]"
5199,sunflowers-59483.mp4,"[sunflowers, bees, field]",https://cdn.pixabay.com/vimeo/493557880/sunflo...,video,sunflower,datalake_media/video-sunflowers-59483.mp4-868f...,a blue sky with a bunch of blue water,"[blue, sky, water, bunch]",pixabay,[sunflowers],"[sunflow, bee, field]"
5200,squirrel-2717.mp4,"[squirrel, head, grey squirrel]",https://cdn.pixabay.com/vimeo/161687558/squirr...,video,sunflower,datalake_media/video-squirrel-2717.mp4-b61aec9...,a small bird is perched on a tree branch,"[bird, tree, perched, branch, small]",pixabay,[squirrel],"[squirrel, sunflow, head]"
5201,bird-9334.mp4,"[bird, sparrow, sunflower]",https://cdn.pixabay.com/vimeo/219173276/bird-9...,video,sunflower,datalake_media/video-bird-9334.mp4-02cbb64f-4f...,a blue bird with a flower in it,"[bird, flower, blue]",pixabay,[bird],"[bird, sunflow, sparrow]"

In [18]:
df_image.to_excel("metadata.xlsx")

In [19]:
import pandas as pd
metadata=pd.read_excel("metadata.xlsx")

In [20]:
metadata.head()

,Unnamed: 0,name,keywords,url,type,term,path_datalake,description,keywords_description,source,topic_name,main_topic,count_usage,count_edit,media_state
0,0,social-media-1360.mp4,"['social media', 'smart phone', 'mobile']",https://cdn.pixabay.com/vimeo/147055409/social...,video,phone,datalake_media/video-social-media-1360.mp4-e07...,a person holding a cell phone next to a cup,"['cup', 'phone', 'holding', 'person', 'cell']",pixabay,['social'],"['phone', 'social', 'media']",0,0,useful
1,1,woman-38084.mp4,"['woman', 'phone', 'smartphone']",https://cdn.pixabay.com/vimeo/416330724/woman-...,video,phone,datalake_media/video-woman-38084.mp4-6979bca5-...,a woman holding a smart phone in her hand,"['woman', 'phone', 'hand', 'holding', 'smart']",pixabay,['woman'],"['woman', 'phone', 'smartphon']",0,0,useful
2,2,woman-174003.mp4,"['woman', 'social networking', 'post']",https://cdn.pixabay.com/vimeo/850361299/woman-...,video,phone,datalake_media/video-woman-174003.mp4-7f7eea97...,a woman holding a cell phone in her hand,"['woman', 'hand', 'phone', 'holding', 'cell']",pixabay,['woman'],"['woman', 'phone', 'social']",0,0,useful
3,3,iphone-160307_150.png,"['iphone', 'cell phone', 'phone']",https://cdn.pixabay.com/photo/2013/07/13/12/46...,image,Smartphone,datalake_media/image-iphone-160307_150.png-6db...,a cell phone sitting on top of a table,"['phone', 'table', 'sitting', 'cell']",pixabay,['iphone'],"['phone', 'iphon', 'cell']",0,0,useful
4,4,mobile-phone-1875813_150.jpg,"['mobile phone', 'smartphone', 'hohenzollern c...",https://cdn.pixabay.com/photo/2016/12/01/18/17...,image,Smartphone,datalake_media/image-mobile-phone-1875813_150....,a model of a cell phone on a table,"['table', 'cell', 'model', 'phone']",pixabay,['mobile'],"['mobil', 'smartphon', 'phone']",0,0,useful

In [8]:
metadata=metadata.drop('scoring', axis=1)

In [8]:
metadata["count_usage"]=0
metadata["count_edit"]=0
metadata["media_state"]="useful"

/var/folders/ys/s5c8y6vx2n95hnjtr5vs5h000000gn/T/ipykernel_45175/1095117936.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  metadata["count_usage"]=0
/var/folders/ys/s5c8y6vx2n95hnjtr5vs5h000000gn/T/ipykernel_45175/1095117936.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  metadata["count_edit"]=0
/var/folders/ys/s5c8y6vx2n95hnjtr5vs5h000000gn/T/ipykernel_45175/1095117936.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  metadata["media_state"]="useful"

In [9]:
metadata.head()

,name,keywords,url,type,term,path_datalake,description,keywords_description,source,topic_name,main_topic,count_usage,count_edit,media_state
0,social-media-1360.mp4,"[social media, smart phone, mobile]",https://cdn.pixabay.com/vimeo/147055409/social...,video,phone,datalake_media/video-social-media-1360.mp4-e07...,a person holding a cell phone next to a cup,"[cup, phone, holding, person, cell]",pixabay,[social],"[phone, social, media]",0,0,useful
1,woman-38084.mp4,"[woman, phone, smartphone]",https://cdn.pixabay.com/vimeo/416330724/woman-...,video,phone,datalake_media/video-woman-38084.mp4-6979bca5-...,a woman holding a smart phone in her hand,"[woman, phone, hand, holding, smart]",pixabay,[woman],"[woman, phone, smartphon]",0,0,useful
2,woman-174003.mp4,"[woman, social networking, post]",https://cdn.pixabay.com/vimeo/850361299/woman-...,video,phone,datalake_media/video-woman-174003.mp4-7f7eea97...,a woman holding a cell phone in her hand,"[woman, hand, phone, holding, cell]",pixabay,[woman],"[woman, phone, social]",0,0,useful
3,iphone-160307_150.png,"[iphone, cell phone, phone]",https://cdn.pixabay.com/photo/2013/07/13/12/46...,image,Smartphone,datalake_media/image-iphone-160307_150.png-6db...,a cell phone sitting on top of a table,"[phone, table, sitting, cell]",pixabay,[iphone],"[phone, iphon, cell]",0,0,useful
4,mobile-phone-1875813_150.jpg,"[mobile phone, smartphone, hohenzollern castle]",https://cdn.pixabay.com/photo/2016/12/01/18/17...,image,Smartphone,datalake_media/image-mobile-phone-1875813_150....,a model of a cell phone on a table,"[table, cell, model, phone]",pixabay,[mobile],"[mobil, smartphon, phone]",0,0,useful

In [10]:
metadata.to_excel("metadata.xlsx")

In [23]:
metadata['name'].value_counts()

name
social-media-1360.mp4        1
sugar-cane-312399_150.png    1
sugar-973899_150.jpg         1
cookie-3216243_150.jpg       1
macaroons-1975545_150.jpg    1
                            ..
notepad-1558811_150.jpg      1
remote-5491798_150.png       1
milky-way-5295160_150.jpg    1
salad-2068217_150.jpg        1
bird-9334.mp4                1
Name: count, Length: 4506, dtype: int64

In [2]:
def stem_words(word,porter):
    stemmed_word = porter.stem(word) 
    return stemmed_word
import pandas as pd
metadata=pd.read_excel('metadata.xlsx')

def find_image_for_term(term, processed_terms, processed_image_paths, metadata, image_folder):

    topic_found = False
    image_found = False
    image_name = None
    metadata = metadata.dropna(subset=['keywords_description'])
    metadata = metadata[~metadata['path_datalake'].isin(processed_image_paths)]
    url_datalake_path = None 

    if term not in processed_terms:
        for idx, meta_row in metadata.iterrows():
            main_topic_stemmed = meta_row['main_topic']  # Assuming main_topic is a list of stemmed words
            # Check for exact match
            main_topic_list = eval(main_topic_stemmed)
            if term in main_topic_list:  
                image_name = meta_row['name']
                url_datalake_path = meta_row['path_datalake'] 
                if url_datalake_path is not None:
                    processed_terms.add(term)
                    topic_found = True
                    image_found = True
                break

    return topic_found, image_found, image_name, url_datalake_path


topic_found, image_found, image_name, url_datalake_path=find_image_for_term('fat', set(), [], metadata, 'data')

In [7]:
processed_image_paths = []
for entry in existing_data:
    processed_image_paths.extend([part['image_key'] for part in entry['video_parts']])
print("processed_image_paths: ",processed_image_paths)

processed_image_paths:  ['datalake_media/image-maldives-1993704_150.jpg-70ef5ccd-0d53-41b5-a054-016be29f2be5', 'datalake_media/image-woman-3640935_150.jpg-57a84e56-ebe3-43ab-82e2-3962a8b15c0c', 'datalake_media/image-winding-road-1556177_150.jpg-8be11ffb-2a1a-4b7c-914f-b3ff9cdc600b', 'datalake_media/image-loveourplanet-4851331_150.jpg-3c37bf5d-9e2b-44d0-8b91-d7e1c78df429', 'datalake_media/image-berries-3504149_150.jpg-5ed7c7f5-1e92-4d82-99f7-83ae38c2667f', 'datalake_media/image-mental-health-4232031_150.jpg-f4dd181f-c229-4dce-a90e-0b2525d563e8', 'datalake_media/image-salad-2068217_150.jpg-e32c1bab-cd4b-4af3-a014-9ae349d266a9', 'datalake_media/image-egg-slicer-647531_150.jpg-2a781df0-34b2-4e72-aa1f-8fb68c8a82dd', 'datalake_media/image-egg-24404_150.png-1f2a2357-2616-4015-847d-28ffdb2dbc37', 'datalake_media/image-berries-3504149_150.jpg-5ed7c7f5-1e92-4d82-99f7-83ae38c2667f', 'datalake_media/image-diet-695723_150.jpg-80cbbef6-f48c-4f5a-93e5-92413ab308a6', 'datalake_media/image-obesity-993126_150.jpg-8bfbdf8b-4fe6-472b-85e3-56071ec4cac1', 'datalake_media/image-vegetables-1085063_150.jpg-dfde1727-a532-4948-b32e-5d11f9728d94', 'datalake_media/image-egg-24404_150.png-1f2a2357-2616-4015-847d-28ffdb2dbc37', 'datalake_media/image-healthy-7213383_150.jpg-f00b2ce4-be70-4f7b-b2dd-9af208eece27', 'datalake_media/image-diet-695723_150.jpg-80cbbef6-f48c-4f5a-93e5-92413ab308a6', 'datalake_media/image-fat-3313923_150.png-5cc9dc32-49a5-4bb5-a0a6-748a236dcee3', 'datalake_media/image-food-366875_150.jpg-f0e09e54-05bc-4d56-a5eb-f22e6de7cf23', 'datalake_media/image-fresh-fruits-2305192_150.jpg-c3ac1f28-856e-4874-93bc-9521ee731014', 'datalake_media/image-berries-3504149_150.jpg-ee1fcfd6-7430-4f8c-ac1b-37e1be1755a1', 'datalake_media/image-salad-2756467_150.jpg-d560f898-8b1e-493b-a321-815befa06aac', 'datalake_media/image-pattern-1477380_150.png-b1ea4604-6d08-4f41-9be3-62c829e42030', 'datalake_media/image-berries-2277_150.jpg-b8c34cce-b019-4349-a488-b3208781ffa9', 'datalake_media/image-fresh-fruits-2305192_150.jpg-d6353a5e-8ef4-46eb-a52c-27cde7a89b85', 'datalake_media/image-healthy-7213383_150.jpg-f00b2ce4-be70-4f7b-b2dd-9af208eece27', 'datalake_media/image-diet-695723_150.jpg-80cbbef6-f48c-4f5a-93e5-92413ab308a6', 'datalake_media/image-fat-3313923_150.png-5cc9dc32-49a5-4bb5-a0a6-748a236dcee3', 'datalake_media/image-food-366875_150.jpg-f0e09e54-05bc-4d56-a5eb-f22e6de7cf23', 'datalake_media/image-fresh-fruits-2305192_150.jpg-7ba683a1-00a5-4565-8159-e0c7cfaffb4f', 'datalake_media/image-food-1898194_150.jpg-73d3c3f5-1584-4d24-a612-ccfcac55c57f', 'datalake_media/image-diet-1949478_150.jpg-eeac3eed-3090-443e-991c-c995b66f2f18', 'datalake_media/image-fat-3313923_150.png-288c7068-8ef6-4365-a86a-3e13bdea9405', 'datalake_media/image-vegetables-1085063_150.jpg-e0fc72ee-cb06-4971-891d-430e3171a61c', 'datalake_media/image-food-1898194_150.jpg-18c457d0-cc1d-40d3-878b-c072b8f10968', 'datalake_media/image-herbs-906140_150.jpg-60b4d1a3-5d20-4970-93cc-23f883b0dfe4', 'datalake_media/image-fruit-3111745_150.jpg-e73710d4-02cb-4af9-9958-b0a882fe63ab', 'datalake_media/image-fat-dog-4392363_150.jpg-e33f56d4-9b15-4f27-9c91-1d651ec51386', 'datalake_media/image-berries-2277_150.jpg-27e46fae-e19f-4ffb-85cc-6a49a2407098', 'datalake_media/image-herbs-906140_150.jpg-d10c7737-b7aa-404e-83ab-ff775fbc3cd2', 'datalake_media/image-vegetables-3679075_150.jpg-6b2e7f9a-145d-4a9a-a459-2c525daf1ab3', 'datalake_media/image-fruit-3111745_150.jpg-c421aa0b-79a6-4310-97a9-58f7db350386', 'datalake_media/image-butter-3411126_150.jpg-26c275fd-c576-424e-b12e-9fd4de1a8958', 'datalake_media/image-berries-2277_150.jpg-e9ad4ec3-ca3b-4e3a-adf3-6e531a154735', 'datalake_media/image-vegetables-2008578_150.png-48d6142b-49f3-42c3-a5b6-bea2ac71aee0']

In [4]:
url_datalake_path
processed_image_paths=[]
processed_image_paths.append(url_datalake_path)

In [8]:
processed_image_paths=[path.split('.jpg')[0].replace("datalake_media/image-", "") + '.jpg' if '.jpg' in path else path.replace("datalake_media/image-", "") for path in processed_image_paths]

In [6]:
processed_image_paths

['churros-2188871_150.jpg']

In [38]:
import nltk
from nltk.corpus import wordnet

# Download WordNet data (if not already downloaded)

def calculate_similarity(term1, term2):
    synsets1 = wordnet.synsets(term1)
    synsets2 = wordnet.synsets(term2)

    max_similarity = 0

    for synset1 in synsets1:
        for synset2 in synsets2:
            similarity = synset1.wup_similarity(synset2)  # Wu-Palmer Similarity
            if similarity is not None and similarity > max_similarity:
                max_similarity = similarity

    return max_similarity

# Test the function with "nutrition" and "olive"
term1 = "nutrition"
term2 = "avocado"
similarity_score = calculate_similarity(term1, term2)
print(similarity_score)

0.42857142857142855

In [21]:
from topic import find_topics,audio_generation

df = find_topics("In the quest for healthier lives, a groundbreaking discovery emerges from the labs of the National University of Singapore. Led by Professor Ashok Venkitaraman, this dynamic team has unlocked a vital link between diet and cancer risk. Their study, published in Cell, reveals how a common chemical, methylglyoxal. found in diabetes, obesity, and poor diets, can heighten the risk of cancer Our research shows that high levels of methylglyoxal can trigger DNA faults, signaling an increased risk of cancer. But here's the game-changer: methylglyoxal levels can be detected with a simple blood test, offering a proactive approach to cancer prevention And that's not all! The team's work challenges old theories, suggesting that poor diet can temporarily silence cancer-preventing genes. As they embark on further research, the future looks bright for innovative approaches to cancer prevention and healthier living")
df

,id,original_sentence,sentence,topic,terms,sentence_part_id
0,1,"In the quest for healthier lives, a groundbrea...",In the quest for healthier lives,2,"[groundbreaking, embark, approaches, quest]",0
1,1,"In the quest for healthier lives, a groundbrea...",a groundbreaking discovery emerges from the l...,2,"[groundbreaking, embark, approaches, quest]",1
2,2,"Led by Professor Ashok Venkitaraman, this dyna...",Led by Professor Ashok Venkitaraman,3,"[team, ashok, challenges, work]",2
3,2,"Led by Professor Ashok Venkitaraman, this dyna...",this dynamic team has unlocked a vital link b...,3,"[team, ashok, challenges, work]",3
4,3,"Their study, published in Cell, reveals how a ...","Their study, published in Cell, reveals how a ...",7,"[methylglyoxal, cell, chemical, common, study]",4
5,4,"found in diabetes, obesity, and poor diets, ca...","found in diabetes, obesity, and poor diets",1,"[cancer, risk, research, shows, diets]",5
6,4,"found in diabetes, obesity, and poor diets, ca...",can heighten the risk of cancer Our research ...,1,"[cancer, risk, research, shows, diets]",6
7,5,But here's the game-changer: methylglyoxal lev...,But here's the game-changer: methylglyoxal lev...,4,"[prevention, cancer, blood, test, approach]",7
8,5,But here's the game-changer: methylglyoxal lev...,offering a proactive approach to cancer preve...,4,"[prevention, cancer, blood, test, approach]",8
9,6,"The team's work challenges old theories, sugge...",The team's work challenges old theories,3,"[team, ashok, challenges, work]",9
10,6,"The team's work challenges old theories, sugge...",suggesting that poor diet can temporarily sil...,3,"[team, ashok, challenges, work]",10
11,7,"As they embark on further research, the future...",As they embark on further research,2,"[groundbreaking, embark, approaches, quest]",11
12,7,"As they embark on further research, the future...",the future looks bright for innovative approa...,2,"[groundbreaking, embark, approaches, quest]",12

In [22]:
df['sentence'].to_csv("test9.csv")

In [44]:
from moviepy.editor import VideoFileClip, ImageClip, TextClip, AudioFileClip, concatenate_videoclips, CompositeAudioClip, CompositeVideoClip
import os 

def generate_final_video(s3,video_id,background_music_file):

    background_music = AudioFileClip(background_music_file)
    background_music = background_music.volumex(0.2) 

    bucket = "soulchain-dev1-output-video"
    key = "video_info.json"

    response = s3.get_object(Bucket=bucket, Key=key)

    data = json.loads(response["Body"].read().decode("utf-8"))

    topic_clips = [
    part["video_part_key"] for video in data if video["video_id"] == video_id
    for part in video["video_parts"]
    ]

    clips = []
    for key in topic_clips:
        obj = s3.get_object(Bucket='soulchain-dev1-output-video', Key=key)
        file_path = key.split('/')[-1]
        with open(file_path, 'wb') as f:
            f.write(obj['Body'].read())
        clips.append(VideoFileClip(file_path))

    final_video = concatenate_videoclips(clips, method="compose")

    background_music = background_music.subclip(0, final_video.duration)
    final_video = final_video.set_audio(CompositeAudioClip([final_video.audio, background_music]))

    final_video_path = "final_video.mp4"
    final_video.write_videofile(final_video_path,audio_codec='aac')

    with open(final_video_path, "rb") as f:
        s3.upload_fileobj(f, 'soulchain-dev1-output-video', f"generated_videos/{video_id}/final_video.mp4")

    for clip in clips:
        clip.close()
        os.remove(clip.filename)
    os.remove(final_video_path)

    return "video uploaded"

In [10]:
import boto3
import json
from botocore.exceptions import ClientError


s3 = boto3.client('s3', aws_access_key_id="AKIAUJXLE2HEOGWEMCEX",aws_secret_access_key="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",region_name='eu-west-1')


try:
    response = s3.get_object(Bucket='soulchain-dev1-output-video', Key='video_info.json')

    data = json.loads(response['Body'].read())
except ClientError as e:
    if e.response['Error']['Code'] == 'NoSuchKey':
        data = []
    else:
        raise
video = next((v for v in data if v["video_id"] == video_id), None)
part = next((p for p in video["video_parts"] if p["key"] == key), None)

In [12]:
part["media_key"]

'datalake_media/image-blueberries-2278921_150.jpg-c614eef5-de47-4dc1-ae11-5cbc7affe015'

In [9]:
video["video_parts"]

[{'key': 1,
  'duration': 4.68,
  'media_key': 'datalake_media/image-blueberries-2278921_150.jpg-c614eef5-de47-4dc1-ae11-5cbc7affe015',
  'audio_key': 'generated_videos/video2/audio1',
  'text': 'Nutrition is the foundation of a healthy life.',
  'video_part_key': 'generated_videos/video2/video2_part_1.mp4'},
 {'key': 2,
  'duration': 5.52,
  'media_key': 'datalake_media/image-salad-2756467_150.jpg-9bd9506d-09c8-4b9e-a0d4-e40ce3441d75',
  'audio_key': 'generated_videos/video2/audio2',
  'text': 'Balanced diets fuel our bodies, providing essential energy.',
  'video_part_key': 'generated_videos/video2/video2_part_2.mp4'},
 {'key': 3,
  'duration': 4.27,
  'media_key': 'datalake_media/image-fat-foods-1487599_150.jpg-57ff722f-e70d-4e61-ad07-74cedffa082f',
  'audio_key': 'generated_videos/video2/audio3',
  'text': 'Healthy fats support our brains.',
  'video_part_key': 'generated_videos/video2/video2_part_3.mp4'},
 {'key': 4,
  'duration': 5.85,
  'media_key': 'datalake_media/image-harmful-food-1803600_150.jpg-3bec5f5c-9ede-4dbd-a8d9-7e9599fa5c61',
  'audio_key': 'generated_videos/video2/audio4',
  'text': 'Processed foods harm, so choose wisely.',
  'video_part_key': 'generated_videos/video2/video2_part_4.mp4'},
 {'key': 5,
  'duration': 6.22,
  'media_key': 'datalake_media/image-smoothie-3697014_150.jpg-d9eff9fe-a149-45fa-b425-958bb53d5640',
  'audio_key': 'generated_videos/video2/audio5',
  'text': "Embrace the power of good nutrition—it's your key to a vibrant, happy life.",
  'video_part_key': 'generated_videos/video2/video2_part_5.mp4'}]

In [1]:
video = {
    'tags': 'music, entertainment, pop culture'
}

# Split the string into a list of keywords
keywords = video['tags'].split(', ')
first_keyword = keywords[0]

In [2]:
first_keyword

'music'

In [12]:
import requests
from langdetect import detect
import json
from text import get_argos
import boto3


def def_translation(sentence, lang):
    original_lang = detect(sentence)
    original_lang = get_argos(original_lang)
    print(original_lang)
    
    subtitles = sentence 
    
    if lang != original_lang and lang != "None":
        url_translation = "http://127.0.0.1:5003/translate"
        data = {
            "text": sentence,
            "source": original_lang,
            "target": lang
        }
        print("data:", data)
        response = requests.post(url_translation, json=data)
        subtitles = response.text  # Update subtitles with the translated text
        
    return subtitles

def def_change_translation(s3,video_id, lang):

    try:
        response = s3.get_object(Bucket='soulchain-dev1-output-video', Key='video_info.json')
        data = json.loads(response['Body'].read())
    except ClientError as e:
        if e.response['Error']['Code'] == 'NoSuchKey':
            data = []
        else:
            raise  

    video = next((v for v in data if v["video_id"] == video_id), None)
    all_keys = []
    if video and "video_parts" in video:
        all_keys = [part['key'] for part in video['video_parts']]

    if video:
        for key in all_keys:
            part = next((p for p in video["video_parts"] if p["key"] == key), None)
            if part:
                part["subtitles"] = def_translation(part["text"],lang)
    try:
        data = json.dumps(data)
        s3.put_object(Bucket='soulchain-dev1-output-video', Key=f"video_info.json", Body=data)
        print("JSON file successfully updated.")
    except Exception as e:
        print(f"Error while saving the JSON file: {e}")


s3 = boto3.client('s3', aws_access_key_id="AKIAUJXLE2HEOGWEMCEX",aws_secret_access_key="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",region_name='eu-west-1')

def_change_translation(s3,"video4000","Spanish")

English
data: {'text': "Nature's tranquility envelops us, with whispering trees and singing birds.", 'source': 'English', 'target': 'Spanish'}
English
data: {'text': 'Rivers flow gently, sunlight paints warmth, and flowers bloom vibrantly.', 'source': 'English', 'target': 'Spanish'}
English
data: {'text': 'Majestic mountains reach for the sky, while stars twinkle overhead.', 'source': 'English', 'target': 'Spanish'}
English
data: {'text': "In nature's embrace, peace reigns, offering a timeless sanctuary for all.", 'source': 'English', 'target': 'Spanish'}
JSON file successfully updated.

In [13]:
pip install flask-cors

Defaulting to user installation because normal site-packages is not writeable
Collecting flask-cors
  Downloading Flask_Cors-4.0.1-py2.py3-none-any.whl.metadata (5.5 kB)
Requirement already satisfied: Flask>=0.9 in /Users/fatimaezzahrasounnyslitine/Library/Python/3.9/lib/python/site-packages (from flask-cors) (3.0.2)
Requirement already satisfied: Werkzeug>=3.0.0 in /Users/fatimaezzahrasounnyslitine/Library/Python/3.9/lib/python/site-packages (from Flask>=0.9->flask-cors) (3.0.1)
Requirement already satisfied: Jinja2>=3.1.2 in /Users/fatimaezzahrasounnyslitine/Library/Python/3.9/lib/python/site-packages (from Flask>=0.9->flask-cors) (3.1.3)
Requirement already satisfied: itsdangerous>=2.1.2 in /Users/fatimaezzahrasounnyslitine/Library/Python/3.9/lib/python/site-packages (from Flask>=0.9->flask-cors) (2.1.2)
Requirement already satisfied: click>=8.1.3 in /Users/fatimaezzahrasounnyslitine/Library/Python/3.9/lib/python/site-packages (from Flask>=0.9->flask-cors) (8.1.7)
Requirement already satisfied: blinker>=1.6.2 in /Users/fatimaezzahrasounnyslitine/Library/Python/3.9/lib/python/site-packages (from Flask>=0.9->flask-cors) (1.7.0)
Requirement already satisfied: importlib-metadata>=3.6.0 in /Users/fatimaezzahrasounnyslitine/Library/Python/3.9/lib/python/site-packages (from Flask>=0.9->flask-cors) (7.0.1)
Requirement already satisfied: zipp>=0.5 in /Users/fatimaezzahrasounnyslitine/Library/Python/3.9/lib/python/site-packages (from importlib-metadata>=3.6.0->Flask>=0.9->flask-cors) (3.17.0)
Requirement already satisfied: MarkupSafe>=2.0 in /Users/fatimaezzahrasounnyslitine/Library/Python/3.9/lib/python/site-packages (from Jinja2>=3.1.2->Flask>=0.9->flask-cors) (2.1.5)
Downloading Flask_Cors-4.0.1-py2.py3-none-any.whl (14 kB)
Installing collected packages: flask-cors
Successfully installed flask-cors-4.0.1
Note: you may need to restart the kernel to use updated packages.

In [4]:
import pkg_resources

try:
    version = pkg_resources.get_distribution("elevenlabs").version
    print("Eleven Labs version:", version)
except pkg_resources.DistributionNotFound:
    print("Eleven Labs is not installed.")

Eleven Labs version: 0.2.27

/var/folders/ys/s5c8y6vx2n95hnjtr5vs5h000000gn/T/ipykernel_2087/3920807979.py:1: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources

In [6]:
def get_scene(s3):
    try:
        response = s3.get_object(Bucket='soulchain-dev1-output-video', Key='video_info.json')
        data = json.loads(response['Body'].read())
    except ClientError as e:
        if e.response['Error']['Code'] == 'NoSuchKey':
            data = []
        else:
            raise  

    return data

In [7]:
get_scene(s3)

{'video_id': 'video70',
 'user_id': 'user7',
 'date_created': '2024-05-13T15:24:19.578265',
 'video_key': 'generated_videos/video70/final_video.mp4',
 'video_type': 'image',
 'video_parts': [{'key': 1,
   'duration': 2.74,
   'media_key': 'datalake_media/image-bread-2796393_150.jpg-1b0ffe96-fbec-4bc3-9c6d-0e43965b52a7',
   'audio_key': 'generated_videos/video70/audio1',
   'text': 'Wondering how protein impacts blood sugar levels?',
   'subtitles': 'Vous vous demandez comment les protéines affectent le taux de sucre dans le sang?',
   'video_part_key': 'generated_videos/video70/video70_part_1.mp4'},
  {'key': 2,
   'duration': 4.5,
   'media_key': 'datalake_media/your_new_image.jpg',
   'audio_key': 'generated_videos/video70/audio_new',
   'text': 'Your new text',
   'subtitles': 'Your new subtitles',
   'video_part_key': 'generated_videos/video70/video70_part_new.mp4'},
  {'key': 4,
   'duration': 6.12,
   'media_key': 'datalake_media/image-diabetes-1724617_150.jpg-8344c298-2de3-40f7-a4b1-bdb1abfc1a06',
   'audio_key': 'generated_videos/video70/audio3',
   'text': 'When you consume protein',
   'subtitles': 'Lorsque vous consommez des protéines',
   'video_part_key': 'generated_videos/video70/video70_part_3.mp4'},
  {'key': 5,
   'duration': 10.190000000000001,
   'media_key': 'datalake_media/image-insulin-2110059_150.jpg-3f7f5053-6446-4a0c-b690-8fbd96572eac',
   'audio_key': 'generated_videos/video70/audio4',
   'text': ' it doesn’t just fill you up—it also triggers an insulin response that helps moderate blood sugar spikes.',
   'subtitles': "Il ne se contente pas de vous remplir — il déclenche également une réponse à l'insuline qui aide à modérées pics de sucre dans le sang.",
   'video_part_key': 'generated_videos/video70/video70_part_4.mp4'}]}

In [22]:
def add_scene(s3, video_id, new_scene):
    try:
        response = s3.get_object(Bucket='soulchain-dev1-output-video', Key='video_info.json')
        data = json.loads(response['Body'].read())
    except ClientError as e:
        if e.response['Error']['Code'] == 'NoSuchKey':
            data = []
        else:
            raise

    video = next((v for v in data if v["video_id"] == video_id), None)

    if video:
        video_parts = video.get("video_parts", [])
        video_parts.insert(1, new_scene)

        for i in range(2, len(video_parts)):
            video_parts[i]["key"] += 1
            video_parts[i]["duration"] += new_scene["duration"]

        video["video_parts"] = video_parts

        try:
            data = json.dumps(data)
            s3.put_object(Bucket='soulchain-dev1-output-video', Key='video_info.json', Body=data)
            print("JSON file successfully updated.")
        except Exception as e:
            print(f"Error while saving the JSON file: {e}")
    else:
        print(f"No video found with ID: {video_id}")

In [8]:
import boto3
from botocore.exceptions import ClientError
import json
s3 = boto3.client('s3', aws_access_key_id="AKIAUJXLE2HEOGWEMCEX",aws_secret_access_key="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",region_name='eu-west-1')


new_scene = {
        "key": 2,
        "duration": 4.5,  # New scene duration
        "media_key": "datalake_media/your_new_image.jpg",
        "audio_key": "generated_videos/video70/audio_new",
        "text": "Your new text",
        "subtitles": "Your new subtitles",
        "video_part_key": "generated_videos/video70/video70_part_new.mp4"
    }
#delete_scene(s3,"video70",2)

delete_scene(s3,"video70",2)

In [32]:
import boto3
s3 = boto3.client('s3', aws_access_key_id="AKIAUJXLE2HEOGWEMCEX",aws_secret_access_key="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")

s3.delete_object(Bucket='soulchain-dev1-output-video', Key="generated_videos/video70/video70_part_22.mp4")

ClientError: An error occurred (AccessDenied) when calling the DeleteObject operation: Access Denied

In [18]:
#s3.delete_object(Bucket='soulchain-dev1-output-video', Key='generated_videos/video70/video70_part_2.mp4')
# s3.copy_object(
#             Bucket="soulchain-dev1-output-video",
#             CopySource={'Bucket': "soulchain-dev1-output-video", 'Key': "generated_videos/video70/video70_part_2.mp4"},
#             Key="generated_videos/video70/video70_part_22.mp4"
#         )


s3.copy_object(
            Bucket="soulchain-dev1-output-video",
            CopySource={'Bucket': "soulchain-dev1-output-video", 'Key': "generated_videos/video70/video70_part_22.mp4"},
            Key="generated_videos/video70/video70_part_222.mp4",
            MetadataDirective='REPLACE'
        )
        
# Set up a redirect from the old object to the new one
s3.put_object(
    Bucket="soulchain-dev1-output-video",
    Key="generated_videos/video70/video70_part_22.mp4",
    WebsiteRedirectLocation=f'/soulchain-dev1-output-video/generated_videos/video70/video70_part_222.mp4'
)

{'ResponseMetadata': {'RequestId': 'RRYGCR0QA5FJAFR6',
  'HostId': 'm7H7l2GY8BcdsECHcCD/qi2mI8GZpnrXS+z1NP06iQtl2v/yNJfOfdDmhSobz9qHoIT1xTrwDnM=',
  'HTTPStatusCode': 200,
  'HTTPHeaders': {'x-amz-id-2': 'm7H7l2GY8BcdsECHcCD/qi2mI8GZpnrXS+z1NP06iQtl2v/yNJfOfdDmhSobz9qHoIT1xTrwDnM=',
   'x-amz-request-id': 'RRYGCR0QA5FJAFR6',
   'date': 'Thu, 16 May 2024 14:56:27 GMT',
   'x-amz-server-side-encryption': 'AES256',
   'etag': '"d41d8cd98f00b204e9800998ecf8427e"',
   'server': 'AmazonS3',
   'content-length': '0'},
  'RetryAttempts': 0},
 'ETag': '"d41d8cd98f00b204e9800998ecf8427e"',
 'ServerSideEncryption': 'AES256'}

In [22]:
# s3 = boto3.client('s3', aws_access_key_id="AKIAUJXLE2HEOGWEMCEX",aws_secret_access_key="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")

# try:
#     response = s3.get_object(Bucket='soulchain-dev1-output-video', Key='video_info.json')
#     data = json.loads(response['Body'].read())
# except ClientError as e:
#     if e.response['Error']['Code'] == 'NoSuchKey':
#         data = []
#     else:
#         raise  

data=[{"video_id": "video7000", "user_id": "user700", "date_created": "2024-05-15T11:30:49.930907", "video_key": "generated_videos/video7000/final_video.mp4", "video_type": "image", "video_parts": [{"key": 1, "duration": 2.77, "media_key": "datalake_media/image-digital-marketing-1725340_150.jpg-785e05fd-a610-4695-bc63-a660b1899a81", "audio_key": "generated_videos/video7000/audio1", "text": "Wondering how protein impacts blood sugar levels?", "subtitles": "Wondering how protein impacts blood sugar levels?", "video_part_key": "generated_videos/video7000/video7000_part_1.mp4"}]}, {"video_id": "video7000", "user_id": "user700", "date_created": "2024-05-15T11:56:49.517180", "video_key": "generated_videos/video7000/final_video.mp4", "video_type": "image", "video_parts": [{"key": 1, "duration": 2.82, "media_key": "datalake_media/image-bread-2796393_150.jpg-1b0ffe96-fbec-4bc3-9c6d-0e43965b52a7", "audio_key": "generated_videos/video7000/audio1", "text": "Wondering how protein impacts blood sugar levels?", "subtitles": "Wondering how protein impacts blood sugar levels?", "video_part_key": "generated_videos/video7000/video7000_part_1.mp4"}]}]

try:
    data = json.dumps(data)
    s3.put_object(Bucket='soulchain-dev1-output-video', Key='video_info.json', Body=data)
    print("JSON file successfully updated.")
except Exception as e:
    print(f"Error while saving the JSON file: {e}")

JSON file successfully updated.

In [21]:
video

{'video_id': 'video7000',
 'user_id': 'user700',
 'date_created': '2024-05-15T11:30:49.930907',
 'video_key': 'generated_videos/video7000/final_video.mp4',
 'video_type': 'image',
 'video_parts': [{'key': 1,
   'duration': 2.77,
   'media_key': 'datalake_media/image-digital-marketing-1725340_150.jpg-785e05fd-a610-4695-bc63-a660b1899a81',
   'audio_key': 'generated_videos/video7000/audio1',
   'text': 'Wondering how protein impacts blood sugar levels?',
   'subtitles': 'Wondering how protein impacts blood sugar levels?',
   'video_part_key': 'generated_videos/video7000/video7000_part_1.mp4'}]}

In [3]:
import pandas as pd
metadata=pd.read_excel("metadata.xlsx")

In [4]:
def find_image_for_term(term, processed_terms, processed_image_paths, metadata, image_folder):

    topic_found = False
    image_found = False
    image_name = None
    metadata = metadata.dropna(subset=['keywords_description'])
    new_metadata = metadata[~metadata['path_datalake'].isin(processed_image_paths)]
    url_datalake_path = None 

    if term not in processed_terms:
        for idx, meta_row in new_metadata.iterrows():
            main_topic_stemmed = meta_row['main_topic']  # Assuming main_topic is a list of stemmed words
            # Check for exact match
            main_topic_list = eval(main_topic_stemmed)
            if term in main_topic_list:  
                image_name = meta_row['name']
                url_datalake_path = meta_row['path_datalake'] 
                if url_datalake_path is not None:
                    processed_terms.add(term)
                    topic_found = True
                    image_found = True
                break

    return topic_found, image_found, image_name, url_datalake_path

In [29]:
topic_found, image_found, image_name, url_datalake_path=find_image_for_term("nutrition",set(),set(),metadata,"data")

In [21]:
import pandas as pd

In [31]:
df=pd.read_csv("unsplash_metadata.csv")
df.to_excel('unsplash_metadata.xlsx', index=False)

FileNotFoundError: [Errno 2] No such file or directory: 'unsplash_metadata.csv'

In [11]:
df["count_edit"]=0

In [100]:
import pandas as pd
df1=pd.read_excel("metadata_video_1772_rest.xlsx")
df2=pd.read_excel("metadata_video_1772.xlsx")

In [101]:
df=pd.concat([df1, df2])

In [102]:
df=df.drop(columns=["Unnamed: 0.1","Unnamed: 0"])

In [103]:
df['new_description'] = df['new_description'].fillna(df['description'])

In [104]:
import spacy
import pandas as pd

# Load the pre-trained spaCy model
nlp = spacy.load("en_core_web_sm")

# Define a set of stopwords
stopwords = ["video", "body"]

# Function to extract unique nouns excluding stopwords
def extract_nouns(text):
    doc = nlp(text)
    keywords = {token.text.lower() for token in doc if token.pos_ == "NOUN" and token.text.lower() not in stopwords}
    return list(keywords)


# Apply the function to the DataFrame
df['new_keywords'] = df['new_description'].apply(extract_nouns)

In [105]:
df

,name,keywords,url,type,term,path_datalake,description,keywords_description,source,size,count_usage,count_edit,media_state,new_description,entities,new_keywords
0,Boxer bleeding after a fight,"['""medium shot""', '""sport""', '""athlete""', '""tr...",https://assets.mixkit.co/videos/preview/mixkit...,video,sport,datalake_media/video-sport-48b6b38b-d2c6-47b2-...,Injured and bleeding boxer sitting in a corner...,"['boxer', 'injured', 'sitting', 'ring', 'bleed...",mixkit,horizontal,0,0,useful,Injured and bleeding boxer sitting in a corner...,NaN,"[ring, corner, boxer, fight]"
1,Boxer training with a punching bag at the gym,"['""medium shot""', '""man""', '""sport""', '""traini...",https://assets.mixkit.co/videos/preview/mixkit...,video,sport,datalake_media/video-sport-33284849-7689-4467-...,Amateur shirtless boxer training wearing boxin...,"['boxing', 'boxer', 'gym', 'training', 'gloves']",mixkit,horizontal,0,0,useful,A video of a man punching a heavy bag in a gym...,"[('a man', (11, 16), [(0.265625, 0.109375, 0.7...","[man, punch, boxer, bag, gym, boxing]"
2,Fencer fighting with sword in hand,"['""sport""', '""training""', '""athlete""', '""sword""']",https://assets.mixkit.co/videos/preview/mixkit...,video,sport,datalake_media/video-sport-6420ae0b-3ea8-45ce-...,NaN,[],mixkit,horizontal,0,0,useful,A video of a woman in white fencing costume an...,"[('white fencing costume', (22, 43), [(0.42187...","[woman, sword, costume, studio, mask, fencing]"
3,Boy skiing on the snow,"['""forest""', '""sport""', '""snow""', '""full shot""...",https://assets.mixkit.co/videos/preview/mixkit...,video,sport,datalake_media/video-sport-5cfeb9fd-5ca2-4550-...,"Boy skiing on the snow, seen up close during s...","['skiing', 'snow', 'sunrise', 'pine', 'trees']",mixkit,horizontal,0,0,useful,A video of a skier watching the sunset A video...,"[('a skier', (11, 18), [(0.140625, 0.015625, 0...","[skiing, skier, sunset, boy, child]"
4,Near the limit at the top of a snowy mountain,"['""man""', '""landscape""', '""sport""', '""snow""', ...",https://assets.mixkit.co/videos/preview/mixkit...,video,sport,datalake_media/video-sport-c1fc6116-17f9-42a1-...,Skier walking near the edge at the top of a sn...,"['skier', 'clouds', 'abyss', 'snowy', 'mountain']",mixkit,horizontal,0,0,useful,A video of a skier and snowboarder walking up ...,"[('a skier', (11, 18), [(0.578125, 0.515625, 0...","[trees, man, pine, background, snowboarder, sk..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1767,Man skillfully practicing pirouettes in a park,"['""sport""', '""medium shot wide""', '""exercise""'...",https://assets.mixkit.co/videos/preview/mixkit...,video,sport,datalake_media/video-sport-c11ecf93-f073-4aab-...,Two cheerleader guys lifting a girl upside dow...,"['lifting', 'cheerleader', 'workout', 'pyramid...",mixkit,vertical,0,0,useful,A video of a woman doing a squat with a traine...,"[('a woman', (11, 18), [(0.265625, 0.171875, 0...","[squat, park, man, trainer, woman, handstand, ..."
1768,Cheerleader girl in pose on top of a pyramid,"['""sport""', '""exercise""', '""low angle shot""', ...",https://assets.mixkit.co/videos/preview/mixkit...,video,sport,datalake_media/video-sport-dee6dd45-e368-40cd-...,"Cheerleader girl in pose, raising her arms on ...","['cheerleader', 'pose', 'pyramid', 'girl', 'ra...",mixkit,vertical,0,0,useful,A video of a woman jumping in the air A video ...,"[('a woman', (11, 18), [(0.015625, 0.046875, 0...","[air, woman]"
1769,Cheerleader boy lifting a girl on his hands,"['""sport""', '""slow motion""', '""exercise""', '""t...",https://assets.mixkit.co/videos/preview/mixkit...,video,sport,datalake_media/video-sport-d3a0fcb8-e665-4c73-...,Cheerleader man lifts a girl to carry her stan...,"['cheerleader', 'lifts', 'girl', 'workout', 'c...",mixkit,vertical,0,0,useful,A video of a man and a woman on a tennis court...,"[('a man', (11, 16), [(0.265625, 0.515625, 0.7...","[expression, tennis, park, man, court, waist, ..."
1770,Cheerleaders throwing a girl into the air at a...,"['""sport""', '""medium shot wide""', '""exercise""'...",https://assets.mixkit.co/videos/preview/mixkit...,video,sport,datalake_media/video-sport-807c3dc2-f9e7-45ce-...,Cheerleading team throwing a girl who takes a ...,"['cheerleading', 'throwing', 'spin', 'girl', '...",mixkit,horizontal,0,0,useful,A video of a group of young men playing basket...,"[('young men', (22, 31), [(0.546875, 0.515625,...","[ground, basketball, group, man, court, tightr..."
1771,Point of view fighting in a ring against a woman,"['""sport""', '""women""', '""sports""', '""fight""', ...",https://assets.mixkit.co/videos/preview/mixkit...,video,sport,datalake_media/video-sport-58ae574d-449a-4265-...,Point of view during an intense mixed martial ...,"['punches', 'martial', 'woman', 'match', 'ring']",mixkit,horizontal,0,0,useful,A video of a female boxer throwing a punch in ...,"[('a female boxer', (11, 25), [(0.421875, 0.01...","[neon, police, man, punch, ring, nightclub, bo..."

In [108]:

df['keywords'] = df['keywords'].apply(eval)
df['keywords_description'] = df['keywords_description'].apply(eval)

TypeError: eval() arg 1 must be a string, bytes or code object

In [109]:
df.head()

,name,keywords,url,type,term,path_datalake,description,keywords_description,source,size,count_usage,count_edit,media_state,new_description,entities,new_keywords
0,Boxer bleeding after a fight,"[""medium shot"", ""sport"", ""athlete"", ""train"", ""...",https://assets.mixkit.co/videos/preview/mixkit...,video,sport,datalake_media/video-sport-48b6b38b-d2c6-47b2-...,Injured and bleeding boxer sitting in a corner...,"[boxer, injured, sitting, ring, bleeding]",mixkit,horizontal,0,0,useful,Injured and bleeding boxer sitting in a corner...,NaN,"[ring, corner, boxer, fight]"
1,Boxer training with a punching bag at the gym,"[""medium shot"", ""man"", ""sport"", ""training"", ""a...",https://assets.mixkit.co/videos/preview/mixkit...,video,sport,datalake_media/video-sport-33284849-7689-4467-...,Amateur shirtless boxer training wearing boxin...,"[boxing, boxer, gym, training, gloves]",mixkit,horizontal,0,0,useful,A video of a man punching a heavy bag in a gym...,"[('a man', (11, 16), [(0.265625, 0.109375, 0.7...","[man, punch, boxer, bag, gym, boxing]"
2,Fencer fighting with sword in hand,"[""sport"", ""training"", ""athlete"", ""sword""]",https://assets.mixkit.co/videos/preview/mixkit...,video,sport,datalake_media/video-sport-6420ae0b-3ea8-45ce-...,NaN,[],mixkit,horizontal,0,0,useful,A video of a woman in white fencing costume an...,"[('white fencing costume', (22, 43), [(0.42187...","[woman, sword, costume, studio, mask, fencing]"
3,Boy skiing on the snow,"[""forest"", ""sport"", ""snow"", ""full shot"", ""girl...",https://assets.mixkit.co/videos/preview/mixkit...,video,sport,datalake_media/video-sport-5cfeb9fd-5ca2-4550-...,"Boy skiing on the snow, seen up close during s...","[skiing, snow, sunrise, pine, trees]",mixkit,horizontal,0,0,useful,A video of a skier watching the sunset A video...,"[('a skier', (11, 18), [(0.140625, 0.015625, 0...","[skiing, skier, sunset, boy, child]"
4,Near the limit at the top of a snowy mountain,"[""man"", ""landscape"", ""sport"", ""snow"", ""full sh...",https://assets.mixkit.co/videos/preview/mixkit...,video,sport,datalake_media/video-sport-c1fc6116-17f9-42a1-...,Skier walking near the edge at the top of a sn...,"[skier, clouds, abyss, snowy, mountain]",mixkit,horizontal,0,0,useful,A video of a skier and snowboarder walking up ...,"[('a skier', (11, 18), [(0.578125, 0.515625, 0...","[trees, man, pine, background, snowboarder, sk..."

In [121]:
import pandas as pd
from nltk.stem import PorterStemmer

stemmer = PorterStemmer()

# Function to normalize keywords
def normalize_keywords(keywords):
    normalized_keywords = []
    for word in keywords:
        # Remove quotes and stem the word
        normalized_word = stemmer.stem(word.strip('"').lower())
        normalized_keywords.append(normalized_word)
    return normalized_keywords

# Apply normalization function to 'keywords' column
df['keywords'] = df['keywords'].apply(normalize_keywords)

In [120]:
#df["keywords"] = df["keywords"].astype(str)
df["keywords"][1:2].tolist()

df['normalized_keywords'][1:2].tolist()

[['medium shot',
  'man',
  'sport',
  'train',
  'athlet',
  'fight',
  'box',
  'box',
  'effort',
  'shirtless']]

In [123]:
df=df.drop(columns=["normalized_keywords"])

In [117]:
df["keywords_description"][1:2].tolist()

[['boxing', 'boxer', 'gym', 'training', 'gloves']]

In [14]:
import nltk
from nltk.stem import WordNetLemmatizer

# Download WordNet if not already downloaded
nltk.download('wordnet')

# Initialize the WordNet lemmatizer
lemmatizer = WordNetLemmatizer()

# Function to lemmatize a list of words
def lemmatize_words(words):
    return [lemmatizer.lemmatize(word) for word in words]

# # Assuming df['new_keywords'] contains lists of words, apply lemmatization
df['new_keywords'] = df['new_keywords'].apply(lemmatize_words)

[nltk_data] Downloading package wordnet to
[nltk_data]     /Users/fatimaezzahrasounnyslitine/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

In [132]:
df3=pd.read_excel("new_metadata_mixkit_unsplash_pixabay-3.xlsx")
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12633 entries, 0 to 12632
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   name                  12633 non-null  object
 1   keywords              12633 non-null  object
 2   url                   12633 non-null  object
 3   type                  12633 non-null  object
 4   term                  12631 non-null  object
 5   path_datalake         12633 non-null  object
 6   count_usage           12633 non-null  int64
 7   count_edit            12633 non-null  int64
 8   media_state           12633 non-null  object
 9   description           12563 non-null  object
 10  keywords_description  12633 non-null  object
 11  topic_name            2 non-null      object
 12  main_topic            2 non-null      object
 13  source                12633 non-null  object
 14  Unnamed: 0            12631 non-null  float64
 15  size                  12631 non-null  object
 16  new_description       12631 non-null  object
 17  entities              12631 non-null  object
 18  new_keywords          12631 non-null  object
 19  most_frequent_words   12631 non-null  object
dtypes: float64(1), int64(2), object(17)
memory usage: 1.9+ MB

In [129]:
df4=pd.concat([df3, df])

In [134]:
df3=df3.drop(columns=["topic_name","Unnamed: 0","main_topic"])

In [135]:
df3

,name,keywords,url,type,term,path_datalake,count_usage,count_edit,media_state,description,keywords_description,source,size,new_description,entities,new_keywords,most_frequent_words
0,21617-319452308_large.mp4,"['blood', 'medicine', 'blood cells']",https://cdn.pixabay.com/video/2019/02/23/21617...,video,health,datalake_media/video-21617-319452308_large.mp4...,1,0,useful,NaN,[],pixabay,NaN,NaN,NaN,NaN,NaN
1,8449-209292163_large.mp4,"['heart', 'heartbeat', 'slow heart']",https://cdn.pixabay.com/video/2017/03/20/8449-...,video,health,datalake_media/video-8449-209292163_large.mp4-...,0,0,useful,NaN,[],pixabay,NaN,NaN,NaN,NaN,NaN
2,bygTaBey1Xk.jpg,"['grass', 'shore', 'ocean', 'coast', 'beach', ...",https://images.unsplash.com/uploads/1413387620...,image,grass,datalake_media/image-bygTaBey1Xk.jpg-c8c7df3c-...,0,0,useful,sea and rock cliff with grasses under cloudy sky,"['cliff', 'grasses', 'cloudy', 'sky', 'rock']",unsplash,horizontal,An image of the sea and cliffs in Scotland,"[('the sea', (12, 19), [(0.015625, 0.296875, 0...","['sea', 'cliff']","['sea', 'cliff']"
3,gXSFnk2a9V4.jpg,"['blue', 'holiday', 'geographical feature', 'a...",https://images.unsplash.com/reserve/jEs6K0y1Sb...,image,blue,datalake_media/image-gXSFnk2a9V4.jpg-a0496092-...,0,0,useful,aerial photography of seashore,"['seashore', 'aerial', 'photography']",unsplash,vertical,An image of a beach and ocean from a hill,"[('a beach', (12, 19), [(0.015625, 0.578125, 0...","['beach', 'ocean', 'hill']","['beach', 'ocean', 'hill']"
4,grg6-DNJuaU.jpg,"['sea', 'jump', 'waves', 'summer', 'holiday', ...",https://images.unsplash.com/uploads/1412192004...,image,sea,datalake_media/image-grg6-DNJuaU.jpg-c2b853ee-...,0,0,useful,man surfboarding on ocean wave during daytime,"['surfboarding', 'ocean', 'wave', 'daytime', '...",unsplash,horizontal,An image of a surfer catching a wave and a man...,"[('a surfer', (12, 20), [(0.515625, 0.140625, ...","['surfer', 'wave', 'man', 'water']","['surfer', 'wave', 'man', 'water']"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12628,father-3871837_150.jpg,"['father', 'daughter', 'piggyback']",https://pixabay.com/get/g296ea0740891441347970...,image,father,datalake_media/image-father-3871837_150.jpg-0f...,0,0,useful,,[],pixabay,horizontal,An image of a father giving his daughter a pig...,"[('a father', (12, 20), [(0.390625, 0.109375, ...","['father', 'daughter', 'piggyback', 'ride', 'f...","['father', 'daughter', 'piggyback', 'ride', 'f..."
12629,mother-429158_150.jpg,"['mother', 'daughter', 'sunset']",https://pixabay.com/get/gdae8fafd1494228179ad8...,image,mother,datalake_media/image-mother-429158_150.jpg-b0e...,0,0,useful,,[],pixabay,horizontal,An image of a mother and son playing on the be...,"[('a mother', (12, 20), [(0.109375, 0.296875, ...","['mother', 'son', 'beach', 'sunset']","['mother', 'sunset', 'daughter', 'son', 'beach']"
12630,grapes-3555214_150.jpg,"['grapes', 'fruit', 'immature']",https://pixabay.com/get/ga3b3c3721572917afb7ce...,image,fruits,datalake_media/image-grapes-3555214_150.jpg-c4...,0,0,useful,,[],pixabay,horizontal,An image of a nice grape cluster,"[('a nice grape cluster', (12, 32), [(0.015625...","['grape', 'cluster']","['grape', 'fruit', 'immature', 'cluster']"
12631,house-7497001_150.png,"['house', 'doodle', 'building']",https://pixabay.com/get/g8664cddba4f5a00d6000f...,image,home,datalake_media/image-house-7497001_150.png-f88...,0,0,useful,,[],pixabay,horizontal,An image of a row of houses in a neighborhood,"[('a row of houses in a neighborhood', (12, 45...","['row', 'house', 'neighborhood']","['house', 'doodle', 'building', 'row', 'neighb..."
12632,salad-2756467_150.jpg,"['salad', 'fruit', 'berry']",https://pixabay.com/get/g6503ae4d75c69f3b64973...,image,food,datalake_media/image-salad-2756467_150.jpg-bfd...,0,0,useful,,[],pixabay,horizontal,An image of a salad and various fruits and veg...,"[('a salad', (12, 19), [(0.203125, 0.140625, 0...","['fruit', 'vegetable']","['fruit', 'salad', 'berry', 'vegetable']"

In [136]:
import pandas as pd
from collections import Counter
from ast import literal_eval
import nltk
from nltk.stem import WordNetLemmatizer

def lemmatize_words(words):
    return [lemmatizer.lemmatize(word) for word in words]

def process_keywords(row):
    if row["source"]=="pixabay":
        all_keywords = row['keywords'] + row['new_keywords']
    if row["source"]=="unsplash":
        all_keywords = row['new_keywords']
    else :
        all_keywords = row['keywords'] + row['keywords_description'] + row['new_keywords']

    normalized_keywords = lemmatize_words(all_keywords)
    word_counts = Counter(normalized_keywords)
    most_common_words = word_counts.most_common(5) 
    most_common_words_only = [word for word, _ in most_common_words]
    
    new_keywords_set = set(row['new_keywords'])
    current_most_common_set = set(most_common_words_only)
    missing_words = new_keywords_set - current_most_common_set
    
    if missing_words:
        most_common_words_only.extend(missing_words)
    
    return most_common_words_only

# Apply the function to each row
df['most_frequent_words'] = df.apply(process_keywords, axis=1)

In [138]:
df4=pd.concat([df3, df])

In [139]:
df4

,name,keywords,url,type,term,path_datalake,count_usage,count_edit,media_state,description,keywords_description,source,size,new_description,entities,new_keywords,most_frequent_words
0,21617-319452308_large.mp4,"['blood', 'medicine', 'blood cells']",https://cdn.pixabay.com/video/2019/02/23/21617...,video,health,datalake_media/video-21617-319452308_large.mp4...,1,0,useful,NaN,[],pixabay,NaN,NaN,NaN,NaN,NaN
1,8449-209292163_large.mp4,"['heart', 'heartbeat', 'slow heart']",https://cdn.pixabay.com/video/2017/03/20/8449-...,video,health,datalake_media/video-8449-209292163_large.mp4-...,0,0,useful,NaN,[],pixabay,NaN,NaN,NaN,NaN,NaN
2,bygTaBey1Xk.jpg,"['grass', 'shore', 'ocean', 'coast', 'beach', ...",https://images.unsplash.com/uploads/1413387620...,image,grass,datalake_media/image-bygTaBey1Xk.jpg-c8c7df3c-...,0,0,useful,sea and rock cliff with grasses under cloudy sky,"['cliff', 'grasses', 'cloudy', 'sky', 'rock']",unsplash,horizontal,An image of the sea and cliffs in Scotland,"[('the sea', (12, 19), [(0.015625, 0.296875, 0...","['sea', 'cliff']","['sea', 'cliff']"
3,gXSFnk2a9V4.jpg,"['blue', 'holiday', 'geographical feature', 'a...",https://images.unsplash.com/reserve/jEs6K0y1Sb...,image,blue,datalake_media/image-gXSFnk2a9V4.jpg-a0496092-...,0,0,useful,aerial photography of seashore,"['seashore', 'aerial', 'photography']",unsplash,vertical,An image of a beach and ocean from a hill,"[('a beach', (12, 19), [(0.015625, 0.578125, 0...","['beach', 'ocean', 'hill']","['beach', 'ocean', 'hill']"
4,grg6-DNJuaU.jpg,"['sea', 'jump', 'waves', 'summer', 'holiday', ...",https://images.unsplash.com/uploads/1412192004...,image,sea,datalake_media/image-grg6-DNJuaU.jpg-c2b853ee-...,0,0,useful,man surfboarding on ocean wave during daytime,"['surfboarding', 'ocean', 'wave', 'daytime', '...",unsplash,horizontal,An image of a surfer catching a wave and a man...,"[('a surfer', (12, 20), [(0.515625, 0.140625, ...","['surfer', 'wave', 'man', 'water']","['surfer', 'wave', 'man', 'water']"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1767,Man skillfully practicing pirouettes in a park,"[sport, medium shot wid, exercis, athlet, spor...",https://assets.mixkit.co/videos/preview/mixkit...,video,sport,datalake_media/video-sport-c11ecf93-f073-4aab-...,0,0,useful,Two cheerleader guys lifting a girl upside dow...,"[lifting, cheerleader, workout, pyramid, upside]",mixkit,vertical,A video of a woman doing a squat with a traine...,"[('a woman', (11, 18), [(0.265625, 0.171875, 0...","[squat, park, man, trainer, woman, handstand, ...","[sport, medium shot wid, exercis, athlet, team..."
1768,Cheerleader girl in pose on top of a pyramid,"[sport, exercis, low angle shot, athlet, sport...",https://assets.mixkit.co/videos/preview/mixkit...,video,sport,datalake_media/video-sport-dee6dd45-e368-40cd-...,0,0,useful,"Cheerleader girl in pose, raising her arms on ...","[cheerleader, pose, pyramid, girl, raising]",mixkit,vertical,A video of a woman jumping in the air A video ...,"[('a woman', (11, 18), [(0.015625, 0.046875, 0...","[air, woman]","[sport, exercis, low angle shot, athlet, cheer..."
1769,Cheerleader boy lifting a girl on his hands,"[sport, slow mot, exercis, track, athlet, spor...",https://assets.mixkit.co/videos/preview/mixkit...,video,sport,datalake_media/video-sport-d3a0fcb8-e665-4c73-...,0,0,useful,Cheerleader man lifts a girl to carry her stan...,"[cheerleader, lifts, girl, workout, carry]",mixkit,vertical,A video of a man and a woman on a tennis court...,"[('a man', (11, 16), [(0.265625, 0.515625, 0.7...","[expression, tennis, park, man, court, waist, ...","[sport, slow mot, exercis, track, athlet, expr..."
1770,Cheerleaders throwing a girl into the air at a...,"[sport, medium shot wid, exercis, track, athle...",https://assets.mixkit.co/videos/preview/mixkit...,video,sport,datalake_media/video-sport-807c3dc2-f9e7-45ce-...,0,0,useful,Cheerleading team throwing a girl who takes a ...,"[cheerleading, throwing, spin, girl, practice]",mixkit,horizontal,A video of a group of young men playing basket...,"[('young men', (22, 31), [(0.546875, 0.515625,...","[ground, basketball, group, man, court, tightr...","[sport, medium shot wid, exercis, track, athle..."
1771,Point of view fighting in a ring against a woman,"[sport, women, sport, fight, box, glove, fight...",https://assets.mixkit.co/videos/preview/mixkit...,video,sport,datalake_media/video-sport-58ae574d-449a-4265-...,0,0,useful,Point of view during an intense mixed martial ...,"[punches, martial, woman, match, ring]",mixkit,horizontal,A video of a female boxer throwing a punch in ...,"[('a female boxer', (11, 25), [(0.421875, 0.01...","[neon, police, man, punch, ring, nightclub, bo...","[woman, ring, sport, fight, punch, neon, night..."

In [141]:
import io
from datalake import put_image_in_s3
with io.BytesIO() as buffer:
    df4.to_excel(buffer, index=True)
    buffer.seek(0)
    data_bytes = buffer.read()
    
put_image_in_s3(data_bytes,"soulchain-dev1-output-video", "new_metadata_mixkit_unsplash_pixabay.xlsx")

Media uploaded successfully to S3

In [143]:
from datalake import read_metadata_from_s3
metadata=read_metadata_from_s3("soulchain-dev1-output-video", "new_metadata_mixkit_unsplash_pixabay.xlsx")

In [144]:
metadata

,Unnamed: 0,name,keywords,url,type,term,path_datalake,count_usage,count_edit,media_state,description,keywords_description,source,size,new_description,entities,new_keywords,most_frequent_words
0,0,21617-319452308_large.mp4,"['blood', 'medicine', 'blood cells']",https://cdn.pixabay.com/video/2019/02/23/21617...,video,health,datalake_media/video-21617-319452308_large.mp4...,1,0,useful,NaN,[],pixabay,NaN,NaN,NaN,NaN,NaN
1,1,8449-209292163_large.mp4,"['heart', 'heartbeat', 'slow heart']",https://cdn.pixabay.com/video/2017/03/20/8449-...,video,health,datalake_media/video-8449-209292163_large.mp4-...,0,0,useful,NaN,[],pixabay,NaN,NaN,NaN,NaN,NaN
2,2,bygTaBey1Xk.jpg,"['grass', 'shore', 'ocean', 'coast', 'beach', ...",https://images.unsplash.com/uploads/1413387620...,image,grass,datalake_media/image-bygTaBey1Xk.jpg-c8c7df3c-...,0,0,useful,sea and rock cliff with grasses under cloudy sky,"['cliff', 'grasses', 'cloudy', 'sky', 'rock']",unsplash,horizontal,An image of the sea and cliffs in Scotland,"[('the sea', (12, 19), [(0.015625, 0.296875, 0...","['sea', 'cliff']","['sea', 'cliff']"
3,3,gXSFnk2a9V4.jpg,"['blue', 'holiday', 'geographical feature', 'a...",https://images.unsplash.com/reserve/jEs6K0y1Sb...,image,blue,datalake_media/image-gXSFnk2a9V4.jpg-a0496092-...,0,0,useful,aerial photography of seashore,"['seashore', 'aerial', 'photography']",unsplash,vertical,An image of a beach and ocean from a hill,"[('a beach', (12, 19), [(0.015625, 0.578125, 0...","['beach', 'ocean', 'hill']","['beach', 'ocean', 'hill']"
4,4,grg6-DNJuaU.jpg,"['sea', 'jump', 'waves', 'summer', 'holiday', ...",https://images.unsplash.com/uploads/1412192004...,image,sea,datalake_media/image-grg6-DNJuaU.jpg-c2b853ee-...,0,0,useful,man surfboarding on ocean wave during daytime,"['surfboarding', 'ocean', 'wave', 'daytime', '...",unsplash,horizontal,An image of a surfer catching a wave and a man...,"[('a surfer', (12, 20), [(0.515625, 0.140625, ...","['surfer', 'wave', 'man', 'water']","['surfer', 'wave', 'man', 'water']"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14901,1767,Man skillfully practicing pirouettes in a park,"['sport', 'medium shot wid', 'exercis', 'athle...",https://assets.mixkit.co/videos/preview/mixkit...,video,sport,datalake_media/video-sport-c11ecf93-f073-4aab-...,0,0,useful,Two cheerleader guys lifting a girl upside dow...,"['lifting', 'cheerleader', 'workout', 'pyramid...",mixkit,vertical,A video of a woman doing a squat with a traine...,"[('a woman', (11, 18), [(0.265625, 0.171875, 0...","['squat', 'park', 'man', 'trainer', 'woman', '...","['sport', 'medium shot wid', 'exercis', 'athle..."
14902,1768,Cheerleader girl in pose on top of a pyramid,"['sport', 'exercis', 'low angle shot', 'athlet...",https://assets.mixkit.co/videos/preview/mixkit...,video,sport,datalake_media/video-sport-dee6dd45-e368-40cd-...,0,0,useful,"Cheerleader girl in pose, raising her arms on ...","['cheerleader', 'pose', 'pyramid', 'girl', 'ra...",mixkit,vertical,A video of a woman jumping in the air A video ...,"[('a woman', (11, 18), [(0.015625, 0.046875, 0...","['air', 'woman']","['sport', 'exercis', 'low angle shot', 'athlet..."
14903,1769,Cheerleader boy lifting a girl on his hands,"['sport', 'slow mot', 'exercis', 'track', 'ath...",https://assets.mixkit.co/videos/preview/mixkit...,video,sport,datalake_media/video-sport-d3a0fcb8-e665-4c73-...,0,0,useful,Cheerleader man lifts a girl to carry her stan...,"['cheerleader', 'lifts', 'girl', 'workout', 'c...",mixkit,vertical,A video of a man and a woman on a tennis court...,"[('a man', (11, 16), [(0.265625, 0.515625, 0.7...","['expression', 'tennis', 'park', 'man', 'court...","['sport', 'slow mot', 'exercis', 'track', 'ath..."
14904,1770,Cheerleaders throwing a girl into the air at a...,"['sport', 'medium shot wid', 'exercis', 'track...",https://assets.mixkit.co/videos/preview/mixkit...,video,sport,datalake_media/video-sport-807c3dc2-f9e7-45ce-...,0,0,useful,Cheerleading team throwing a girl who takes a ...,"['cheerleading', 'throwing', 'spin', 'girl', '...",mixkit,horizontal,A video of a group of young men playing basket...,"[('young men', (22, 31), [(0.546875, 0.515625,...","['ground', 'basketball', 'group', 'man', 'cour...","['sport', 'medium shot wid', 'exercis', 'track..."
14905,1771,Point of view fighting in a ring against a woman,"['sport', 'women', 'sport', 'fight', 'box', 'g...",https://assets.mixkit.co/videos/preview/mixkit...,video,sport,datalake_media/video-sport-58ae574d-449a-4265-...,0,0,useful,Point of view during an intense mixed martial ...,"['punches', 'martial', 'woman', 'match', 'ring']",mixkit,horizontal,A video of a female boxer throwing a punch in ...,"[('a female boxer', (11, 25), [(0.421875, 0.01...","['neon', 'police', 'man', 'punch', 'ring', 'ni...","['woman', 'ring', 'sport', 'fight', 'punch', '..."

In [117]:
image_path=metadata['path_datalake'][:1]
image_path=image_path.tolist()
image_path

['datalake_media/image-bygTaBey1Xk.jpg-c8c7df3c-30e9-4ff5-a33e-2f64122101f7']

In [118]:
image_path=["datalake_media/default_image.jpg"]
image_path

['datalake_media/default_image.jpg']

In [121]:
import ast
import pandas as pd
from collections import Counter
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer

# Initialize lemmatizer
lemmatizer = WordNetLemmatizer()

def lemmatize_words(words):
    return [lemmatizer.lemmatize(word) for word in words]

def preprocess_text(text):
    stop_words = set(stopwords.words('english'))
    word_tokens = word_tokenize(text.lower())
    filtered_words = [w for w in word_tokens if w.isalnum() and w not in stop_words]
    return ' '.join(filtered_words)

def common_word_frequency(row, topics):
    keywords = row['keywords']
    count_topics = Counter(topics.split())
    count_keywords = Counter(keywords.split())
    common_words = set(count_topics.keys()) & set(count_keywords.keys())
    common_frequencies = {word: min(count_topics[word], count_keywords[word]) for word in common_words}
    return max(common_frequencies.values(), default=0)

def find_common_word(topics, keywords):
    topic_set = set(topics)
    keyword_set = set(keywords)
    common_words = topic_set.intersection(keyword_set)
    return len(common_words) > 0

def find_media_best(topics, processed_media_paths, metadata, l=1):
    metadata = metadata[~metadata['path_datalake'].isin(processed_media_paths)]
    metadata["most_frequent_words"] = metadata["most_frequent_words"].apply(ast.literal_eval)


    topics = lemmatize_words(topics)
    print("Lemmatized topics:", topics)

    preprocessed_topics = preprocess_text(' '.join(topics))
    print("Preprocessed topics:", preprocessed_topics)

    metadata['preprocessed_keywords'] = metadata['most_frequent_words'].apply(lambda words: ' '.join(words))

    metadata['has_common_word'] = metadata['preprocessed_keywords'].apply(lambda x: find_common_word(topics, x.split()))

    filtered_metadata = metadata[metadata['has_common_word']]

    if not filtered_metadata.empty:
        filtered_metadata['max_common_frequency'] = filtered_metadata.apply(lambda row: common_word_frequency(row, preprocessed_topics), axis=1)

        highest_frequency = filtered_metadata['max_common_frequency'].max()

        rows_with_highest_frequency = filtered_metadata[filtered_metadata['max_common_frequency'] == highest_frequency].head(l)

        if not rows_with_highest_frequency.empty:
            topic_found = True
            media_found = True
            return topic_found, media_found, rows_with_highest_frequency["path_datalake"].tolist()

    topic_found = False
    media_found = False
    return topic_found, media_found, []


metadata=read_metadata_from_s3("soulchain-dev1-output-video", "new_metadata_mixkit_unsplash_pixabay.xlsx")

find_media_best(["summer", "sunlight", "mountains", "warmly", "glow"], ["datalake_media/image-3d97QVYOuL0.jpg-856bf518-b144-4656-b5a4-ca58e23566f3"], metadata, 2)

Lemmatized topics: ['summer', 'sunlight', 'mountain', 'warmly', 'glow']
Preprocessed topics: summer sunlight mountain warmly glow

/var/folders/ys/s5c8y6vx2n95hnjtr5vs5h000000gn/T/ipykernel_10806/2525116829.py:36: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  metadata["most_frequent_words"] = metadata["most_frequent_words"].apply(ast.literal_eval)
/var/folders/ys/s5c8y6vx2n95hnjtr5vs5h000000gn/T/ipykernel_10806/2525116829.py:45: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  metadata['preprocessed_keywords'] = metadata['most_frequent_words'].apply(lambda words: ' '.join(words))
/var/folders/ys/s5c8y6vx2n95hnjtr5vs5h000000gn/T/ipykernel_10806/2525116829.py:47: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  metadata['has_common_word'] = metadata['preprocessed_keywords'].apply(lambda x: find_common_word(topics, x.split()))
/var/folders/ys/s5c8y6vx2n95hnjtr5vs5h000000gn/T/ipykernel_10806/2525116829.py:52: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_metadata['max_common_frequency'] = filtered_metadata.apply(lambda row: common_word_frequency(row, preprocessed_topics), axis=1)

(True,
 True,
 ['datalake_media/image-X41O9TMInoU.jpg-355f41f1-0580-436d-9e5a-8def30a0a6d5',
  'datalake_media/image-aFqfi1ASUJc.jpg-bf099635-48b2-4452-8b0e-3a86e33f8887'])

In [ ]:
def count_topic_words(row):
    words = row.split()
    return sum(word in topics for word in words)

# Apply the function to each row in the 'words' column
metadata['topic_count'] = metadata['words'].apply(count_topic_words)

# Sort the DataFrame by 'topic_count' in descending order
metadata_sorted = metadata.sort_values(by='topic_count', ascending=False)

# Select the top 5 rows
top_5_rows = metadata_sorted.head(5)

In [100]:
lemmatize_words(["topics"])

['topic']

In [1]:
def get_first_word_after_slash(input_string):
    parts = input_string.split('/')
    
    last_part = parts[-1]
    
    sub_parts = last_part.split('-')
    
    first_word = sub_parts[0]
    
    return first_word


get_first_word_after_slash("datalake_media/video-2266-157183287_medium.mp4-a3b65f75-c34b-4d6e-ba14-c0a9b091bef5")

'video'

In [8]:
import cv2
import numpy as np
import requests

def is_video_readable(url):
    try:
        cap = cv2.VideoCapture(url)
        if cap.isOpened():
            cap.release()
            return True
        else:
            return False
    except Exception as e:
        print(f"Error: {e}")
        return False
    
is_video_readable("https://assets.mixkit.co/videos/preview/mixkit-rinsing-strawberries-apples-and-grapes-holding-hands-10434-large.mp4")

[tcp @ 0x109470e10] Failed to resolve hostname as: nodename nor servname provided, or not known
OpenCV: Couldn't read video stream from file "https://as"

False

In [9]:
from transformers import VisionEncoderDecoderModel, ViTImageProcessor, AutoTokenizer
from keybert import KeyBERT


def generate_video_description(video_urls):
    model = VisionEncoderDecoderModel.from_pretrained("nlpconnect/vit-gpt2-image-captioning")
    feature_extractor = ViTImageProcessor.from_pretrained("nlpconnect/vit-gpt2-image-captioning")
    tokenizer = AutoTokenizer.from_pretrained("nlpconnect/vit-gpt2-image-captioning")

    captions_all_videos = []
    keywords_all_videos = []

    print(video_urls)

    for video_url in video_urls:
        video_capture = cv2.VideoCapture(video_url)
        
        if not video_capture.isOpened():
            print(f"Error: Unable to open video URL '{video_url}'.")
            continue

        ret, frame = video_capture.read()
        if not ret:
            print(f"Error: No frames found in video '{video_url}'.")
            video_capture.release()
            continue

        pixel_values = feature_extractor(images=frame, return_tensors="pt").pixel_values
        output_ids = model.generate(pixel_values, max_length=50, num_beams=1, early_stopping=True)
        caption = tokenizer.decode(output_ids[0], skip_special_tokens=True)

        key_model = KeyBERT()
        keywords_with_scores = key_model.extract_keywords(caption)
        description_keywords = [keyword for keyword, score in keywords_with_scores]
        description_keywords_str = str(description_keywords)

        captions_all_videos.append(caption)
        keywords_all_videos.append(description_keywords_str)

        video_capture.release()

    return captions_all_videos, keywords_all_videos

/Users/fatimaezzahrasounnyslitine/Library/Python/3.9/lib/python/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [11]:
generate_video_description(["https://assets.mixkit.co/videos/preview/mixkit-rinsing-strawberries-apples-and-grapes-holding-hands-10434-large.mp4"])

['https://assets.mixkit.co/videos/preview/mixkit-rinsing-strawberries-apples-and-grapes-holding-hands-10434-large.mp4']

/Users/fatimaezzahrasounnyslitine/Library/Python/3.9/lib/python/site-packages/transformers/generation/configuration_utils.py:433: UserWarning: `num_beams` is set to 1. However, `early_stopping` is set to `True` -- this flag is only used in beam-based generation modes. You should set `num_beams>1` or unset `early_stopping`.
  warnings.warn(
We strongly recommend passing in an `attention_mask` since your input_ids may be padded. See https://huggingface.co/docs/transformers/troubleshooting#incorrect-output-when-padding-tokens-arent-masked.
You may ignore this warning if your `pad_token_id` (50256) is identical to the `bos_token_id` (50256), `eos_token_id` (50256), or the `sep_token_id` (None), and your input is not padded.

(['a blue and white vase filled with water and flowers '],
 ["['vase', 'flowers', 'blue', 'filled', 'water']"])

In [19]:
import os
import requests
from PIL import Image
from transformers import VisionEncoderDecoderModel, ViTImageProcessor, AutoTokenizer
from keybert import KeyBERT
import io
from PIL import Image
from io import BytesIO



def predict_step(image_urls):
    model = VisionEncoderDecoderModel.from_pretrained("nlpconnect/vit-gpt2-image-captioning")
    feature_extractor = ViTImageProcessor.from_pretrained("nlpconnect/vit-gpt2-image-captioning")
    tokenizer = AutoTokenizer.from_pretrained("nlpconnect/vit-gpt2-image-captioning")

    max_length = 16
    num_beams = 4
    gen_kwargs = {"max_length": max_length, "num_beams": num_beams}

    images = []
    for image_url in image_urls:
        response = requests.get(image_url)
        i_image = Image.open(BytesIO(response.content))
        if i_image.mode != "RGB":
            i_image = i_image.convert(mode="RGB")
        images.append(i_image)

    pixel_values = feature_extractor(images=images, return_tensors="pt").pixel_values

    output_ids = model.generate(pixel_values, **gen_kwargs)

    preds = tokenizer.batch_decode(output_ids, skip_special_tokens=True)
    preds = [pred.strip() for pred in preds]
    description = " ".join(preds)

    key_model = KeyBERT()
    keywords_with_scores = key_model.extract_keywords(description)
    description_keywords = [keyword for keyword, score in keywords_with_scores]
    description_keywords_str = str(description_keywords)
    
    print("Description done")
    return description, description_keywords_str

In [20]:
predict_step(["https://images.unsplash.com/uploads/1413387620228d142bee4/23eceb86"])

Description done

('a view from the top of a hill overlooking a body of water',
 "['hill', 'view', 'overlooking', 'water', 'body']")

In [29]:
from text_to_media import find_media_best
from datalake import read_metadata_from_s3
from topic import find_topics
text="A balanced diet is essential for maintaining optimal health and well-being. By including a variety of fruits, vegetables, whole grains, lean proteins, and healthy fats in your meals, you can ensure you are getting the necessary nutrients your body needs."
df = find_topics(text)
metadata=read_metadata_from_s3("soulchain-dev1-output-video", "new_metadata_mixkit_unsplash_pixabay.xlsx")
for index, row in df.iterrows():
    sentence = row['sentence']
    topic_found = False
    image_found = False

    l=1

    if 50<=len(sentence)<=100:
        l=2
    if len(sentence)>100:
        l=3

    topics =row['terms']

    print("topics",topics)
    topic_found, image_found,image_path_list = find_media_best(topics, [], metadata,l)  
    print(image_path_list)

topics ['diet', 'health', 'balanced', 'maintaining', 'optimal']
['diet', 'health', 'balanced', 'maintaining', 'optimal']
['datalake_media/image-bygTaBey1Xk.jpg-c8c7df3c-30e9-4ff5-a33e-2f64122101f7', 'datalake_media/image-gXSFnk2a9V4.jpg-a0496092-1701-40d3-98a2-13b522b1cb1a']
topics ['body', 'proteins', 'fruits', 'nutrients', 'vegetables', 'grains']
['body', 'protein', 'fruit', 'nutrient', 'vegetable', 'grain']
['datalake_media/image-bygTaBey1Xk.jpg-c8c7df3c-30e9-4ff5-a33e-2f64122101f7', 'datalake_media/image-gXSFnk2a9V4.jpg-a0496092-1701-40d3-98a2-13b522b1cb1a', 'datalake_media/image-grg6-DNJuaU.jpg-c2b853ee-529a-486b-b303-a01cd79e0b9a']
topics ['body', 'proteins', 'fruits', 'nutrients', 'vegetables', 'grains']
['body', 'protein', 'fruit', 'nutrient', 'vegetable', 'grain']
['datalake_media/image-bygTaBey1Xk.jpg-c8c7df3c-30e9-4ff5-a33e-2f64122101f7', 'datalake_media/image-gXSFnk2a9V4.jpg-a0496092-1701-40d3-98a2-13b522b1cb1a']

In [14]:
metadata

,name,keywords,url,type,term,path_datalake,description,keywords_description,source,size,count_usage,count_edit,media_state,new_description,entities,new_keywords,most_frequent_words
0,bygTaBey1Xk.jpg,"['grass', 'shore', 'ocean', 'coast', 'beach', ...",https://images.unsplash.com/uploads/1413387620...,image,grass,datalake_media/image-bygTaBey1Xk.jpg-c8c7df3c-...,sea and rock cliff with grasses under cloudy sky,"['cliff', 'grasses', 'cloudy', 'sky', 'rock']",unsplash,horizontal,0,0,useful,An image of the sea and cliffs in Scotland,"[('the sea', (12, 19), [(0.015625, 0.296875, 0...","['sea', 'cliff']","['sea', 'cliff']"
1,gXSFnk2a9V4.jpg,"['blue', 'holiday', 'geographical feature', 'a...",https://images.unsplash.com/reserve/jEs6K0y1Sb...,image,blue,datalake_media/image-gXSFnk2a9V4.jpg-a0496092-...,aerial photography of seashore,"['seashore', 'aerial', 'photography']",unsplash,vertical,0,0,useful,An image of a beach and ocean from a hill,"[('a beach', (12, 19), [(0.015625, 0.578125, 0...","['beach', 'ocean', 'hill']","['beach', 'ocean', 'hill']"
2,grg6-DNJuaU.jpg,"['sea', 'jump', 'waves', 'summer', 'holiday', ...",https://images.unsplash.com/uploads/1412192004...,image,sea,datalake_media/image-grg6-DNJuaU.jpg-c2b853ee-...,man surfboarding on ocean wave during daytime,"['surfboarding', 'ocean', 'wave', 'daytime', '...",unsplash,horizontal,0,0,useful,An image of a surfer catching a wave and a man...,"[('a surfer', (12, 20), [(0.515625, 0.140625, ...","['surfer', 'wave', 'man', 'water']","['surfer', 'wave', 'man', 'water']"
3,sO42hhChB1c.jpg,"['ocean', 'waves', 'mist', 'water', 'foam', 'd...",https://images.unsplash.com/reserve/ijl3tATFRp...,image,ocean,datalake_media/image-sO42hhChB1c.jpg-586ba674-...,body of water,"['water', 'body']",unsplash,horizontal,0,0,useful,An image of a foggy ocean and waves,"[('a foggy ocean', (12, 25), [(0.015625, 0.515...","['ocean', 'wave']","['ocean', 'wave']"
4,tkk8_HakQ98.jpg,"['dawn', 'scenery', 'glow', 'dune', 'sunlight'...",https://images.unsplash.com/reserve/6vaWXsQuSW...,image,dawn,datalake_media/image-tkk8_HakQ98.jpg-9f60f63f-...,car on desert during sunset,"['sunset', 'desert', 'car']",unsplash,horizontal,0,0,useful,An image of a car driving through the desert a...,"[('a car', (12, 17), [(0.359375, 0.609375, 0.4...","['car', 'desert', 'sunset']","['car', 'desert', 'sunset']"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12626,father-3871837_150.jpg,"['father', 'daughter', 'piggyback']",https://pixabay.com/get/g296ea0740891441347970...,image,father,datalake_media/image-father-3871837_150.jpg-0f...,,[],pixabay,horizontal,0,0,useful,An image of a father giving his daughter a pig...,"[('a father', (12, 20), [(0.390625, 0.109375, ...","['father', 'daughter', 'piggyback', 'ride', 'f...","['father', 'daughter', 'piggyback', 'ride', 'f..."
12627,mother-429158_150.jpg,"['mother', 'daughter', 'sunset']",https://pixabay.com/get/gdae8fafd1494228179ad8...,image,mother,datalake_media/image-mother-429158_150.jpg-b0e...,,[],pixabay,horizontal,0,0,useful,An image of a mother and son playing on the be...,"[('a mother', (12, 20), [(0.109375, 0.296875, ...","['mother', 'son', 'beach', 'sunset']","['mother', 'sunset', 'daughter', 'son', 'beach']"
12628,grapes-3555214_150.jpg,"['grapes', 'fruit', 'immature']",https://pixabay.com/get/ga3b3c3721572917afb7ce...,image,fruits,datalake_media/image-grapes-3555214_150.jpg-c4...,,[],pixabay,horizontal,0,0,useful,An image of a nice grape cluster,"[('a nice grape cluster', (12, 32), [(0.015625...","['grape', 'cluster']","['grape', 'fruit', 'immature', 'cluster']"
12629,house-7497001_150.png,"['house', 'doodle', 'building']",https://pixabay.com/get/g8664cddba4f5a00d6000f...,image,home,datalake_media/image-house-7497001_150.png-f88...,,[],pixabay,horizontal,0,0,useful,An image of a row of houses in a neighborhood,"[('a row of houses in a neighborhood', (12, 45...","['row', 'house', 'neighborhood']","['house', 'doodle', 'building', 'row', 'neighb..."
12630,salad-2756467_150.jpg,"['salad', 'fruit', 'berry']",https://pixabay.com/get/g6503ae4d75c69f3b64973...,image,food,datalake_media/image-salad-2756467_150.jpg-bfd...,,[],pixabay,horizontal,0,0,useful,An image of a salad and various fruits and veg...,"[('a salad', (12, 19), [(0.203125, 0.140625, 0...","['fruit', 'vegetable']","['fruit', 'salad', 'berry', 'vegetable']"

In [50]:
df

,name,keywords,url,type,term,path_datalake,description,keywords_description,source,size,count_usage,count_edit,media_state,new_description,entities,new_keywords,most_frequent_words
0,bygTaBey1Xk.jpg,"[grass, shore, ocean, coast, beach, sea, possi...",https://images.unsplash.com/uploads/1413387620...,image,grass,datalake_media/image-bygTaBey1Xk.jpg-c8c7df3c-...,sea and rock cliff with grasses under cloudy sky,"[cliff, grasses, cloudy, sky, rock]",unsplash,horizontal,0,0,useful,An image of the sea and cliffs in Scotland,"[('the sea', (12, 19), [(0.015625, 0.296875, 0...","[sea, cliff]","[sea, cliff]"
1,gXSFnk2a9V4.jpg,"[blue, holiday, geographical feature, aerial, ...",https://images.unsplash.com/reserve/jEs6K0y1Sb...,image,blue,datalake_media/image-gXSFnk2a9V4.jpg-a0496092-...,aerial photography of seashore,"[seashore, aerial, photography]",unsplash,vertical,0,0,useful,An image of a beach and ocean from a hill,"[('a beach', (12, 19), [(0.015625, 0.578125, 0...","[beach, ocean, hill]","[beach, ocean, hill]"
2,grg6-DNJuaU.jpg,"[sea, jump, waves, summer, holiday, beach, spo...",https://images.unsplash.com/uploads/1412192004...,image,sea,datalake_media/image-grg6-DNJuaU.jpg-c2b853ee-...,man surfboarding on ocean wave during daytime,"[surfboarding, ocean, wave, daytime, man]",unsplash,horizontal,0,0,useful,An image of a surfer catching a wave and a man...,"[('a surfer', (12, 20), [(0.515625, 0.140625, ...","[surfer, wave, man, water]","[surfer, wave, man, water]"
3,sO42hhChB1c.jpg,"[ocean, waves, mist, water, foam, dizzy, lost,...",https://images.unsplash.com/reserve/ijl3tATFRp...,image,ocean,datalake_media/image-sO42hhChB1c.jpg-586ba674-...,body of water,"[water, body]",unsplash,horizontal,0,0,useful,An image of a foggy ocean and waves,"[('a foggy ocean', (12, 25), [(0.015625, 0.515...","[ocean, wave]","[ocean, wave]"
4,tkk8_HakQ98.jpg,"[dawn, scenery, glow, dune, sunlight, adventur...",https://images.unsplash.com/reserve/6vaWXsQuSW...,image,dawn,datalake_media/image-tkk8_HakQ98.jpg-9f60f63f-...,car on desert during sunset,"[sunset, desert, car]",unsplash,horizontal,0,0,useful,An image of a car driving through the desert a...,"[('a car', (12, 17), [(0.359375, 0.609375, 0.4...","[car, desert, sunset]","[car, desert, sunset]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3823,father-3871837_150.jpg,"[father, daughter, piggyback]",https://pixabay.com/get/g296ea0740891441347970...,image,father,datalake_media/image-father-3871837_150.jpg-0f...,,[],pixabay,horizontal,0,0,useful,An image of a father giving his daughter a pig...,"[('a father', (12, 20), [(0.390625, 0.109375, ...","[father, daughter, piggyback, ride, field]","[father, daughter, piggyback, ride, field]"
3824,mother-429158_150.jpg,"[mother, daughter, sunset]",https://pixabay.com/get/gdae8fafd1494228179ad8...,image,mother,datalake_media/image-mother-429158_150.jpg-b0e...,,[],pixabay,horizontal,0,0,useful,An image of a mother and son playing on the be...,"[('a mother', (12, 20), [(0.109375, 0.296875, ...","[mother, son, beach, sunset]","[mother, sunset, daughter, son, beach]"
3825,grapes-3555214_150.jpg,"[grapes, fruit, immature]",https://pixabay.com/get/ga3b3c3721572917afb7ce...,image,fruits,datalake_media/image-grapes-3555214_150.jpg-c4...,,[],pixabay,horizontal,0,0,useful,An image of a nice grape cluster,"[('a nice grape cluster', (12, 32), [(0.015625...","[grape, cluster]","[grape, fruit, immature, cluster]"
3826,house-7497001_150.png,"[house, doodle, building]",https://pixabay.com/get/g8664cddba4f5a00d6000f...,image,home,datalake_media/image-house-7497001_150.png-f88...,,[],pixabay,horizontal,0,0,useful,An image of a row of houses in a neighborhood,"[('a row of houses in a neighborhood', (12, 45...","[row, house, neighborhood]","[house, doodle, building, row, neighborhood]"
3827,salad-2756467_150.jpg,"[salad, fruit, berry]",https://pixabay.com/get/g6503ae4d75c69f3b64973...,image,food,datalake_media/image-salad-2756467_150.jpg-bfd...,,[],pixabay,horizontal,0,0,useful,An image of a salad and various fruits and veg...,"[('a salad', (12, 19), [(0.203125, 0.140625, 0...","[fruit, vegetable]","[fruit, salad, berry, vegetable]"

In [51]:
metadata

,Unnamed: 0,name,keywords,url,type,term,path_datalake,description,keywords_description,source,size,count_usage,count_edit,media_state,new_description,entities,new_keywords,most_frequent_words
0,0,bygTaBey1Xk.jpg,"['grass', 'shore', 'ocean', 'coast', 'beach', ...",https://images.unsplash.com/uploads/1413387620...,image,grass,datalake_media/image-bygTaBey1Xk.jpg-c8c7df3c-...,sea and rock cliff with grasses under cloudy sky,"['cliff', 'grasses', 'cloudy', 'sky', 'rock']",unsplash,horizontal,0,0,useful,An image of the sea and cliffs in Scotland,"[('the sea', (12, 19), [(0.015625, 0.296875, 0...","['sea', 'cliff']","['sea', 'cliff']"
1,1,gXSFnk2a9V4.jpg,"['blue', 'holiday', 'geographical feature', 'a...",https://images.unsplash.com/reserve/jEs6K0y1Sb...,image,blue,datalake_media/image-gXSFnk2a9V4.jpg-a0496092-...,aerial photography of seashore,"['seashore', 'aerial', 'photography']",unsplash,vertical,0,0,useful,An image of a beach and ocean from a hill,"[('a beach', (12, 19), [(0.015625, 0.578125, 0...","['beach', 'ocean', 'hill']","['beach', 'ocean', 'hill']"
2,2,grg6-DNJuaU.jpg,"['sea', 'jump', 'waves', 'summer', 'holiday', ...",https://images.unsplash.com/uploads/1412192004...,image,sea,datalake_media/image-grg6-DNJuaU.jpg-c2b853ee-...,man surfboarding on ocean wave during daytime,"['surfboarding', 'ocean', 'wave', 'daytime', '...",unsplash,horizontal,0,0,useful,An image of a surfer catching a wave and a man...,"[('a surfer', (12, 20), [(0.515625, 0.140625, ...","['surfer', 'wave', 'man', 'water']","['surfer', 'wave', 'man', 'water']"
3,3,sO42hhChB1c.jpg,"['ocean', 'waves', 'mist', 'water', 'foam', 'd...",https://images.unsplash.com/reserve/ijl3tATFRp...,image,ocean,datalake_media/image-sO42hhChB1c.jpg-586ba674-...,body of water,"['water', 'body']",unsplash,horizontal,0,0,useful,An image of a foggy ocean and waves,"[('a foggy ocean', (12, 25), [(0.015625, 0.515...","['ocean', 'wave']","['ocean', 'wave']"
4,4,tkk8_HakQ98.jpg,"['dawn', 'scenery', 'glow', 'dune', 'sunlight'...",https://images.unsplash.com/reserve/6vaWXsQuSW...,image,dawn,datalake_media/image-tkk8_HakQ98.jpg-9f60f63f-...,car on desert during sunset,"['sunset', 'desert', 'car']",unsplash,horizontal,0,0,useful,An image of a car driving through the desert a...,"[('a car', (12, 17), [(0.359375, 0.609375, 0.4...","['car', 'desert', 'sunset']","['car', 'desert', 'sunset']"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12626,3823,father-3871837_150.jpg,"['father', 'daughter', 'piggyback']",https://pixabay.com/get/g296ea0740891441347970...,image,father,datalake_media/image-father-3871837_150.jpg-0f...,,[],pixabay,horizontal,0,0,useful,An image of a father giving his daughter a pig...,"[('a father', (12, 20), [(0.390625, 0.109375, ...","['father', 'daughter', 'piggyback', 'ride', 'f...","['father', 'daughter', 'piggyback', 'ride', 'f..."
12627,3824,mother-429158_150.jpg,"['mother', 'daughter', 'sunset']",https://pixabay.com/get/gdae8fafd1494228179ad8...,image,mother,datalake_media/image-mother-429158_150.jpg-b0e...,,[],pixabay,horizontal,0,0,useful,An image of a mother and son playing on the be...,"[('a mother', (12, 20), [(0.109375, 0.296875, ...","['mother', 'son', 'beach', 'sunset']","['mother', 'sunset', 'daughter', 'son', 'beach']"
12628,3825,grapes-3555214_150.jpg,"['grapes', 'fruit', 'immature']",https://pixabay.com/get/ga3b3c3721572917afb7ce...,image,fruits,datalake_media/image-grapes-3555214_150.jpg-c4...,,[],pixabay,horizontal,0,0,useful,An image of a nice grape cluster,"[('a nice grape cluster', (12, 32), [(0.015625...","['grape', 'cluster']","['grape', 'fruit', 'immature', 'cluster']"
12629,3826,house-7497001_150.png,"['house', 'doodle', 'building']",https://pixabay.com/get/g8664cddba4f5a00d6000f...,image,home,datalake_media/image-house-7497001_150.png-f88...,,[],pixabay,horizontal,0,0,useful,An image of a row of houses in a neighborhood,"[('a row of houses in a neighborhood', (12, 45...","['row', 'house', 'neighborhood']","['house', 'doodle', 'building', 'row', 'neighb..."
12630,3827,salad-2756467_150.jpg,"['salad', 'fruit', 'berry']",https://pixabay.com/get/g6503ae4d75c69f3b64973...,image,food,datalake_media/image-salad-2756467_150.jpg-bfd...,,[],pixabay,horizontal,0,0,useful,An image of a salad and various fruits and veg...,"[('a salad', (12, 19), [(0.203125, 0.140625, 0...","['fruit', 'vegetable']","['fruit', 'salad', 'berry', 'vegetable']"

In [56]:
import ast
metadata["most_frequent_words"] = metadata["most_frequent_words"].apply(ast.literal_eval)

In [57]:
metadata

,Unnamed: 0,name,keywords,url,type,term,path_datalake,description,keywords_description,source,size,count_usage,count_edit,media_state,new_description,entities,new_keywords,most_frequent_words
0,0,bygTaBey1Xk.jpg,"['grass', 'shore', 'ocean', 'coast', 'beach', ...",https://images.unsplash.com/uploads/1413387620...,image,grass,datalake_media/image-bygTaBey1Xk.jpg-c8c7df3c-...,sea and rock cliff with grasses under cloudy sky,"['cliff', 'grasses', 'cloudy', 'sky', 'rock']",unsplash,horizontal,0,0,useful,An image of the sea and cliffs in Scotland,"[('the sea', (12, 19), [(0.015625, 0.296875, 0...","['sea', 'cliff']","[sea, cliff]"
1,1,gXSFnk2a9V4.jpg,"['blue', 'holiday', 'geographical feature', 'a...",https://images.unsplash.com/reserve/jEs6K0y1Sb...,image,blue,datalake_media/image-gXSFnk2a9V4.jpg-a0496092-...,aerial photography of seashore,"['seashore', 'aerial', 'photography']",unsplash,vertical,0,0,useful,An image of a beach and ocean from a hill,"[('a beach', (12, 19), [(0.015625, 0.578125, 0...","['beach', 'ocean', 'hill']","[beach, ocean, hill]"
2,2,grg6-DNJuaU.jpg,"['sea', 'jump', 'waves', 'summer', 'holiday', ...",https://images.unsplash.com/uploads/1412192004...,image,sea,datalake_media/image-grg6-DNJuaU.jpg-c2b853ee-...,man surfboarding on ocean wave during daytime,"['surfboarding', 'ocean', 'wave', 'daytime', '...",unsplash,horizontal,0,0,useful,An image of a surfer catching a wave and a man...,"[('a surfer', (12, 20), [(0.515625, 0.140625, ...","['surfer', 'wave', 'man', 'water']","[surfer, wave, man, water]"
3,3,sO42hhChB1c.jpg,"['ocean', 'waves', 'mist', 'water', 'foam', 'd...",https://images.unsplash.com/reserve/ijl3tATFRp...,image,ocean,datalake_media/image-sO42hhChB1c.jpg-586ba674-...,body of water,"['water', 'body']",unsplash,horizontal,0,0,useful,An image of a foggy ocean and waves,"[('a foggy ocean', (12, 25), [(0.015625, 0.515...","['ocean', 'wave']","[ocean, wave]"
4,4,tkk8_HakQ98.jpg,"['dawn', 'scenery', 'glow', 'dune', 'sunlight'...",https://images.unsplash.com/reserve/6vaWXsQuSW...,image,dawn,datalake_media/image-tkk8_HakQ98.jpg-9f60f63f-...,car on desert during sunset,"['sunset', 'desert', 'car']",unsplash,horizontal,0,0,useful,An image of a car driving through the desert a...,"[('a car', (12, 17), [(0.359375, 0.609375, 0.4...","['car', 'desert', 'sunset']","[car, desert, sunset]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12626,3823,father-3871837_150.jpg,"['father', 'daughter', 'piggyback']",https://pixabay.com/get/g296ea0740891441347970...,image,father,datalake_media/image-father-3871837_150.jpg-0f...,,[],pixabay,horizontal,0,0,useful,An image of a father giving his daughter a pig...,"[('a father', (12, 20), [(0.390625, 0.109375, ...","['father', 'daughter', 'piggyback', 'ride', 'f...","[father, daughter, piggyback, ride, field]"
12627,3824,mother-429158_150.jpg,"['mother', 'daughter', 'sunset']",https://pixabay.com/get/gdae8fafd1494228179ad8...,image,mother,datalake_media/image-mother-429158_150.jpg-b0e...,,[],pixabay,horizontal,0,0,useful,An image of a mother and son playing on the be...,"[('a mother', (12, 20), [(0.109375, 0.296875, ...","['mother', 'son', 'beach', 'sunset']","[mother, sunset, daughter, son, beach]"
12628,3825,grapes-3555214_150.jpg,"['grapes', 'fruit', 'immature']",https://pixabay.com/get/ga3b3c3721572917afb7ce...,image,fruits,datalake_media/image-grapes-3555214_150.jpg-c4...,,[],pixabay,horizontal,0,0,useful,An image of a nice grape cluster,"[('a nice grape cluster', (12, 32), [(0.015625...","['grape', 'cluster']","[grape, fruit, immature, cluster]"
12629,3826,house-7497001_150.png,"['house', 'doodle', 'building']",https://pixabay.com/get/g8664cddba4f5a00d6000f...,image,home,datalake_media/image-house-7497001_150.png-f88...,,[],pixabay,horizontal,0,0,useful,An image of a row of houses in a neighborhood,"[('a row of houses in a neighborhood', (12, 45...","['row', 'house', 'neighborhood']","[house, doodle, building, row, neighborhood]"
12630,3827,salad-2756467_150.jpg,"['salad', 'fruit', 'berry']",https://pixabay.com/get/g6503ae4d75c69f3b64973...,image,food,datalake_media/image-salad-2756467_150.jpg-bfd...,,[],pixabay,horizontal,0,0,useful,An image of a salad and various fruits and veg...,"[('a salad', (12, 19), [(0.203125, 0.140625, 0...","['fruit', 'vegetable']","[fruit, salad, berry, vegetable]"

In [15]:
import requests
from io import BytesIO
import json
from botocore.exceptions import ClientError
from moviepy.editor import VideoFileClip, ImageClip, AudioFileClip, CompositeVideoClip,concatenate_videoclips
import tempfile
from io import BytesIO
from PIL import Image
import numpy as np
import requests
import uuid
import os
from datalake import put_image_in_s3
from text import create_text_updated_clip,def_translation
from langdetect import detect
from text import get_argos
import base64
media_list=[]
response = requests.get("https://images.unsplash.com/photo-1542622546-0505b9749cca")
if response.status_code == 200:
    media_data = response.content
    media_list.append(media_data)
else:
    print(f"Failed to fetch image from URL:")

image_stream = BytesIO(media_data)
image = Image.open(image_stream)
image = Image.open(image_stream).convert("RGB")
image_np = np.array(image)

In [13]:
media_key='datalake_media/hjdvkd'
if media_key.startswith('datalake_media'):
    print("yes")

yes

In [153]:
from datalake import read_metadata_from_s3

metadata=read_metadata_from_s3("soulchain-dev1-output-video", "new_metadata_mixkit_unsplash_pixabay.xlsx")

In [151]:
metadata = metadata[~metadata['path_datalake'].isin(["datalake_media/video-vegetables-8e4d0468-43bd-48b8-9c73-15163d754a29"])]

In [152]:
metadata.iloc[12732:12738]

,Unnamed: 0,name,keywords,url,type,term,path_datalake,count_usage,count_edit,media_state,description,keywords_description,source,size,new_description,entities,new_keywords,most_frequent_words
12732,99,Harvesting potato crops,"['veget', 'crop', 'harvest']",https://assets.mixkit.co/videos/preview/mixkit...,video,vegetables,datalake_media/video-vegetables-96ca1ee3-c071-...,0,0,useful,NaN,[],mixkit,horizontal,A video of a plowed field from a drone A video...,"[('a plowed field', (11, 25), [(0.015625, 0.01...","['potato', 'harvester', 'truck', 'drone', 'tra...","['veget', 'crop', 'harvest', 'potato', 'harves..."
12733,100,Creating vegetable omelette,"['cook', 'egg', 'veget']",https://assets.mixkit.co/videos/preview/mixkit...,video,vegetables,datalake_media/video-vegetables-929bfb5d-b2d6-...,0,0,useful,NaN,[],mixkit,horizontal,A video of an egg being fried in a pan with to...,"[('an egg', (11, 17), [(0.203125, 0.390625, 0....","['eggs', 'stove', 'iron', 'tomatoes', 'person'...","['egg', 'cook', 'veget', 'stove', 'iron', 'egg..."
12735,102,Broccoli splashing onto a table,"['food prepar', 'veget', 'splash']",https://assets.mixkit.co/videos/preview/mixkit...,video,vegetables,datalake_media/video-vegetables-7b7146bb-f957-...,0,0,useful,NaN,[],mixkit,horizontal,A video of cauliflower and broccoli on a white...,"[('cauliflower', (11, 22), [(0.421875, 0.01562...","['cauliflower', 'board', 'table', 'broccoli']","['food prepar', 'veget', 'splash', 'cauliflowe..."
12736,103,Washing lettuce before making a salad,"['food prepar', 'veget', 'wash']",https://assets.mixkit.co/videos/preview/mixkit...,video,vegetables,datalake_media/video-vegetables-b5daaba4-8765-...,0,0,useful,NaN,[],mixkit,horizontal,A video of a hand putting lettuce in a bowl A ...,"[('lettuce', (26, 33), [(0.140625, 0.015625, 0...","['lettuce', 'hand', 'glass', 'bowl']","['food prepar', 'veget', 'wash', 'lettuce', 'h..."
12737,104,Chef preparing a salad in the kitchen,"['food', 'food prepar', 'chef', 'veget', 'rest...",https://assets.mixkit.co/videos/preview/mixkit...,video,vegetables,datalake_media/video-vegetables-7474d6a7-2e59-...,0,0,useful,NaN,[],mixkit,horizontal,A video of a chef preparing a plate of food A ...,"[('a chef', (11, 17), [(0.015625, 0.015625, 0....","['chef', 'salad', 'kitchen', 'plate', 'food']","['food', 'chef', 'food prepar', 'veget', 'rest..."
12738,105,Closeup of plants in a vegetable garden,"['close up', 'medium shot', 'healthy lifestyl'...",https://assets.mixkit.co/videos/preview/mixkit...,video,vegetables,datalake_media/video-vegetables-3785d0ac-660a-...,0,0,useful,Closeup video of a green romaine lettuce in a ...,"['lettuce', 'romaine', 'garden', 'nursery', 'v...",mixkit,horizontal,A video of a kale plant growing in a garden A ...,"[('a kale plant', (11, 23), [(0.109375, 0.1093...","['plant', 'garden']","['garden', 'plant', '', 'close up', 'medium sh..."

In [159]:
from text_to_media import find_media_best

metadata_video = metadata[metadata["type"] == 'video']
metadata_video= metadata_video[metadata_video["media_state"] == 'useful']
find_media_best(['health', 'nutritionist'],["datalake_media/video-vegetables-8e4d0468-43bd-48b8-9c73-15163d754a29"],metadata_video,1)

ValueError: malformed node or string: nan

In [158]:
metadata_image

,Unnamed: 0,name,keywords,url,type,term,path_datalake,count_usage,count_edit,media_state,description,keywords_description,source,size,new_description,entities,new_keywords,most_frequent_words
0,0,21617-319452308_large.mp4,"['blood', 'medicine', 'blood cells']",https://cdn.pixabay.com/video/2019/02/23/21617...,video,health,datalake_media/video-21617-319452308_large.mp4...,1,0,useful,NaN,[],pixabay,NaN,NaN,NaN,NaN,NaN
1,1,8449-209292163_large.mp4,"['heart', 'heartbeat', 'slow heart']",https://cdn.pixabay.com/video/2017/03/20/8449-...,video,health,datalake_media/video-8449-209292163_large.mp4-...,0,0,useful,NaN,[],pixabay,NaN,NaN,NaN,NaN,NaN
12633,0,Boxer bleeding after a fight,"['medium shot', 'sport', 'athlet', 'train', 'f...",https://assets.mixkit.co/videos/preview/mixkit...,video,sport,datalake_media/video-sport-48b6b38b-d2c6-47b2-...,0,0,useful,Injured and bleeding boxer sitting in a corner...,"['boxer', 'injured', 'sitting', 'ring', 'bleed...",mixkit,horizontal,Injured and bleeding boxer sitting in a corner...,NaN,"['ring', 'corner', 'boxer', 'fight']","['ring', 'fight', 'box', 'boxer', 'medium shot..."
12634,1,Boxer training with a punching bag at the gym,"['medium shot', 'man', 'sport', 'train', 'athl...",https://assets.mixkit.co/videos/preview/mixkit...,video,sport,datalake_media/video-sport-33284849-7689-4467-...,0,0,useful,Amateur shirtless boxer training wearing boxin...,"['boxing', 'boxer', 'gym', 'training', 'gloves']",mixkit,horizontal,A video of a man punching a heavy bag in a gym...,"[('a man', (11, 16), [(0.265625, 0.109375, 0.7...","['man', 'punch', 'boxer', 'bag', 'gym', 'boxing']","['man', 'box', 'boxing', 'boxer', 'gym', 'punc..."
12635,2,Fencer fighting with sword in hand,"['sport', 'train', 'athlet', 'sword']",https://assets.mixkit.co/videos/preview/mixkit...,video,sport,datalake_media/video-sport-6420ae0b-3ea8-45ce-...,0,0,useful,NaN,[],mixkit,horizontal,A video of a woman in white fencing costume an...,"[('white fencing costume', (22, 43), [(0.42187...","['woman', 'sword', 'costume', 'studio', 'mask'...","['sword', 'sport', 'train', 'athlet', 'woman',..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14901,1767,Man skillfully practicing pirouettes in a park,"['sport', 'medium shot wid', 'exercis', 'athle...",https://assets.mixkit.co/videos/preview/mixkit...,video,sport,datalake_media/video-sport-c11ecf93-f073-4aab-...,0,0,useful,Two cheerleader guys lifting a girl upside dow...,"['lifting', 'cheerleader', 'workout', 'pyramid...",mixkit,vertical,A video of a woman doing a squat with a traine...,"[('a woman', (11, 18), [(0.265625, 0.171875, 0...","['squat', 'park', 'man', 'trainer', 'woman', '...","['sport', 'medium shot wid', 'exercis', 'athle..."
14902,1768,Cheerleader girl in pose on top of a pyramid,"['sport', 'exercis', 'low angle shot', 'athlet...",https://assets.mixkit.co/videos/preview/mixkit...,video,sport,datalake_media/video-sport-dee6dd45-e368-40cd-...,0,0,useful,"Cheerleader girl in pose, raising her arms on ...","['cheerleader', 'pose', 'pyramid', 'girl', 'ra...",mixkit,vertical,A video of a woman jumping in the air A video ...,"[('a woman', (11, 18), [(0.015625, 0.046875, 0...","['air', 'woman']","['sport', 'exercis', 'low angle shot', 'athlet..."
14903,1769,Cheerleader boy lifting a girl on his hands,"['sport', 'slow mot', 'exercis', 'track', 'ath...",https://assets.mixkit.co/videos/preview/mixkit...,video,sport,datalake_media/video-sport-d3a0fcb8-e665-4c73-...,0,0,useful,Cheerleader man lifts a girl to carry her stan...,"['cheerleader', 'lifts', 'girl', 'workout', 'c...",mixkit,vertical,A video of a man and a woman on a tennis court...,"[('a man', (11, 16), [(0.265625, 0.515625, 0.7...","['expression', 'tennis', 'park', 'man', 'court...","['sport', 'slow mot', 'exercis', 'track', 'ath..."
14904,1770,Cheerleaders throwing a girl into the air at a...,"['sport', 'medium shot wid', 'exercis', 'track...",https://assets.mixkit.co/videos/preview/mixkit...,video,sport,datalake_media/video-sport-807c3dc2-f9e7-45ce-...,0,0,useful,Cheerleading team throwing a girl who takes a ...,"['cheerleading', 'throwing', 'spin', 'girl', '...",mixkit,horizontal,A video of a group of young men playing basket...,"[('young men', (22, 31), [(0.546875, 0.515625,...","['ground', 'basketball', 'group', 'man', 'cour...","['sport', 'medium shot wid', 'exercis', 'track..."
14905,1771,Point of view fighting in a ring against a woman,"['sport', 'women', 'sport', 'fight', 'box', 'g...",https://assets.mixkit.co/videos/preview/mixkit...,video,sport,datalake_media/video-sport-58ae574d-449a-4265-...,0,0,useful,Point of view during an intense mixed martial ...,"['punches', 'martial', 'woman', 'match', 'ring']",mixkit,horizontal,A video of a female boxer throwing a punch in ...,"[('a female boxer', (11, 25), [(0.421875, 0.01...","['neon', 'police', 'man', 'punch', 'ring', 'ni...","['woman', 'ring', 'sport', 'fight', 'punch', '..."

In [1]:
from text_to_media import find_media_best
import pandas as pd

metadata=pd.read_csv("metadata_new_pixabay")

find_media_best(['wellness', 'longevity'],[], metadata)

/Users/fatimaezzahrasounnyslitine/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
/Users/fatimaezzahrasounnyslitine/Library/Python/3.9/lib/python/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Lemmatized topics: ['wellness', 'longevity']
Preprocessed topics: wellness longevity

(False, False, [])

In [5]:
def replace_default_image(image_path_list, processed_image_paths):
    for i in range(len(image_path_list)):
        if image_path_list[i] == "datalake_media/default_image.jpg":
            if i > 0:
                image_path_list[i] = image_path_list[i - 1]
            else:
                image_path_list[i] = processed_image_paths[-1]
    return image_path_list

# Example usage:
image_path_list = ["datalake_media/default_image.jpg", "image3.jpg", "datalake_media/default_image.jpg"]
processed_image_paths = ["processed_image1.jpg", "processed_image2.jpg", "processed_image3.jpg"]

image_path_list = replace_default_image(image_path_list, processed_image_paths)

In [6]:
image_path_list

['processed_image3.jpg', 'image3.jpg', 'image3.jpg']