In [2]:
import pandas as pd
import os
metadata= pd.read_excel('metadata.xlsx')


metadata=metadata[metadata["type"]=='image']

In [11]:
import requests
import io
from io import BytesIO
import uuid
import boto3
from openpyxl import load_workbook
from botocore.exceptions import ClientError
import os
from pathlib import Path
import pandas as pd
def generate_download_url(bucket_name, object_name, expiration=3600):
    session = boto3.Session(region_name='eu-west-1')
    s3_client = session.client('s3',aws_access_key_id="AKIAUJXLE2HEOGWEMCEX",aws_secret_access_key="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")
    try:
        url = s3_client.generate_presigned_url(
            'get_object',
            Params={'Bucket': bucket_name, 'Key': object_name},
            ExpiresIn=expiration
        )
    except ClientError as e:
        print(f"Error generating presigned URL: {e}")
        return None

    return url

url=generate_download_url('soulchain-dev1-output-video','datalake_media/image-vegetables-752153_150.jpg-b825acb9-eeb6-459c-a309-605d2337f777')
url

'https://soulchain-dev1-output-video.s3.amazonaws.com/datalake_media/image-vegetables-752153_150.jpg-b825acb9-eeb6-459c-a309-605d2337f777?AWSAccessKeyId=AKIAUJXLE2HEOGWEMCEX&Signature=%2F%2B8W3z0%2FXjvj1Sw%2BrYV5kV6%2B7XY%3D&Expires=1710240227'

In [15]:
import cv2
import numpy as np
import requests
from io import BytesIO
from transformers import VisionEncoderDecoderModel, ViTImageProcessor, AutoTokenizer
from keybert import KeyBERT

def generate_video_description(video_urls):

    model = VisionEncoderDecoderModel.from_pretrained("nlpconnect/vit-gpt2-image-captioning")
    feature_extractor = ViTImageProcessor.from_pretrained("nlpconnect/vit-gpt2-image-captioning")
    tokenizer = AutoTokenizer.from_pretrained("nlpconnect/vit-gpt2-image-captioning")

    captions_all_videos = []
    keywords_all_videos = []

    for video_url in video_urls:
        
        response = requests.get(video_url)
        if response.status_code != 200:
            print(f"Error: Unable to fetch video from URL '{video_url}'.")
            continue

        #video_bytes = BytesIO(response.content)
        video_capture = cv2.VideoCapture(response.content)
        
        if not video_capture.isOpened():
            print(f"Error: Unable to open video from URL '{video_url}'.")
            continue

        ret, frame = video_capture.read()
        if not ret:
            print(f"Error: No frames found in video from URL '{video_url}'.")
            continue

        pixel_values = feature_extractor(images=frame, return_tensors="pt").pixel_values
        output_ids = model.generate(pixel_values, max_length=50, num_beams=1, early_stopping=True)
        caption = tokenizer.decode(output_ids[0], skip_special_tokens=True)

        key_model = KeyBERT()
        keywords_with_scores = key_model.extract_keywords(caption)
        description_keywords = [keyword for keyword, score in keywords_with_scores]
        description_keywords_str = str(description_keywords)

        captions_all_videos.append(caption)
        keywords_all_videos.append(description_keywords_str)

        video_capture.release()

    return captions_all_videos, keywords_all_videos

captions_all_videos, keywords_all_videos=generate_video_description(['https://cdn.pixabay.com/vimeo/209766289/food-8477.mp4?width=1920&hash=b990aa328faf2311e2fac4d3f39870543496f889'])

error: OpenCV(4.9.0) :-1: error: (-5:Bad argument) in function 'VideoCapture'
> Overload resolution failed:
>  - Can't convert object to 'str' for 'filename'
>  - VideoCapture() missing required argument 'apiPreference' (pos 2)
>  - Argument 'index' is required to be an integer
>  - VideoCapture() missing required argument 'apiPreference' (pos 2)

In [3]:
import requests
from PIL import Image
from io import BytesIO


from transformers import VisionEncoderDecoderModel, ViTImageProcessor, AutoTokenizer
import torch
from PIL import Image

model = VisionEncoderDecoderModel.from_pretrained("nlpconnect/vit-gpt2-image-captioning")
feature_extractor = ViTImageProcessor.from_pretrained("nlpconnect/vit-gpt2-image-captioning")
tokenizer = AutoTokenizer.from_pretrained("nlpconnect/vit-gpt2-image-captioning")

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)

max_length = 16
num_beams = 4
gen_kwargs = {"max_length": max_length, "num_beams": num_beams}

def predict_from_url(image_url):
    response = requests.get(image_url)
    image = Image.open(BytesIO(response.content))
    
    pixel_values = feature_extractor(images=[image], return_tensors="pt").pixel_values
    pixel_values = pixel_values.to(device)

    output_ids = model.generate(pixel_values, **gen_kwargs)

    preds = tokenizer.batch_decode(output_ids, skip_special_tokens=True)
    preds = [pred.strip() for pred in preds]
    
    return preds

predicted_caption = predict_from_url(url)
print(predicted_caption)

/Users/fatimaezzahrasounnyslitine/Library/Python/3.9/lib/python/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
We strongly recommend passing in an `attention_mask` since your input_ids may be padded. See https://huggingface.co/docs/transformers/troubleshooting#incorrect-output-when-padding-tokens-arent-masked.
You may ignore this warning if your `pad_token_id` (50256) is identical to the `bos_token_id` (50256), `eos_token_id` (50256), or the `sep_token_id` (None), and your input is not padded.

['a bowl filled with lots of food on top of a table']

In [12]:

from transformers import pipeline

image_to_text = pipeline("image-to-text", model="nlpconnect/vit-gpt2-image-captioning")

image_to_text(url)

# [{'generated_text': 'a soccer game with a player jumping to catch the ball '}]

Could not find image processor class in the image processor config or the model config. Loading based on pattern matching with the model's feature extractor configuration. Please open a PR/issue to update `preprocessor_config.json` to use `image_processor_type` instead of `feature_extractor_type`. This warning will be removed in v4.40.
/Users/fatimaezzahrasounnyslitine/Library/Python/3.9/lib/python/site-packages/transformers/generation/utils.py:1133: UserWarning: Using the model-agnostic default `max_length` (=20) to control the generation length. We recommend setting `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(

[{'generated_text': 'a basket filled with lots of different types of fruit '}]

In [5]:
import cv2
import os
import requests
from io import BytesIO
from PIL import Image
from transformers import VisionEncoderDecoderModel, ViTImageProcessor, AutoTokenizer
from keybert import KeyBERT


def generate_video_description(video_urls):

    model = VisionEncoderDecoderModel.from_pretrained("nlpconnect/vit-gpt2-image-captioning")
    feature_extractor = ViTImageProcessor.from_pretrained("nlpconnect/vit-gpt2-image-captioning")
    tokenizer = AutoTokenizer.from_pretrained("nlpconnect/vit-gpt2-image-captioning")

    captions_all_videos = []
    keywords_all_videos = []

    for video_path in video_urls:
        #video_path=os.path.join(video_folder, video_path)
        
        video_capture = cv2.VideoCapture(video_path)
        
        if not video_capture.isOpened():
            print(f"Error: Unable to open video file '{video_path}'.")
            continue

        ret, frame = video_capture.read()
        if not ret:
            print(f"Error: No frames found in video '{video_path}'.")
            continue

        pixel_values = feature_extractor(images=frame, return_tensors="pt").pixel_values
        output_ids = model.generate(pixel_values, max_length=50, num_beams=1, early_stopping=True)
        caption = tokenizer.decode(output_ids[0], skip_special_tokens=True)

        key_model = KeyBERT()
        keywords_with_scores = key_model.extract_keywords(caption)
        description_keywords = [keyword for keyword, score in keywords_with_scores]
        description_keywords_str = str(description_keywords)

        captions_all_videos.append(caption)
        keywords_all_videos.append(description_keywords_str)

        video_capture.release()
        os.remove(video_path)

    return captions_all_videos, keywords_all_videos


video_urls = ['https://soulchain-dev1-output-video.s3.amazonaws.com/video-f90cc2b2-bad9-47de-84e1-48eb23455d11?AWSAccessKeyId=AKIAUJXLE2HEOGWEMCEX&Signature=qVDxUVdC2TG80T2WnMRV7TSPIxc%3D&Expires=1710181314']  # Replace "url1", "url2" with your actual URLs
captions, keywords = generate_video_description(video_urls)
print("Captions:", captions)
print("Keywords:", keywords)

/Users/fatimaezzahrasounnyslitine/Library/Python/3.9/lib/python/site-packages/transformers/generation/configuration_utils.py:433: UserWarning: `num_beams` is set to 1. However, `early_stopping` is set to `True` -- this flag is only used in beam-based generation modes. You should set `num_beams>1` or unset `early_stopping`.
  warnings.warn(
We strongly recommend passing in an `attention_mask` since your input_ids may be padded. See https://huggingface.co/docs/transformers/troubleshooting#incorrect-output-when-padding-tokens-arent-masked.
You may ignore this warning if your `pad_token_id` (50256) is identical to the `bos_token_id` (50256), `eos_token_id` (50256), or the `sep_token_id` (None), and your input is not padded.

FileNotFoundError: [Errno 2] No such file or directory: 'https://soulchain-dev1-output-video.s3.amazonaws.com/video-f90cc2b2-bad9-47de-84e1-48eb23455d11?AWSAccessKeyId=AKIAUJXLE2HEOGWEMCEX&Signature=qVDxUVdC2TG80T2WnMRV7TSPIxc%3D&Expires=1710181314'

In [1]:
import requests

def download_image(url, destination):
    try:
        response = requests.get(url)
        if response.status_code == 200:
            with open(destination, 'wb') as f:
                f.write(response.content)
            print(f"Image downloaded successfully to {destination}")
        else:
            print(f"Failed to download image from {url}. Status code: {response.status_code}")
    except Exception as e:
        print(f"An error occurred: {e}")

# Example usage:
url = "https://soulchain-dev1-output-video.s3.amazonaws.com/image-2ae94688-4347-421e-9fe8-e2907ae82c24?AWSAccessKeyId=AKIAUJXLE2HEOGWEMCEX&Signature=hQzS2Uy0FNBZF1lPJQkCSPp%2BPBw%3D&Expires=1709311495"  # Replace with the image URL returned from generate_download_url
destination = "image.jpg"  # Specify the destination file path
download_image(url, destination)

Failed to download image from https://soulchain-dev1-output-video.s3.amazonaws.com/image-2ae94688-4347-421e-9fe8-e2907ae82c24?AWSAccessKeyId=AKIAUJXLE2HEOGWEMCEX&Signature=hQzS2Uy0FNBZF1lPJQkCSPp%2BPBw%3D&Expires=1709311495. Status code: 403

In [4]:
from video import search_video_for_dataframe_pixabay_video 

data = {
    'terms': [
        ['nutrition', 'health', 'foods', 'variety'],
        ['variety', 'foods', 'health', 'nutrition', 'key']
    ]
}

i=0
df = pd.DataFrame(data)

df
processed_video_paths = set()  

for index, row in df.iterrows():
    print(row['terms'][i])

nutrition
variety

In [18]:
import requests
import os
import pandas as pd
from PIL import Image
from transformers import VisionEncoderDecoderModel, ViTImageProcessor, AutoTokenizer
from keybert import KeyBERT
from moviepy.editor import VideoFileClip
import cv2
import torch
from collections import Counter
def generate_video_description(video_path):

    model = VisionEncoderDecoderModel.from_pretrained("nlpconnect/vit-gpt2-image-captioning")
    feature_extractor = ViTImageProcessor.from_pretrained("nlpconnect/vit-gpt2-image-captioning")
    tokenizer = AutoTokenizer.from_pretrained("nlpconnect/vit-gpt2-image-captioning")

    captions_all_videos = []
    keywords_all_videos = []

        
    video_capture = cv2.VideoCapture(video_path)
    
    if not video_capture.isOpened():
        print(f"Error: Unable to open video file '{video_path}'.")
        

    ret, frame = video_capture.read()
    if not ret:
        print(f"Error: No frames found in video '{video_path}'.")
        

    pixel_values = feature_extractor(images=frame, return_tensors="pt").pixel_values
    output_ids = model.generate(pixel_values, max_length=50, num_beams=1, early_stopping=True)
    caption = tokenizer.decode(output_ids[0], skip_special_tokens=True)

    key_model = KeyBERT()
    keywords_with_scores = key_model.extract_keywords(caption)
    description_keywords = [keyword for keyword, score in keywords_with_scores]
    description_keywords_str = str(description_keywords)

    video_capture.release()

    captions_all_videos=str(caption)
    return captions_all_videos, description_keywords_str

captions_all_videos,keywords_all_videos=  generate_video_description('scrapped_media/beef-22476.mp4')

In [21]:
captions_all_videos

'a blue bucket filled with water and a bunch of birds '

In [11]:
def predict_step(image_paths):

    model = VisionEncoderDecoderModel.from_pretrained("nlpconnect/vit-gpt2-image-captioning")
    feature_extractor = ViTImageProcessor.from_pretrained("nlpconnect/vit-gpt2-image-captioning")
    tokenizer = AutoTokenizer.from_pretrained("nlpconnect/vit-gpt2-image-captioning")

    max_length = 16
    num_beams = 4
    gen_kwargs = {"max_length": max_length, "num_beams": num_beams}

    images = []
    for image_path in image_paths:
        i_image = Image.open(image_path)
        if i_image.mode != "RGB":
            i_image = i_image.convert(mode="RGB")

        images.append(i_image)

    pixel_values = feature_extractor(images=images, return_tensors="pt").pixel_values

    output_ids = model.generate(pixel_values, **gen_kwargs)

    preds = tokenizer.batch_decode(output_ids, skip_special_tokens=True)
    preds = [pred.strip() for pred in preds]
    description = " ".join(preds)

    key_model = KeyBERT()
    keywords_with_scores = key_model.extract_keywords(description)
    description_keywords = [keyword for keyword, score in keywords_with_scores]
    description_keywords_str = str(description_keywords)
    return description, description_keywords_str

description, description_keywords_str=predict_step(['scrapped_media/vegetables-1085063_150.jpg'])

In [22]:
description_keywords_str

"['fruits', 'vegetables', 'table', 'variety']"

In [9]:
keywords_all_videos

["['bucket', 'birds', 'water', 'blue', 'filled']"]

In [1]:
from transformers import VisionEncoderDecoderModel, ViTImageProcessor, AutoTokenizer

# Load the models
model = VisionEncoderDecoderModel.from_pretrained("nlpconnect/vit-gpt2-image-captioning")
feature_extractor = ViTImageProcessor.from_pretrained("nlpconnect/vit-gpt2-image-captioning")
tokenizer = AutoTokenizer.from_pretrained("nlpconnect/vit-gpt2-image-captioning")

In [2]:
model.save_pretrained("gpt2_saved_model")
feature_extractor.save_pretrained("gpt2_saved_feature_extractor")
tokenizer.save_pretrained("gpt2_saved_tokenizer")

Removed shared tensor {'decoder.lm_head.weight'} while saving. This should be OK, but check by verifying that you don't receive any warning while reloading

('gpt2_saved_tokenizer/tokenizer_config.json',
 'gpt2_saved_tokenizer/special_tokens_map.json',
 'gpt2_saved_tokenizer/vocab.json',
 'gpt2_saved_tokenizer/merges.txt',
 'gpt2_saved_tokenizer/added_tokens.json',
 'gpt2_saved_tokenizer/tokenizer.json')

In [3]:
model = VisionEncoderDecoderModel.from_pretrained("gpt2_saved_model")
feature_extractor = ViTImageProcessor.from_pretrained("gpt2_saved_feature_extractor")
tokenizer = AutoTokenizer.from_pretrained("gpt2_saved_tokenizer")

In [5]:
import os
import json

# Load the JSON data
with open('challenge.json', 'r') as file:
    data = json.load(file)

# Directory containing the files
files_directory = "challenge"

# Function to check file existence
def check_files(data):
    missing_files = []
    for scene in data.values():
        if isinstance(scene, dict):
            for file_path in scene.values():
                if isinstance(file_path, str):
                    full_path = os.path.join(files_directory, file_path)
                    if not os.path.exists(full_path):
                        missing_files.append(full_path)
                elif isinstance(file_path, list):
                    for fp in file_path:
                        full_path = os.path.join(files_directory, fp)
                        if not os.path.exists(full_path):
                            missing_files.append(full_path)
                else:
                    missing_files.append(file_path)
    return missing_files

# Check for missing files
missing_files = check_files(data)

# Print missing files
if missing_files:
    print("Missing files:")
    for file_path in missing_files:
        print(file_path)
else:
    print("All files listed in the JSON data exist.")

Missing files:
challenge/Nature is alive with rustling leaves and gentle breezes.
challenge/Sunlight paints the world in shades of gold and green.
challenge/Babbling streams flow through the land, singing a peaceful song.
challenge/Wildflowers bloom, adding bursts of color.
challenge/Mountains stand tall, reaching toward the sky.
challenge/In this beautiful dance, nature's wonder unfolds.

In [14]:
import pandas as pd
import numpy as np
import nltk
from nltk.tokenize import sent_tokenize
from nltk.corpus import stopwords
from gensim import corpora, models
import spacy
from spacy.util import fix_random_seed

def split_text_into_sentences(text):
    sentences = sent_tokenize(text)
    return sentences
def split_sentence_into_two_parts(sentence, max_length=100):
    nlp = spacy.load('en_core_web_sm')

    if len(sentence) > max_length:
        # Attempt to split the sentence at the last space within the specified length
        split_index = sentence.rfind(' ', 0, max_length)

        if split_index != -1:
            part1 = sentence[:split_index].strip()
            part2 = sentence[split_index + 1:].strip()

            # Check if the last word of part1 is a verb, and if so, move it to part2
            last_word_part1 = nlp(part1.split()[-1])
            
            if last_word_part1 and last_word_part1[0].pos_ == 'VERB':
                part1 = ' '.join(part1.split()[:-1]).strip()
                part2 = last_word_part1.text + ' ' + part2

                return part1, part2

        # If no space is found or the last word is not a verb, try to split when a verb is found
        doc = nlp(sentence)
        for token in reversed(doc):
            if token.pos_ == 'VERB':
                split_index = token.idx
                part1 = sentence[:split_index].strip()
                part2 = sentence[split_index:].strip()
                return part1, part2

        # If no verb is found, split at the max_length
        part1 = sentence[:max_length].strip()
        part2 = sentence[max_length:].strip()
        return part1, part2
    else:
        return sentence, None


def find_topics(text):
    np.random.seed(42)

    sentences = split_text_into_sentences(text)

    stop_words = set(stopwords.words('english'))
    tokenized_sentences = [nltk.word_tokenize(sentence.lower()) for sentence in sentences]
    filtered_sentences = [
        [word for word in sentence if word.isalnum() and word not in stop_words]
        for sentence in tokenized_sentences
    ]

    dictionary = corpora.Dictionary(filtered_sentences)
    corpus = [dictionary.doc2bow(sentence) for sentence in filtered_sentences]

    np.random.seed(42)

    gensim_seed = 42
    lda_model = models.LdaModel(corpus, num_topics=len(sentences), id2word=dictionary, passes=15, random_state=gensim_seed)

    spacy_seed = 42
    fix_random_seed(spacy_seed)
    nlp = spacy.load('en_core_web_sm', disable=['parser', 'ner'])

    topic_data = []
    for sentence_id, sentence in enumerate(sentences):
        part1, part2 = split_sentence_into_two_parts(sentence)
        original_sentence = sentence  # Store the original sentence before any splitting
        if part2:
            topics_part1 = lda_model.get_document_topics(corpus[sentence_id])
            topics_part2 = lda_model.get_document_topics(dictionary.doc2bow(part2.lower().split()))

            # Combine topics from both parts
            combined_topics = topics_part1 + topics_part2

            top_topic = max(combined_topics, key=lambda x: x[1])
            top_terms = [term[0] for term in lda_model.show_topic(top_topic[0])]

            doc = nlp(' '.join(top_terms))
            cleaned_terms = [
                token.text
                for token in doc
                if token.pos_ not in ['ADJ', 'ADV', 'VERB']
            ]

            topic_data.append({'id': sentence_id + 1, 'original_sentence': original_sentence, 'sentence': part1, 'topic': top_topic[0] + 1, 'terms': cleaned_terms})
            topic_data.append({'id': sentence_id + 1, 'original_sentence': original_sentence, 'sentence': part2, 'topic': top_topic[0] + 1, 'terms': cleaned_terms})
        else:
            topics = lda_model.get_document_topics(corpus[sentence_id])
            top_topic = max(topics, key=lambda x: x[1])
            top_terms = [term[0] for term in lda_model.show_topic(top_topic[0])]

            doc = nlp(' '.join(top_terms))
            cleaned_terms = [
                token.text
                for token in doc
                if token.pos_ not in ['ADJ', 'ADV', 'VERB']
            ]

            topic_data.append({'id': sentence_id + 1, 'original_sentence': original_sentence, 'sentence': sentence, 'topic': top_topic[0] + 1, 'terms': cleaned_terms})

    df = pd.DataFrame(topic_data)
    df['sentence_part_id'] = df.index

    return df

In [15]:
text= "The intricate interplay between economic dynamics and the real estate sector is manifested in a multifaceted manner exerting a profound impact on both property values and the overarching demand for real estate properties. Market fluctuations impact housing affordability and investment decisions. Economic stability fosters a robust real estate environment, driving growth. Market resilience relies on a balance between economic health and stability. Real estate mirrors economic trends, responding to market dynamics and shifts. Economic indicators guide real estate trends, dictating property values and transactions. In turn, real estate plays a pivotal role in economic development. Economic fluctuations echo through real estate markets, influencing buying patterns. Investors navigate economic climates, seeking opportunities in dynamic real estate sectors. The relationship between economy and real estate underscores financial interconnectedness."
test=find_topics(text)

In [16]:
test

,id,original_sentence,sentence,topic,terms,sentence_part_id
0,1,The intricate interplay between economic dynam...,The intricate interplay between economic dynam...,9,"[dynamics, sector, properties, demand]",0
1,1,The intricate interplay between economic dynam...,exerting a profound impact on both property va...,9,"[dynamics, sector, properties, demand]",1
2,2,Market fluctuations impact housing affordabili...,Market fluctuations impact housing affordabili...,8,"[market, impact, fluctuations, housing, invest...",2
3,3,Economic stability fosters a robust real estat...,Economic stability fosters a robust real estat...,3,"[estate, driving, fosters, mirrors, investors,...",3
4,4,Market resilience relies on a balance between ...,Market resilience relies on a balance between ...,1,"[stability, market, balance, health, resilienc...",4
5,5,"Real estate mirrors economic trends, respondin...","Real estate mirrors economic trends, respondin...",3,"[estate, driving, fosters, mirrors, investors,...",5
6,6,"Economic indicators guide real estate trends, ...","Economic indicators guide real estate trends, ...",5,"[property, values, guide, transactions, indica...",6
7,7,"In turn, real estate plays a pivotal role in e...","In turn, real estate plays a pivotal role in e...",9,"[dynamics, sector, properties, demand]",7
8,8,Economic fluctuations echo through real estate...,Economic fluctuations echo through real estate...,2,"[buying, markets, fluctuations, patterns, esta...",8
9,9,"Investors navigate economic climates, seeking ...","Investors navigate economic climates, seeking ...",3,"[estate, driving, fosters, mirrors, investors,...",9
10,10,The relationship between economy and real esta...,The relationship between economy and real esta...,6,"[interconnectedness, economy, relationship, es...",10

In [20]:
new_df = test.drop_duplicates(subset='original_sentence')
new_df = new_df[['id', 'original_sentence', 'terms']]
new_df

,id,original_sentence,terms
0,1,The intricate interplay between economic dynam...,"[dynamics, sector, properties, demand]"
2,2,Market fluctuations impact housing affordabili...,"[market, impact, fluctuations, housing, invest..."
3,3,Economic stability fosters a robust real estat...,"[estate, driving, fosters, mirrors, investors,..."
4,4,Market resilience relies on a balance between ...,"[stability, market, balance, health, resilienc..."
5,5,"Real estate mirrors economic trends, respondin...","[estate, driving, fosters, mirrors, investors,..."
6,6,"Economic indicators guide real estate trends, ...","[property, values, guide, transactions, indica..."
7,7,"In turn, real estate plays a pivotal role in e...","[dynamics, sector, properties, demand]"
8,8,Economic fluctuations echo through real estate...,"[buying, markets, fluctuations, patterns, esta..."
9,9,"Investors navigate economic climates, seeking ...","[estate, driving, fosters, mirrors, investors,..."
10,10,The relationship between economy and real esta...,"[interconnectedness, economy, relationship, es..."

In [21]:
test=test.drop(columns='terms')
merged_df = pd.merge(new_df, test, on=['id','original_sentence'], how='left')

In [23]:
merged_df['topic']

0     9
1     9
2     8
3     3
4     1
5     3
6     5
7     9
8     2
9     3
10    6
Name: topic, dtype: int64

In [2]:
import pandas as pd
df= pd.read_excel("metadata.xlsx")

In [6]:
df['keywords_description']

0       ['fruit', 'vegetables', 'table', 'basket', 'wo...
1            ['fruit', 'bowl', 'types', 'filled', 'lots']
2          ['fruit', 'basket', 'types', 'filled', 'lots']
3       ['fruit', 'vegetables', 'table', 'basket', 'wo...
4            ['fruit', 'bowl', 'types', 'filled', 'lots']
                              ...
3080                                                  NaN
3081                                                  NaN
3082                                                  NaN
3083                                                  NaN
3084                                                  NaN
Name: keywords_description, Length: 3085, dtype: object

In [23]:
term = "fruit"
for idx, meta_row in df.iterrows():
    if term in meta_row['keywords_description']:  # No need to wrap in a list
        image_path = meta_row['name']
        print(image_path)
        break
    else:
        print('no')
        break

spaghetti-1932466_150.jpg

In [111]:
from topic import find_topics
text="Nature's tranquility envelops us, with whispering trees and singing birds. Rivers flow gently, sunlight paints warmth, and flowers bloom vibrantly. Majestic mountains reach for the sky, while stars twinkle overhead. In nature's embrace, peace reigns, offering a timeless sanctuary for all."
df=find_topics(text)

In [112]:
df

,id,original_sentence,sentence,topic,terms,sentence_part_id
0,1,"Nature's tranquility envelops us, with whisper...","Nature's tranquility envelops us, with whisper...",4,"[us, birds, singing, tranquility, mountains]",0
1,2,"Rivers flow gently, sunlight paints warmth, an...","Rivers flow gently, sunlight paints warmth, an...",3,"[flow, sunlight, rivers, paints, bloom, flower...",1
2,3,"Majestic mountains reach for the sky, while st...","Majestic mountains reach for the sky, while st...",4,"[us, birds, singing, tranquility, mountains]",2
3,4,"In nature's embrace, peace reigns, offering a ...","In nature's embrace, peace reigns, offering a ...",1,"[nature, timeless, peace, embrace, reigns, trees]",3

In [97]:
df=df[['sentence']]

In [98]:
df.to_csv("test3.csv")

In [36]:
df

                                            sentence
0  The sun's gentle rays filtered through Sara's ...
1  With a groggy yawn, Sara stirred from her slum...
2                         radiated through her body.
3  It was as though the very act of waking had br...

In [65]:
import spacy
from nltk.tokenize import sent_tokenize

def split_text_into_sentences(text):
    sentences = sent_tokenize(text)
    return sentences

def split_sentence_into_two_parts(sentence, max_length=70):
    nlp = spacy.load('en_core_web_sm')

    if len(sentence) > max_length:
        # Attempt to split the sentence at the last space within the specified length
        split_index = sentence.rfind(' ', 0, max_length)

        if split_index != -1:
            part1 = sentence[:split_index].strip()
            part2 = sentence[split_index + 1:].strip()

            # Check if the last word of part1 is a verb, and if so, move it to part2
            last_word_part1 = nlp(part1.split()[-1])
            
            if last_word_part1 and last_word_part1[0].pos_ == 'VERB':
                part1 = ' '.join(part1.split()[:-1]).strip()
                part2 = last_word_part1.text + ' ' + part2

                return part1, part2

        # If no space is found or the last word is not a verb, try to split when a verb is found
        doc = nlp(sentence)
        for token in reversed(doc):
            if token.pos_ == 'VERB':
                split_index = token.idx
                part1 = sentence[:split_index].strip()
                part2 = sentence[split_index:].strip()
                return part1, part2

        # If no verb is found, split at the max_length
        part1 = sentence[:max_length].strip()
        part2 = sentence[max_length:].strip()
        return part1, part2
    else:
        return sentence, None

In [67]:
text_test="Ultraprocessed foods, often high in salt, sugar, and fat but low in essential nutrients, make up about 73% of the U.S. food supply, fueling an epidemic of dietrelated diseases."
print(split_sentence_into_two_parts(text_test))

('Ultraprocessed foods, often high in salt, sugar, and fat but low in essential nutrients, make up about 73% of the U.S. food supply,', 'fueling an epidemic of dietrelated diseases.')

In [61]:
import spacy

nlp = spacy.load('en_core_web_sm')
doc = nlp("With a yawn that is groggy, Sara stirred from her")
for token in doc:
    print(token.text, token.pos_)

With ADP
a DET
yawn NOUN
that PRON
is AUX
groggy ADJ
, PUNCT
Sara PROPN
stirred VERB
from ADP
her PRON

In [133]:
import pandas as pd
import numpy as np
import nltk
import spacy
from nltk.corpus import stopwords
from gensim import corpora, models
from keybert import KeyBERT



def split_text_into_sentences(text):
    sentences = sent_tokenize(text)
    return sentences

def split_sentence_into_two_parts(sentence, max_length=100):
    nlp = spacy.load('en_core_web_sm')

    if len(sentence) > max_length:
        # Attempt to split the sentence at the last space within the specified length
        length =len(sentence)/2
        split_index = sentence.rfind(', ', 0, int(length))

        if split_index != -1:
            part1 = sentence[:split_index].strip()
            part2 = sentence[split_index + 1:].strip()

            # Check if the last word of part1 is a verb, and if so, move it to part2
            last_word_part1 = nlp(part1.split()[-1])
            
            if last_word_part1 and last_word_part1[0].pos_ == 'VERB':
                part1 = ' '.join(part1.split()[:-1]).strip()
                part2 = last_word_part1.text + ' ' + part2

                return part1, part2

        # If no space is found or the last word is not a verb, try to split when a verb is found
        doc = nlp(sentence)
        for token in reversed(doc):
            if token.pos_ == 'VERB':
                split_index = token.idx
                part1 = sentence[:split_index].strip()
                part2 = sentence[split_index:].strip()
                return part1, part2

        # If no verb is found, split at the max_length
        part1 = sentence[:max_length].strip()
        part2 = sentence[max_length:].strip()
        return part1, part2
    else:
        return sentence, None


def find_topics(text):
    np.random.seed(42)

    sentences = split_text_into_sentences(text)
    keybert = KeyBERT()

    stop_words = set(stopwords.words('english'))
    tokenized_sentences = [nltk.word_tokenize(sentence.lower()) for sentence in sentences]
    filtered_sentences = [
        [word for word in sentence if word.isalnum() and word not in stop_words]
        for sentence in tokenized_sentences
    ]

    dictionary = corpora.Dictionary(filtered_sentences)
    corpus = [dictionary.doc2bow(sentence) for sentence in filtered_sentences]

    np.random.seed(42)

    gensim_seed = 42
    lda_model = models.LdaModel(corpus, num_topics=len(sentences), id2word=dictionary, passes=15, random_state=gensim_seed)

    spacy_seed = 42
    nlp = spacy.load('en_core_web_sm')

    topic_data = []
    for sentence_id, sentence in enumerate(sentences):
        part1, part2 = split_sentence_into_two_parts(sentence)
        original_sentence = sentence  # Store the original sentence before any splitting
        if part2:
            topics_part1 = lda_model.get_document_topics(corpus[sentence_id])
            topics_part2 = lda_model.get_document_topics(dictionary.doc2bow(part2.lower().split()))

            # Combine topics from both parts
            combined_topics = topics_part1 + topics_part2

            top_topic = max(combined_topics, key=lambda x: x[1])
            top_terms = [term[0] for term in lda_model.show_topic(top_topic[0])]

            doc = nlp(' '.join(top_terms))
            cleaned_terms = [
                token.text
                for token in doc
                if token.pos_ in ['NOUN']
            ]

            topic_data.append({'id': sentence_id + 1, 'original_sentence': original_sentence, 'sentence': part1, 'topic': top_topic[0] + 1, 'terms': cleaned_terms})
            topic_data.append({'id': sentence_id + 1, 'original_sentence': original_sentence, 'sentence': part2, 'topic': top_topic[0] + 1, 'terms': cleaned_terms})
        else:
            topics = lda_model.get_document_topics(corpus[sentence_id])
            top_topic = max(topics, key=lambda x: x[1])
            top_terms = [term[0] for term in lda_model.show_topic(top_topic[0])]

            doc = nlp(' '.join(top_terms))
            cleaned_terms = [
                token.text
                for token in doc
                if token.pos_ in ['NOUN']
            ]
            if 'topic' not in locals():
                keywords = keybert.extract_keywords(original_sentence, keyphrase_ngram_range=(1, 1), stop_words='english')
                cleaned_terms = [keyword[0] for keyword in keywords]

            topic_data.append({'id': sentence_id + 1, 'original_sentence': original_sentence, 'sentence': sentence, 'topic': top_topic[0] + 1, 'terms': cleaned_terms})

    df = pd.DataFrame(topic_data)
    df['sentence_part_id'] = df.index

    return df

In [123]:
find_topics("Nature's tranquility envelops us, with whispering trees and singing birds. Rivers flow gently, sunlight paints warmth, and flowers bloom vibrantly. Majestic mountains reach for the sky, while stars twinkle overhead. In nature's embrace, peace reigns, offering a timeless sanctuary for all.")

,id,original_sentence,sentence,topic,terms,sentence_part_id
0,1,"Nature's tranquility envelops us, with whisper...","Nature's tranquility envelops us, with whisper...",4,"[nature, birds, whispering, tranquility, trees]",0
1,2,"Rivers flow gently, sunlight paints warmth, an...","Rivers flow gently, sunlight paints warmth, an...",3,"[flowers, bloom, sunlight, rivers, vibrantly]",1
2,3,"Majestic mountains reach for the sky, while st...","Majestic mountains reach for the sky, while st...",4,"[mountains, sky, majestic, twinkle, stars]",2
3,4,"In nature's embrace, peace reigns, offering a ...","In nature's embrace, peace reigns, offering a ...",1,"[sanctuary, peace, timeless, embrace, nature]",3

In [138]:
text="The sun's gentle rays filtered through Sara's bedroom window, casting a warm glow on the walls. With a groggy yawn, Sara stirred from her slumber, the remnants of sleep lingering in her mind. As she stretched and shifted, a twinge of unfamiliar discomfort radiated through her body. It was as though the very act of waking had brought her face to face with time."

In [9]:
import pandas as pd
import numpy as np
import nltk
import spacy
from nltk.corpus import stopwords
from nltk.tokenize import sent_tokenize
from gensim import corpora, models
from keybert import KeyBERT

nltk.download('stopwords')
nltk.download('punkt')


import spacy

def split_sentence(sentence, max_length=100):
    nlp = spacy.load('en_core_web_sm')
    
    if len(sentence) > max_length:
        # First, try splitting by ','
        if ', ' in sentence:
            parts = sentence.split(',')
            num_parts = len(parts)
            split_index = num_parts // 2

            # Find the optimal split index by minimizing the absolute difference in lengths
            optimal_split_index = split_index
            min_length_diff = abs(sum(len(part) for part in parts[:split_index]) - sum(len(part) for part in parts[split_index:]))
            for i in range(split_index + 1, num_parts):
                length_diff = abs(sum(len(part) for part in parts[:i]) - sum(len(part) for part in parts[i:]))
                if length_diff < min_length_diff:
                    optimal_split_index = i
                    min_length_diff = length_diff

            part1 = ','.join(parts[:optimal_split_index])
            part2 = ','.join(parts[optimal_split_index:])
                        
            return part1, part2
        
        # If ',' not found, proceed with original logic
        length = len(sentence) // 2
        split_index = sentence.rfind(" ", 0, int(length))

        if split_index != -1:
            part1 = sentence[:split_index].strip()
            part2 = sentence[split_index + 1:].strip()

            last_word_part1 = nlp(part1.split()[-1])
            if last_word_part1 and last_word_part1[0].pos_ == 'VERB':
                part1 = ' '.join(part1.split()[:-1]).strip()
                part2 = last_word_part1.text + ' ' + part2

                return part1, part2

        doc = nlp(sentence)
        for token in reversed(doc):
            if token.pos_ == 'VERB':
                split_index = token.idx
                part1 = sentence[:split_index].strip()
                part2 = sentence[split_index:].strip()
                return part1, part2

        part1 = sentence[:max_length].strip()
        part2 = sentence[max_length:].strip()
        return part1, part2
    else:
        return sentence, None


def preprocess_text(text):
    stop_words = set(stopwords.words('english'))
    sentences = sent_tokenize(text)
    tokenized_sentences = [nltk.word_tokenize(sentence.lower()) for sentence in sentences]
    filtered_sentences = [
        [word for word in sentence if word.isalnum() and word not in stop_words]
        for sentence in tokenized_sentences
    ]
    return sentences, filtered_sentences

def clean_terms(top_terms):
    nlp = spacy.load('en_core_web_sm')
    doc = nlp(' '.join(top_terms))
    cleaned_terms = [
        token.text
        for token in doc
        if token.pos_ in ['NOUN']
    ]
    return cleaned_terms

def extract_keywords(text):
    keybert = KeyBERT()
    keywords = keybert.extract_keywords(text, keyphrase_ngram_range=(1, 1), stop_words='english')
    return [keyword[0] for keyword in keywords]

def find_topics(text):
    np.random.seed(42)

    sentences, filtered_sentences = preprocess_text(text)

    dictionary = corpora.Dictionary(filtered_sentences)
    corpus = [dictionary.doc2bow(sentence) for sentence in filtered_sentences]

    np.random.seed(42)

    lda_model = models.LdaModel(corpus, num_topics=len(sentences), id2word=dictionary, passes=15, random_state=42)

    topic_data = []
    for sentence_id, sentence in enumerate(sentences):
        part1, part2 = split_sentence(sentence)
        original_sentence = sentence  # Store the original sentence before any splitting

        if part2:
            topics_part1 = lda_model.get_document_topics(corpus[sentence_id])
            topics_part2 = lda_model.get_document_topics(dictionary.doc2bow(part2.lower().split()))
            combined_topics = topics_part1 + topics_part2

            top_topic = max(combined_topics, key=lambda x: x[1])
            top_terms = [term[0] for term in lda_model.show_topic(top_topic[0])]
            cleaned_terms = clean_terms(top_terms)

            topic_data.append({'id': sentence_id + 1, 'original_sentence': original_sentence, 'sentence': part1, 'topic': top_topic[0] + 1, 'terms': cleaned_terms})
            topic_data.append({'id': sentence_id + 1, 'original_sentence': original_sentence, 'sentence': part2, 'topic': top_topic[0] + 1, 'terms': cleaned_terms})
        else:
            topics = lda_model.get_document_topics(corpus[sentence_id])
            top_topic = max(topics, key=lambda x: x[1])
            top_terms = [term[0] for term in lda_model.show_topic(top_topic[0])]
            cleaned_terms = clean_terms(top_terms)

            if 'topic' not in locals():
                keywords = extract_keywords(original_sentence)
                cleaned_terms = keywords

            topic_data.append({'id': sentence_id + 1, 'original_sentence': original_sentence, 'sentence': sentence, 'topic': top_topic[0] + 1, 'terms': cleaned_terms})

    df = pd.DataFrame(topic_data)
    df['sentence_part_id'] = df.index

    return df

text="From anxiety to cancer, the evidence against ultra-processed food piles up. Americans now consume over half of their daily calories from these foods. Studies reveal a heightened risk of anxiety, depression, obesity, metabolic syndrome, and certain cancers. One telltale sign? Ingredient labels filled with additives and chemicals. Research from over 9 million participants confirms the link. The solution? Fill your plate with whole foods – fruits, vegetables, and whole grains. Take charge of your health and say no to ultra-processed foods. Because what you eat today shapes your health tomorrow."

# Example usage
result_df = find_topics(text)

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/fatimaezzahrasounnyslitine/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     /Users/fatimaezzahrasounnyslitine/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

In [10]:
result_df

,id,original_sentence,sentence,topic,terms,sentence_part_id
0,1,"From anxiety to cancer, the evidence against u...","From anxiety to cancer, the evidence against u...",4,"[cancer, anxiety, food, piles, processed]",0
1,2,Americans now consume over half of their daily...,Americans now consume over half of their daily...,2,"[calories, foods, consume, americans, half]",1
2,3,"Studies reveal a heightened risk of anxiety, d...","Studies reveal a heightened risk of anxiety, d...",5,"[solution, obesity, syndrome, anxiety, cancers...",2
3,3,"Studies reveal a heightened risk of anxiety, d...","obesity, metabolic syndrome, and certain canc...",5,"[solution, obesity, syndrome, anxiety, cancers...",3
4,4,One telltale sign?,One telltale sign?,2,"[telltale, sign]",4
5,5,Ingredient labels filled with additives and ch...,Ingredient labels filled with additives and ch...,3,"[ingredient, labels, additives, chemicals, fil...",5
6,6,Research from over 9 million participants conf...,Research from over 9 million participants conf...,3,"[link, research, participants, million, confirms]",6
7,7,The solution?,The solution?,5,[solution],7
8,8,"Fill your plate with whole foods – fruits, veg...","Fill your plate with whole foods – fruits, veg...",7,"[foods, plate, fruits, vegetables, grains]",8
9,9,Take charge of your health and say no to ultra...,Take charge of your health and say no to ultra...,10,"[foods, processed, health, ultra, say]",9
10,10,Because what you eat today shapes your health ...,Because what you eat today shapes your health ...,10,"[eat, health, today, tomorrow, shapes]",10

In [11]:
result_df["sentence"].to_csv('test6.csv')

In [2]:
image_paths=['datalake_media/image-maldives-1993704_150.jpg-70ef5ccd-0d53-41b5-a054-016be29f2be5', 'datalake_media/image-woman-3640935_150.jpg-57a84e56-ebe3-43ab-82e2-3962a8b15c0c', 'datalake_media/image-winding-road-1556177_150.jpg-8be11ffb-2a1a-4b7c-914f-b3ff9cdc600b', 'datalake_media/image-loveourplanet-4851331_150.jpg-3c37bf5d-9e2b-44d0-8b91-d7e1c78df429', 'datalake_media/image-berries-3504149_150.jpg-5ed7c7f5-1e92-4d82-99f7-83ae38c2667f', 'datalake_media/image-mental-health-4232031_150.jpg-f4dd181f-c229-4dce-a90e-0b2525d563e8', 'datalake_media/image-salad-2068217_150.jpg-e32c1bab-cd4b-4af3-a014-9ae349d266a9', 'datalake_media/image-egg-slicer-647531_150.jpg-2a781df0-34b2-4e72-aa1f-8fb68c8a82dd', 'datalake_media/image-egg-24404_150.png-1f2a2357-2616-4015-847d-28ffdb2dbc37', 'datalake_media/image-berries-3504149_150.jpg-5ed7c7f5-1e92-4d82-99f7-83ae38c2667f', 'datalake_media/image-diet-695723_150.jpg-80cbbef6-f48c-4f5a-93e5-92413ab308a6', 'datalake_media/image-obesity-993126_150.jpg-8bfbdf8b-4fe6-472b-85e3-56071ec4cac1', 'datalake_media/image-vegetables-1085063_150.jpg-dfde1727-a532-4948-b32e-5d11f9728d94', 'datalake_media/image-egg-24404_150.png-1f2a2357-2616-4015-847d-28ffdb2dbc37', 'datalake_media/image-healthy-7213383_150.jpg-f00b2ce4-be70-4f7b-b2dd-9af208eece27', 'datalake_media/image-diet-695723_150.jpg-80cbbef6-f48c-4f5a-93e5-92413ab308a6', 'datalake_media/image-fat-3313923_150.png-5cc9dc32-49a5-4bb5-a0a6-748a236dcee3', 'datalake_media/image-food-366875_150.jpg-f0e09e54-05bc-4d56-a5eb-f22e6de7cf23', 'datalake_media/image-fresh-fruits-2305192_150.jpg-c3ac1f28-856e-4874-93bc-9521ee731014']

In [3]:
image_path='datalake_media/image-maldives-1993704_150.jpg-70ef5ccd-0d53-41b5-a054-016be29f2be5'

In [56]:
import pandas as pd
from nltk.stem import PorterStemmer
from nltk.tokenize import word_tokenize

def stem_words(words):
    porter = PorterStemmer()
    tokens = word_tokenize(words)
    stemmed_words = [porter.stem(word) for word in tokens]

    return stemmed_words

combined_keywords = ['tree']+['nature']+['tree','flower','sun']+ ['tree','coffee','sun']  
stemmed_keywords = stem_words(' '.join(combined_keywords))
keyword_freq = pd.Series(stemmed_keywords).value_counts()
top_terms = keyword_freq.index.tolist()

In [57]:
top_terms

['tree', 'sun', 'natur', 'flower', 'coffe']

In [6]:
from scrapping_api_image import find_image_for_term
import pandas as pd
metadata=pd.read_excel("metadata.xlsx")
term="healthy"
processed_terms = set()
processed_image_paths = set()

metadata['main_topic'] = metadata['main_topic'].astype(str)

while image_path in image_paths:
    metadata=metadata[metadata['path_datalake'] != image_path]
    topic_found, image_found, image_name,image_path = find_image_for_term(term, processed_terms, processed_image_paths, metadata, 'data')

Topic: healthi
healthy-7213383_150.jpg

In [22]:
filenames_list = metadata['name'].tolist()

In [23]:
filenames_list

['fresh-fruits-2305192_150.jpg',
 'vegetables-1085063_150.jpg',
 'olive-oil-968657_150.jpg',
 'berries-3504149_150.jpg',
 'vegetables-3679075_150.jpg',
 'salad-2068217_150.jpg',
 'fresh-fruits-2305192_150.jpg',
 'vegetables-1085063_150.jpg',
 'olive-oil-968657_150.jpg',
 'berries-3504149_150.jpg',
 'vegetables-3679075_150.jpg',
 'salad-2068217_150.jpg',
 'old-books-436498_150.jpg',
 'book-1822474_150.jpg',
 'paper-1100254_150.jpg',
 'glasses-1052010_150.jpg',
 'laptop-3087585_150.jpg',
 'books-2596809_150.jpg',
 'child-865116_150.jpg',
 'abstract-1264071_150.png',
 'students-3518726_150.jpg',
 'laptop-3196481_150.jpg',
 'questions-2519654_150.png',
 'book-1052014_150.jpg',
 'journal-2850091_150.jpg',
 'girl-3528292_150.jpg',
 'books-1163695_150.jpg',
 'question-mark-1872665_150.jpg',
 'literature-3091212_150.jpg',
 'boys-286245_150.jpg',
 'books-1204029_150.jpg',
 'crayons-1445053_150.jpg',
 'library-869061_150.jpg',
 'open-book-1428428_150.jpg',
 'books-1845614_150.jpg',
 'atlas-1052011_150.jpg',
 'desk-1869579_150.jpg',
 'book-2178586_150.jpg',
 'library-2507902_150.jpg',
 'library-1147815_150.jpg',
 'books-21849_150.jpg',
 'pi-1453836_150.jpg',
 'watch-4638673_150.jpg',
 'books-2463779_150.jpg',
 'library-488690_150.jpg',
 'library-849797_150.jpg',
 'books-2606859_150.jpg',
 'group-3137670_150.jpg',
 'books-5937716_150.jpg',
 'books-5937823_150.jpg',
 'book-1868068_150.jpg',
 'apple-1853259_150.jpg',
 'books-1246674_150.jpg',
 'pens-1867899_150.jpg',
 'books-4515917_150.jpg',
 'notebook-2178656_150.jpg',
 'book-4600757_150.jpg',
 'board-5599231_150.png',
 'boy-5731001_150.jpg',
 'idea-3976295_150.png',
 'book-1835799_150.jpg',
 'book-3964050_150.jpg',
 'education-3704026_150.jpg',
 'books-462579_150.jpg',
 'books-1850645_150.jpg',
 'person-5582976_150.jpg',
 'books-5433432_150.jpg',
 'pencils-6099511_150.jpg',
 'reading-4045414_150.jpg',
 'books-1835753_150.jpg',
 'book-3531412_150.jpg',
 'library-488678_150.jpg',
 'children-876543_150.jpg',
 'spiral-staircase-877834_150.jpg',
 'books-5211309_150.jpg',
 'library-7720589_150.jpg',
 'education-3670453_150.jpg',
 'alphabet-916673_150.jpg',
 'musician-5960112_150.jpg',
 'letters-425004_150.jpg',
 'rose-6931259_150.jpg',
 'glasses-4704055_150.jpg',
 'book-6957870_150.jpg',
 'book-5178205_150.jpg',
 'street-2805643_150.jpg',
 'man-6530416_150.jpg',
 'boy-521545_150.jpg',
 'book-856151_150.jpg',
 'knowledge-1052013_150.jpg',
 'antique-7627999_150.jpg',
 'earth-day-7903523_150.png',
 'reading-4330761_150.jpg',
 'lights-951000_150.jpg',
 'old-couple-5051770_150.jpg',
 'woman-8205187_150.jpg',
 'books-3446451_150.jpg',
 'fish-7961064_150.png',
 'los-angeles-8205184_150.jpg',
 'book-6213537_150.jpg',
 'reader-8211917_150.png',
 'museum-5082786_150.jpg',
 'green-1738220_150.jpg',
 'stack-of-books-1001655_150.jpg',
 'never-stop-learning-3653430_150.jpg',
 'science-1182713_150.jpg',
 'books-2869_150.jpg',
 'book-3033196_150.jpg',
 'adult-education-2706977_150.jpg',
 'read-3048651_150.jpg',
 'school-2596090_150.png',
 'school-1782427_150.jpg',
 'learning-3245793_150.jpg',
 'computer-472016_150.jpg',
 'shelf-159852_150.png',
 'blackboard-307835_150.png',
 'school-2761394_150.jpg',
 'technology-1095751_150.jpg',
 'books-2943383_150.png',
 'classroom-2093744_150.jpg',
 'books-1297707_150.png',
 'baby-84626_150.jpg',
 'chalkboard-2379763_150.jpg',
 'study-1968077_150.jpg',
 'online-education-3412473_150.jpg',
 'colorful-2729707_150.png',
 'creative-725811_150.jpg',
 'boy-311392_150.png',
 'owl-47526_150.png',
 'brain-20424_150.jpg',
 'literature-3068940_150.jpg',
 'fish-1653753_150.jpg',
 'students-99506_150.jpg',
 'never-stop-learning-3258944_150.jpg',
 'boys-3350810_150.png',
 'pencils-1280558_150.jpg',
 'school-supplies-3109465_150.png',
 'girl-3038974_150.jpg',
 'boys-3350811_150.png',
 'notebook-1587525_150.jpg',
 'university-105709_150.jpg',
 'apples-2276269_150.jpg',
 'classroom-2093743_150.jpg',
 'school-1974369_150.jpg',
 'tux-161406_150.png',
 'children-602967_150.jpg',
 'graduation-309661_150.png',
 'books-2665628_150.png',
 'notebook-1587527_150.jpg',
 'teach-1968076_150.jpg',
 'education-1545578_150.png',
 'learning-1782430_150.jpg',
 'animals-2730764_150.png',
 'diary-147191_150.png',
 'crayon-2162075_150.jpg',
 'books-4109214_150.png',
 'coral-1653752_150.jpg',
 'question-mark-1872634_150.jpg',
 'creativity-819371_150.jpg',
 'child-830988_150.jpg',
 'teacher-4784916_150.jpg',
 'cap-1266204_150.png',
 'child-3326960_150.png',
 'woman-4599055_150.png',
 'african-american-869673_150.jpg',
 'education-3189934_150.jpg',
 'font-2111748_150.jpg',
 'teenager-1424614_150.png',
 'bookshelves-5142509_150.png',
 'graduation-995042_150.jpg',
 'math-1547018_150.jpg',
 'boy-286240_150.jpg',
 'cactus-1063094_150.jpg',
 'pencil-3318160_150.jpg',
 'man-857943_150.png',
 'brain-1773885_150.png',
 'online-3412498_150.jpg',
 'book-436507_150.jpg',
 'guy-2557251_150.jpg',
 'book-2389229_150.png',
 'library-488677_150.jpg',
 'art-supplies-1324034_150.jpg',
 'read-1342499_150.jpg',
 'english-2724442_150.jpg',
 'dog-1773712_150.png',
 'bookshelves-1751334_150.png',
 'graduation-1345123_150.png',
 'an-array-of-2060778_150.png',
 'kansai-university-84363_150.jpg',
 'learn-2128978_150.jpg',
 'book-15584_150.jpg',
 'school-295210_150.png',
 'book-2948634_150.png',
 'teacher-4784917_150.jpg',
 'graduation-1449488_150.jpg',
 'student-41444_150.png',
 'school-1325091_150.png',
 'books-155185_150.png',
 'adult-education-572269_150.jpg',
 'silhouette-3350708_150.png',
 'dictionary-1619740_150.jpg',
 'books-5430104_150.jpg',
 'book-307045_150.png',
 'wisdom-3071110_150.jpg',
 'book-805405_150.png',
 'kids-5198187_150.png',
 'books-1099067_150.jpg',
 'learning-4264032_150.jpg',
 'old-letters-436502_150.jpg',
 'studying-951818_150.jpg',
 'book-933088_150.jpg',
 'book-2026901_150.png',
 'office-594119_150.jpg',
 'sunrise-1014712_150.jpg',
 'beach-1236581_150.jpg',
 'camera-1130731_150.jpg',
 'polynesia-3021072_150.jpg',
 'people-2591874_150.jpg',
 'notepad-1130743_150.jpg',
 'compass-3408928_150.jpg',
 'luggage-1149289_150.jpg',
 'island-3542290_150.jpg',
 'train-3758523_150.jpg',
 'panorama-2117310_150.jpg',
 'barley-field-1684052_150.jpg',
 'japan-2014618_150.jpg',
 'loveourplanet-4851331_150.jpg',
 'photographer-407068_150.jpg',
 'ribblehead-viaduct-2443085_150.jpg',
 'architecture-1868667_150.jpg',
 'maldives-3220702_150.jpg',
 'summer-2880261_150.jpg',
 'beach-832346_150.jpg',
 'winding-road-1556177_150.jpg',
 'fantasy-3502188_150.jpg',
 'beach-2836300_150.jpg',
 'blonde-1867768_150.jpg',
 'bora-bora-3023437_150.jpg',
 'bora-bora-685303_150.jpg',
 'nature-3787200_150.jpg',
 'orion-nebula-11107_150.jpg',
 'beach-2089936_150.jpg',
 'travel-1749508_150.jpg',
 'houses-4093227_150.jpg',
 'journey-1130732_150.jpg',
 'woman-2896389_150.jpg',
 'woman-3640935_150.jpg',
 'go-pro-1478810_150.jpg',
 'lighthouse-1872998_150.jpg',
 'girl-429380_150.jpg',
 'globe-trotter-1828079_150.jpg',
 'camp-4363073_150.png',
 'boats-2758962_150.jpg',
 'hamburg-3846525_150.jpg',
 'architecture-3095716_150.jpg',
 'nature-2990060_150.jpg',
 'nature-3616194_150.jpg',
 'europe-1264062_150.jpg',
 'beach-1449008_150.jpg',
 'airport-2373727_150.jpg',
 'river-4245261_150.jpg',
 'beach-2413081_150.jpg',
 'adventure-1850912_150.jpg',
 'japan-2014619_150.jpg',
 'girl-3954232_150.jpg',
 'nature-3719233_150.jpg',
 'woman-2711279_150.jpg',
 'passport-2714675_150.jpg',
 'hot-air-balloon-1756150_150.jpg',
 'sea-4955005_150.jpg',
 'lake-6701636_150.jpg',
 'earth-11015_150.jpg',
 'aircraft-1499171_150.jpg',
 'woman-2594934_150.jpg',
 'mosque-615415_150.jpg',
 'women-3266211_150.jpg',
 'neuschwanstein-2602208_150.jpg',
 'auto-3091234_150.jpg',
 'train-1728537_150.jpg',
 'bmw-1313343_150.jpg',
 'thin-2902686_150.jpg',
 'water-3354062_150.jpg',
 'space-4888643_150.jpg',
 'books-1163695_150.jpg',
 'water-3271579_150.jpg',
 'dunes-2184976_150.jpg',
 'vw-bus-1845719_150.jpg',
 'architecture-3121009_150.jpg',
 'the-caucasus-5299607_150.jpg',
 'compass-1753659_150.jpg',
 'man-1850181_150.jpg',
 'couple-2568954_150.jpg',
 'biker-407123_150.jpg',
 'fantasy-6403406_150.jpg',
 'wyoming-4786394_150.jpg',
 'valley-4646114_150.jpg',
 'sea-4768869_150.jpg',
 'forest-3107139_150.jpg',
 'road-trip-4399206_150.png',
 'cyclist-3202481_150.jpg',
 'location-4496459_150.png',
 'palace-530055_150.jpg',
 'beach-3121393_150.png',
 'nepal-1309205_150.jpg',
 'compass-1850673_150.jpg',
 'regensburg-3023439_150.jpg',
 'ship-952292_150.jpg',
 'adult-2178904_150.jpg',
 'travel-3122702_150.jpg',
 'freedom-4782870_150.jpg',
 'little-boy-731165_150.jpg',
 'beach-6292382_150.jpg',
 'kyoto-1976538_150.jpg',
 'traveling-4323759_150.png',
 'woman-1836601_150.jpg',
 'compass-2384365_150.png',
 'beach-4852830_150.jpg',
 'blue-4145659_150.jpg',
 'dubai-1767540_150.jpg',
 'mckenzie-river-5129717_150.jpg',
 'car-6603726_150.jpg',
 'arches-national-park-1846759_150.jpg',
 'blur-1239439_150.jpg',
 'rails-416460_150.jpg',
 'mountains-3523153_150.jpg',
 'road-3856796_150.jpg',
 'nature-3807916_150.jpg',
 'map-2562138_150.jpg',
 'house-4811590_150.jpg',
 'nature-2147400_150.jpg',
 'hiker-918473_150.jpg',
 'temple-1670926_150.jpg',
 'woman-1854284_150.jpg',
 'windmills-1850214_150.jpg',
 'the-caucasus-5302236_150.jpg',
 'skyscrapers-5838029_150.jpg',
 'flowers-2162026_150.jpg',
 'train-station-3169964_150.jpg',
 'rainbow-1467988_150.jpg',
 'bay-1867798_150.jpg',
 'boat-5889919_150.png',
 'nature-6565499_150.jpg',
 'rainbow-4468783_150.jpg',
 'mountains-4671122_150.jpg',
 'mountain-4810958_150.jpg',
 'holiday-4138980_150.png',
 'nature-6723133_150.jpg',
 'water-5386820_150.jpg',
 'yellow-mountains-532857_150.jpg',
 'death-valley-4257280_150.jpg',
 'snow-1890653_150.jpg',
 'airport-1822133_150.jpg',
 'canal-6519196_150.jpg',
 'water-3354063_150.jpg',
 'asphalt-1867667_150.jpg',
 'lighthouse-820431_150.jpg',
 'adventure-4381674_150.jpg',
 'road-trip-3469810_150.jpg',
 'acropolis-2725918_150.jpg',
 'cruise-1578528_150.jpg',
 'desert-3217765_150.jpg',
 'asia-3713473_150.jpg',
 'fish-6093991_150.jpg',
 'hot-air-balloons-4561267_150.jpg',
 'conifers-1850227_150.jpg',
 'street-7467503_150.jpg',
 'wadi-rum-5079834_150.jpg',
 'compass-7592447_150.jpg',
 'astronaut-11080_150.jpg',
 'rails-3309912_150.jpg',
 'senior-3336451_150.jpg',
 'nature-6847175_150.jpg',
 'beach-1867590_150.jpg',
 'moon-2048727_150.jpg',
 'plane-4301615_150.png',
 'motorcycle-1905281_150.jpg',
 'beach-2178747_150.jpg',
 'globe-3411506_150.jpg',
 'japan-2014616_150.jpg',
 'peru-641632_150.jpg',
 'mountain-6815304_150.jpg',
 'mountains-4423621_150.jpg',
 'channel-3547224_150.jpg',
 'mountain-2585069_150.jpg',
 'mountain-806915_150.jpg',
 'road-5089188_150.jpg',
 'japan-2014617_150.jpg',
 'sea-192989_150.jpg',
 'mountains-6544522_150.jpg',
 'sea-4492536_150.jpg',
 'highway-4268179_150.jpg',
 'travel-5219496_150.jpg',
 'fantasy-2861815_150.jpg',
 'adult-2693054_150.jpg',
 'opera-house-3381786_150.jpg',
 'santorini-1546901_150.jpg',
 'nature-6780354_150.jpg',
 'travel-6768660_150.png',
 'vw-1835506_150.jpg',
 'city-2517650_150.jpg',
 'solar-system-11111_150.jpg',
 'nature-1207955_150.jpg',
 'seychelles-4245171_150.jpg',
 'girl-6624686_150.jpg',
 'mountain-4331689_150.jpg',
 'ancient-5302623_150.jpg',
 'mountain-4694346_150.png',
 'bridge-3013297_150.jpg',
 'dune-1748462_150.jpg',
 'woman-8587090_150.png',
 'temple-3181803_150.jpg',
 'fashion-2208045_150.jpg',
 'dna-3539309_150.jpg',
 'laboratory-563423_150.jpg',
 'surgery-1807541_150.jpg',
 'dna-1811955_150.jpg',
 'laboratory-2815641_150.jpg',
 'thermometer-1539191_150.jpg',
 'blood-1813410_150.jpg',
 'syringe-1884784_150.jpg',
 'pulse-trace-163708_150.jpg',
 'anatomical-2261006_150.jpg',
 'covid-4941846_150.png',
 'blood-pressure-1584223_150.jpg',
 'poison-1481596_150.jpg',
 'microscope-275984_150.jpg',
 'virus-1812092_150.jpg',
 'cells-1872666_150.jpg',
 'lab-217043_150.jpg',
 'surgery-1822458_150.jpg',
 'herbs-906140_150.jpg',
 'analysis-2030265_150.jpg',
 'tooth-1670434_150.png',
 'doctor-563429_150.jpg',
 'doctor-650534_150.jpg',
 'capsules-1079838_150.jpg',
 'stethoscope-840125_150.jpg',
 'mask-4898571_150.jpg',
 'biology-220005_150.jpg',
 'pills-3673645_150.jpg',
 'nurse-2019420_150.jpg',
 'analysis-2030261_150.jpg',
 'medications-1853400_150.jpg',
 'pill-3069032_150.jpg',
 'pill-1884775_150.jpg',
 'covid-4948866_150.jpg',
 'nurse-37322_150.png',
 'wheelchair-749985_150.jpg',
 'heart-5079717_150.png',
 'mask-4964590_150.png',
 'dentist-8576790_150.png',
 'corona-4983590_150.jpg',
 'coronavirus-4981176_150.png',
 'medications-257336_150.jpg',
 'tablets-1001224_150.jpg',
 'hypertension-867855_150.jpg',
 'lungs-7578680_150.png',
 'animal-1554745_150.jpg',
 'medications-1851178_150.jpg',
 'medications-1628372_150.jpg',
 'protective-suit-5716753_150.jpg',
 'medicine-257349_150.jpg',
 'test-tube-5065426_150.jpg',
 'tablets-5620566_150.jpg',
 'vitamins-7661774_150.jpg',
 'gel-capsules-5834023_150.jpg',
 'dentist-428646_150.jpg',
 'capsule-158568_150.png',
 'dentist-2589771_150.jpg',
 'covid-19-5169689_150.jpg',
 'pill-4897529_150.jpg',
 'person-5441453_150.jpg',
 'biology-316571_150.jpg',
 'face-mask-4986596_150.jpg',
 'world-1185076_150.png',
 'vaccine-6165772_150.jpg',
 'jar-2338584_150.jpg',
 'blood-test-5601437_150.jpg',
 'pills-6127501_150.jpg',
 'dandelion-5197826_150.jpg',
 'worker-6322085_150.jpg',
 'medicine-8287535_150.jpg',
 'worker-6322029_150.jpg',
 'medical-563427_150.jpg',
 'doctor-563428_150.jpg',
 'electrocardiogram-2858693_150.png',
 'medical-4510408_150.png',
 'health-2082630_150.jpg',
 'stethoscope-icon-2316460_150.png',
 'stethoscope-2617701_150.jpg',
 'blood-pressure-3312513_150.png',
 'ekg-2753762_150.png',
 'ekg-2069872_150.png',
 'skull-765477_150.jpg',
 'coffee-4388872_150.png',
 'abstract-background-1061100_150.jpg',
 'caduceus-2730761_150.png',
 'doctor-6701410_150.jpg',
 'medic-563425_150.jpg',
 'first-aid-2789562_150.png',
 'stethoscope-3725131_150.png',
 'doctor-2027615_150.png',
 'child-2166079_150.jpg',
 'diabetes-528678_150.jpg',
 'isolated-1188036_150.png',
 'ekg-2753761_150.png',
 'hospital-840135_150.jpg',
 'caduceus-2029254_150.png',
 'medications-342462_150.jpg',
 'doctor-2025725_150.png',
 'heart-2730784_150.png',
 'doctor-2027768_150.png',
 'mask-4912807_150.jpg',
 'brain-512758_150.png',
 'fetus-ribs-2936875_150.png',
 'hospital-1338585_150.jpg',
 'headache-1540220_150.jpg',
 'caduceus-30591_150.png',
 'lab-217074_150.jpg',
 'medical-781422_150.jpg',
 'virus-4030721_150.jpg',
 'doctor-5187733_150.png',
 'ekg-2753763_150.png',
 'medicine-296966_150.png',
 'offal-1463369_150.png',
 'brain-1787622_150.jpg',
 'vaccination-2722937_150.jpg',
 'medical-5459630_150.png',
 'coronavirus-5088470_150.jpg',
 'mental-health-2313428_150.png',
 'snellen-3312498_150.png',
 'dna-1903318_150.jpg',
 'scientist-2141259_150.jpg',
 'medical-5459633_150.png',
 'survey-2316468_150.png',
 'heart-6940665_150.png',
 'heart-icon-2316451_150.png',
 'brain-1710293_150.png',
 'leech-368345_150.jpg',
 'hallway-867226_150.jpg',
 'chair-2584260_150.jpg',
 'lungs-2803208_150.png',
 'medical-emergency-1057706_150.jpg',
 'medical-312324_150.png',
 'blood-pressure-1006791_150.jpg',
 'herb-2915337_150.jpg',
 'medical-5459631_150.png',
 'health-2662312_150.jpg',
 'heartbeat-163709_150.jpg',
 'cannabis-1032131_150.png',
 'medical-equipment-4099429_150.jpg',
 'medicine-2801025_150.png',
 'ekg-158177_150.png',
 'harmony-1229886_150.jpg',
 'coronavirus-4972480_150.jpg',
 'brain-5605289_150.png',
 'ekg-2753760_150.png',
 'brain-3446307_150.jpg',
 'medications-257346_150.jpg',
 'medicine-2994788_150.jpg',
 'epidemic-4952933_150.jpg',
 'knee-2253047_150.jpg',
 'heart-care-1040250_150.jpg',
 'health-846780_150.png',
 'stomach-icon-2316627_150.png',
 'ehr-1476525_150.png',
 'medical-5459632_150.png',
 'bones-2663669_150.png',
 'eye-766166_150.jpg',
 'bacteria-3662695_150.jpg',
 'skeleton-5585340_150.png',
 'heart-2658206_150.png',
 'lungs-2773515_150.png',
 'drug-1674890_150.png',
 'dna-3656587_150.jpg',
 'man-3011213_150.jpg',
 'syringe-1884758_150.jpg',
 'stethoscope-2617700_150.jpg',
 'prognosis-icon-2803190_150.png',
 'acne-1606765_150.jpg',
 'health-621356_150.jpg',
 'apothecary-437743_150.jpg',
 'dna-4068826_150.jpg',
 'allergy-1738191_150.jpg',
 'analysis-2030266_150.jpg',
 'diagnostics-161140_150.png',
 'mri-2813899_150.jpg',
 'x-ray-1704855_150.jpg',
 'hospital-3098683_150.jpg',
 'human-heart-1700453_150.png',
 'sneeze-1679104_150.jpg',
 'puzzle-2500333_150.jpg',
 'cartoon-2027771_150.png',
 'doctor-2025726_150.png',
 'family-icon-2316421_150.png',
 'molecule-2082634_150.jpg',
 'flasks-606612_150.jpg',
 'building-154304_150.png',
 'ambulance-1674877_150.png',
 'diabetes-2058045_150.png',
 'caduceus-2789653_150.png',
 'doctor-840127_150.jpg',
 'virus-4971922_150.jpg',
 'pill-1884777_150.jpg',
 'heart-care-1040229_150.png',
 'abdomen-1698565_150.png',
 'covid-19-4960254_150.png',
 'ribs-front-2931058_150.png',
 'wheelchair-1595794_150.jpg',
 'test-214185_150.jpg',
 'antibiotic-1782433_150.jpg',
 'bandage-1235337_150.jpg',
 'milky-way-2695569_150.jpg',
 'earth-1756274_150.jpg',
 'universe-2742113_150.jpg',
 'eclipse-1492818_150.jpg',
 'galaxy-3608029_150.jpg',
 'stars-2643089_150.jpg',
 'orion-nebula-11107_150.jpg',
 'planet-581239_150.jpg',
 'astronaut-4106766_150.jpg',
 'space-911785_150.jpg',
 'astronomy-1867616_150.jpg',
 'galaxy-11098_150.jpg',
 'ufo-1265186_150.jpg',
 'moon-2048727_150.jpg',
 'sketch-3045125_150.jpg',
 'earth-11015_150.jpg',
 'starry-sky-2675322_150.jpg',
 'stars-67616_150.jpg',
 'milky-way-2750627_150.jpg',
 'desk-2325627_150.jpg',
 'superhero-534120_150.jpg',
 'planet-1702788_150.jpg',
 'saturn-54999_150.jpg',
 'moon-1527501_150.jpg',
 'christmas-1911637_150.jpg',
 'galaxy-11188_150.jpg',
 'earth-1365995_150.jpg',
 'wormhole-739872_150.png',
 'clouds-3526558_150.jpg',
 'plant-2004483_150.jpg',
 'milky-way-67504_150.jpg',
 'astronaut-11080_150.jpg',
 'milky-way-74005_150.jpg',
 'yellow-926728_150.jpg',
 'space-3197611_150.jpg',
 'gift-1420830_150.jpg',
 'solar-system-439046_150.jpg',
 'earth-1617121_150.jpg',
 'stars-1654074_150.jpg',
 'universe-4609408_150.jpg',
 'astronaut-1784245_150.jpg',
 'space-5654794_150.png',
 'stars-1655504_150.jpg',
 'cosmos-1853491_150.jpg',
 'northern-lights-3273425_150.jpg',
 'star-trails-1846734_150.jpg',
 'spaceship-4828098_150.jpg',
 'earth-11009_150.jpg',
 'food-366875_150.jpg',
 'milky-way-4526277_150.jpg',
 'wood-1776060_150.jpg',
 'solar-system-11111_150.jpg',
 'space-11099_150.jpg',
 'cartoon-4556429_150.png',
 'stars-1845140_150.jpg',
 'lagoon-nebula-11143_150.jpg',
 'tea-2356770_150.jpg',
 'art-2907939_150.png',
 'polar-lights-5858656_150.jpg',
 'abstract-5719221_150.jpg',
 'earth-11014_150.jpg',
 'constellations-1851128_150.jpg',
 'toys-3644073_150.png',
 'space-3262811_150.jpg',
 'night-photograph-2183637_150.jpg',
 'stars-1837306_150.jpg',
 'stars-2179083_150.jpg',
 'starry-sky-1655503_150.jpg',
 'rocket-launch-67643_150.jpg',
 'wreath-4331664_150.png',
 'parking-space-1487891_150.jpg',
 'space-4984262_150.jpg',
 'cosmos-5809271_150.png',
 'cat-3695213_150.jpg',
 'notepad-3297994_150.jpg',
 'stars-7249785_150.jpg',
 'space-station-60615_150.jpg',
 'sun-11582_150.jpg',
 'wormhole-5319067_150.jpg',
 'workplace-2303851_150.jpg',
 'stars-5442598_150.jpg',
 'spacecraft-441708_150.jpg',
 'night-1189929_150.jpg',
 'lost-places-3035877_150.jpg',
 'frame-1868498_150.jpg',
 'christmas-3861993_150.jpg',
 'water-lily-1592793_150.png',
 'earth-11008_150.jpg',
 'mars-67522_150.jpg',
 'fantasy-4063619_150.jpg',
 'the-sun-3057622_150.jpg',
 'fern-1250903_150.jpg',
 'mars-11012_150.jpg',
 'milky-way-4500469_150.jpg',
 'explosion-1497200_150.jpg',
 'rocket-launch-67646_150.jpg',
 'snow-4726119_150.jpg',
 'astronaut-8061095_150.png',
 'satellite-67718_150.jpg',
 'coffee-2242213_150.jpg',
 'autumn-2857032_150.jpg',
 'rocket-launch-67723_150.jpg',
 'turntable-1109588_150.jpg',
 'light-bulb-5831252_150.jpg',
 'space-art-5626853_150.jpg',
 'library-5219747_150.jpg',
 'spaceship-5570682_150.jpg',
 'space-7709489_150.jpg',

In [23]:
from gensim.models import Word2Vec

word2vec_model = model

word1 = 'tree'
word2 = 'nature'

if word1 in word2vec_model.key_to_index and word2 in word2vec_model.key_to_index:
    embedding_word1 = word2vec_model.get_vector(word1)
    embedding_word2 = word2vec_model.get_vector(word2)

    similarity = word2vec_model.similarity(word1, word2)
    
    print(f"Similarity between '{word1}' and '{word2}': {similarity}")
else:
    print("One or both of the words are not in the vocabulary.")

Similarity between 'tree' and 'nature': 0.11323462426662445

In [37]:
from difflib import SequenceMatcher

word1 = 'montain'
word2 = 'nature'

similarity_ratio = SequenceMatcher(None, word1, word2).ratio()

print(f"Similarity between '{word1}' and '{word2}': {similarity_ratio}")

Similarity between 'montain' and 'nature': 0.3076923076923077

In [41]:
from transformers import BertTokenizer, BertModel
import torch
from sklearn.metrics.pairwise import cosine_similarity

# Load pre-trained BERT model and tokenizer
#tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
#model = BertModel.from_pretrained('bert-base-uncased')

# Define two words
word1 = 'nature'
word2 = 'tree'

# Tokenize and encode words
word1_tokens = tokenizer(word1, return_tensors='pt', padding=True, truncation=True)
word2_tokens = tokenizer(word2, return_tensors='pt', padding=True, truncation=True)

# Get BERT embeddings
with torch.no_grad():
    word1_embeddings = model(**word1_tokens).last_hidden_state.mean(dim=1)  # Use mean pooling over tokens
    word2_embeddings = model(**word2_tokens).last_hidden_state.mean(dim=1)

# Calculate cosine similarity
similarity = cosine_similarity(word1_embeddings, word2_embeddings)[0][0]

print(f"Similarity between '{word1}' and '{word2}': {similarity}")

Similarity between 'nature' and 'tree': 0.7547664642333984

In [9]:
import spacy

nlp = spacy.load('en_core_web_md')

word1 = "animal"
word2 = "cat"

tokens = nlp(f"{word1} {word2}")

for token in tokens:
    print(token.text, token.has_vector, token.vector_norm, token.is_oov)

token1, token2 = tokens[0], tokens[1]

print("Similarity:", token1.similarity(token2))

animal True 47.628998 False
cat True 63.188496 False
Similarity: 0.502460777759552

In [10]:
pip install editdistance

Defaulting to user installation because normal site-packages is not writeable
Collecting editdistance
  Downloading editdistance-0.8.1-cp39-cp39-macosx_11_0_arm64.whl.metadata (3.9 kB)
Downloading editdistance-0.8.1-cp39-cp39-macosx_11_0_arm64.whl (79 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.1/79.1 kB 1.9 MB/s eta 0:00:00
Installing collected packages: editdistance
Successfully installed editdistance-0.8.1
Note: you may need to restart the kernel to use updated packages.

In [19]:
import editdistance

# Define two words
word1 = "flower"
word2 = "bee"

# Calculate Levenshtein distance
distance = editdistance.eval(word1, word2)

# Normalize the distance to get a similarity score
max_length = max(len(word1), len(word2))
similarity_score = (max_length - distance) / max_length

print(f"Similarity between '{word1}' and '{word2}': {similarity_score}")

Similarity between 'flower' and 'bee': 0.16666666666666666

In [7]:
def jaccard_similarity(word1, word2):
    set1 = set(word1)
    set2 = set(word2)
    intersection = len(set1.intersection(set2))
    union = len(set1.union(set2))
    return intersection / union if union != 0 else 0

# Define two words
word1 = "nutrition"
word2 = "vitamins"

# Calculate Jaccard similarity
similarity_score = jaccard_similarity(word1, word2)

print(f"Similarity between '{word1}' and '{word2}': {similarity_score}")

Similarity between 'nutrition' and 'vitamins': 0.3

In [12]:
text="https://cdn.pixabay.com/photo/2015/10/02/15/59/olive-oil-968657_150.jpg"
text=text.split('/')[-1].split('-')[0]

In [13]:
text

'olive'

In [39]:
import requests 
def search_pixabay_images(query, api_key, per_page=3, safe_search=True):
    safe_search_param = 'true' if safe_search else 'false'
    url = f'https://pixabay.com/api/?key={api_key}&q={query}&per_page={per_page}&safesearch={safe_search_param}'
    response = requests.get(url)
    if response.status_code == 200:
        hits = response.json()['hits']
        # Check if hits are available
        if hits:
            images = []
            for resp in hits:
                preview_url = resp['previewURL']
                topic_name = preview_url.split('/')[-1].split('-')[0]
                score = lexical_similarity(query, topic_name)
                print("Score between:", topic_name, " and ", query, " is ", score)
                if score >= 0.5:
                    images.append(resp)
                elif score <= 0.5:
                    # Request new URLs until required number of images is achieved
                    current_page = 1
                    while len(images) < per_page:
                        current_page += 1
                        new_url = f'https://pixabay.com/api/?key={api_key}&q={query}&per_page={per_page}&safesearch={safe_search_param}&page={current_page}'
                        new_response = requests.get(new_url)
                        if new_response.status_code == 200:
                            new_hits = new_response.json()['hits']
                            if not new_hits:
                                break  # No more hits available
                            for new_resp in new_hits:
                                new_preview_url = new_resp['previewURL']
                                new_topic_name = new_preview_url.split('/')[-1].split('-')[0]
                                new_score = jaccard_similarity(query, new_topic_name)
                                print("Score between:", new_topic_name, " and ", query, " is ", new_score)
                                if new_score >= 0.5:
                                    images.append(new_resp)
                        else:
                            print(f"Error: Failed to retrieve images for query: {query}")
                            break
            return images
        else:
            print(f"No images found for query: {query}")
            return []
    else:
        print(f"Error: Failed to retrieve images for query: {query}")
        return []
    
images= search_pixabay_images("nutrition","41475535-6d87f1c0e99d7a58bc22bfbda")

Score between: fresh  and  nutrition  is  0.20064953
Score between: berries  and  nutrition  is  0.2222222222222222
Score between: oranges  and  nutrition  is  0.3
Score between: herbs  and  nutrition  is  0.1
Score between: smoothie  and  nutrition  is  0.3
Score between: cherries  and  nutrition  is  0.2
Score between: food  and  nutrition  is  0.125
Score between: salad  and  nutrition  is  0.0
Score between: smoothie  and  nutrition  is  0.3
Score between: mediterranean  and  nutrition  is  0.4
Score between: salad  and  nutrition  is  0.0
Score between: vegetables  and  nutrition  is  0.07692307692307693
Score between: tangerines  and  nutrition  is  0.4
Score between: pumpkin  and  nutrition  is  0.3333333333333333
Score between: tomatoes  and  nutrition  is  0.2
Score between: garlic  and  nutrition  is  0.2
Score between: hamburger  and  nutrition  is  0.16666666666666666
Score between: strawberries  and  nutrition  is  0.2727272727272727
Score between: berries  and  nutrition  is  0.2222222222222222
Score between: carrots  and  nutrition  is  0.3333333333333333
Score between: hot  and  nutrition  is  0.2857142857142857
Score between: smoothies  and  nutrition  is  0.3
Score between: spaghetti  and  nutrition  is  0.16666666666666666
Score between: slice  and  nutrition  is  0.1
Score between: blueberries  and  nutrition  is  0.3
Score between: blueberries  and  nutrition  is  0.3
Score between: breakfast  and  nutrition  is  0.16666666666666666
Score between: mandarins  and  nutrition  is  0.3
Score between: vegetables  and  nutrition  is  0.07692307692307693
Score between: yogurt  and  nutrition  is  0.5
Score between: tray  and  nutrition  is  0.25
Score between: supermarket  and  nutrition  is  0.25
Score between: garlic  and  nutrition  is  0.2
Score between: honey  and  nutrition  is  0.2222222222222222
Score between: fruits  and  nutrition  is  0.5
Score between: oranges  and  nutrition  is  0.3
Score between: olive  and  nutrition  is  0.2222222222222222
Score between: blueberries  and  nutrition  is  0.3
Score between: vegetables  and  nutrition  is  0.07692307692307693
Score between: fruits  and  nutrition  is  0.5
Score between: vegetables  and  nutrition  is  0.3591856
Score between: olive  and  nutrition  is  0.14694989

In [42]:
images

[{'id': 1442034,
  'pageURL': 'https://pixabay.com/photos/yogurt-strawberries-food-fruit-1442034/',
  'type': 'photo',
  'tags': 'yogurt, strawberries, food',
  'previewURL': 'https://cdn.pixabay.com/photo/2016/06/07/17/15/yogurt-1442034_150.jpg',
  'previewWidth': 150,
  'previewHeight': 99,
  'webformatURL': 'https://pixabay.com/get/g463b443b17c55c72249d91852e08c700cfcbb1b01fa568d60d98ef796df0817d23f7b4ae44d6265f86861ad5a00d0bcf7c5300d1faa68cc1127a7878a612b569_640.jpg',
  'webformatWidth': 640,
  'webformatHeight': 426,
  'largeImageURL': 'https://pixabay.com/get/g285ab1c34ccf16a955a75afd34aa198a61f43de0367a61eaaacd018e8b209fb9ab99d45640533a9f5c66629cd3f535872bfbc3c01fc2b65699408fa64ad40fb5_1280.jpg',
  'imageWidth': 3888,
  'imageHeight': 2592,
  'imageSize': 2588760,
  'views': 230247,
  'downloads': 136747,
  'collections': 575,
  'likes': 515,
  'comments': 84,
  'user_id': 2473530,
  'user': 'ponce_photography',
  'userImageURL': 'https://cdn.pixabay.com/user/2016/08/06/01-12-58-158_250x250.jpg'},
 {'id': 1869132,
  'pageURL': 'https://pixabay.com/photos/fruits-crepes-breakfast-plates-1869132/',
  'type': 'photo',
  'tags': 'fruits, crepes, breakfast',
  'previewURL': 'https://cdn.pixabay.com/photo/2016/11/29/11/15/fruits-1869132_150.jpg',
  'previewWidth': 150,
  'previewHeight': 112,
  'webformatURL': 'https://pixabay.com/get/gf13971d89bdf1a345c0c87385a9f2cc021daf1d757fe0379e8cc0ae8fadc7d18b438898e1f7386333d1909303379e577d0444c9c7dce018292ce2d72cf7cfcb8_640.jpg',
  'webformatWidth': 640,
  'webformatHeight': 479,
  'largeImageURL': 'https://pixabay.com/get/gfc7e82fd742885fba657215648126d2257829bd07bcef616be20ee51f08eb436568ea8a66c3c362d1da9d1410abab424a9677615e1e0f59ba4418375098740ed_1280.jpg',
  'imageWidth': 5130,
  'imageHeight': 3840,
  'imageSize': 2306193,
  'views': 103382,
  'downloads': 57685,
  'collections': 311,
  'likes': 238,
  'comments': 21,
  'user_id': 2286921,
  'user': 'Pexels',
  'userImageURL': 'https://cdn.pixabay.com/user/2016/03/26/22-06-36-459_250x250.jpg'},
 {'id': 1114060,
  'pageURL': 'https://pixabay.com/photos/fruits-fresh-basket-fresh-fruits-1114060/',
  'type': 'photo',
  'tags': 'fruits, fresh, basket',
  'previewURL': 'https://cdn.pixabay.com/photo/2015/12/30/11/57/fruits-1114060_150.jpg',
  'previewWidth': 150,
  'previewHeight': 99,
  'webformatURL': 'https://pixabay.com/get/g396f39105b01e91b58d393d7d5147cae68177bd8ef11c0fd4648fbc8b2bc58d690e0508ae801b7a75c5f05e532e9ee3b0b4b1c0bb3f5277825edde1375d2ca6d_640.jpg',
  'webformatWidth': 640,
  'webformatHeight': 423,
  'largeImageURL': 'https://pixabay.com/get/g20b58965105e9826381cd89659a9a952c34ccaca651e2b45b164dc2d7fbce68a34f36d37085467cadde7367819f42693bd091655e265e2d0777180c646d608cd_1280.jpg',
  'imageWidth': 4928,
  'imageHeight': 3264,
  'imageSize': 2399627,
  'views': 223683,
  'downloads': 135997,
  'collections': 387,
  'likes': 521,
  'comments': 97,
  'user_id': 1729295,
  'user': 'diapicard',
  'userImageURL': ''}]

In [24]:
jaccard_similarity("vegetable","nutrition")

0.08333333333333333

In [25]:
import gensim.downloader as api
from gensim.models import KeyedVectors

def lexical_similarity(word1, word2):
    word_vectors=KeyedVectors.load("word_vectors.gensim")
    try:
        similarity_score = word_vectors.similarity(word1, word2)
        return similarity_score
    except KeyError:
        print("One or both words not found in the vocabulary.")
        return 0

# Example usage:
word1 = "vegetables"
word2 = "fruit"
similarity = lexical_similarity(word1, word2)
if similarity is not None:
    print(f"Similarity between '{word1}' and '{word2}': {similarity}")

[==================================================] 100.0% 128.1/128.1MB downloaded
Similarity between 'vegetables' and 'fruit': 0.7578458786010742

In [36]:
word1 = "nutrition"
word2 = "food"
similarity = lexical_similarity(word1, word2)
if similarity is not None:
    print(f"Similarity between '{word1}' and '{word2}': {similarity}")

Similarity between 'nutrition' and 'food': 0.655144989490509

In [2]:
from gensim.models import KeyedVectors
import gensim.downloader as api
from gensim.models import KeyedVectors
# Load pre-trained word vectors
word_vectors = api.load("glove-wiki-gigaword-100")

# Define the file path to save the word vectors
file_path = "word_vectors.gensim"

# Save the word vectors to the file
word_vectors.save(file_path)

In [38]:
loaded_word_vectors = KeyedVectors.load("word_vectors.gensim")

In [32]:
import requests 
import pandas as pd
from nltk.corpus import wordnet


def lexical_similarity(word1, word2):
    synsets1 = wordnet.synsets(word1)
    synsets2 = wordnet.synsets(word2)

    max_similarity = 0

    for synset1 in synsets1:
        for synset2 in synsets2:
            similarity = synset1.wup_similarity(synset2)  # Wu-Palmer Similarity
            if similarity is not None and similarity > max_similarity:
                max_similarity = similarity

    return max_similarity

def search_pixabay_images(query, api_key,metadata, per_page=3, safe_search=True):
    safe_search_param = 'true' if safe_search else 'false'
    image_names_used=metadata['name'].tolist()
    url = f'https://pixabay.com/api/?key={api_key}&q={query}&per_page={per_page}&safesearch={safe_search_param}'
    response = requests.get(url)
    if response.status_code == 200:
        hits = response.json()['hits']
        # Check if hits are available
        if hits:
            images = []
            for resp in hits:
                preview_url = resp['previewURL']
                filename = preview_url.split('/')[-1]
                print(filename)
                topic_name = preview_url.split('/')[-1].split('-')[0]
                score = lexical_similarity(query, topic_name)
                print("Score between:", topic_name, " and ", query, " is ", score)
                if score >= 0.4:
                    #if filename not in image_names_used:
                    images.append(resp)
                elif score <= 0.4:
                    # Request new URLs until required number of images is achieved
                    current_page = 1
                    while len(images) < 1:
                        current_page += 1
                        new_url = f'https://pixabay.com/api/?key={api_key}&q={query}&per_page={per_page}&safesearch={safe_search_param}&page={current_page}'
                        new_response = requests.get(new_url)
                        if new_response.status_code == 200:
                            new_hits = new_response.json()['hits']
                            if not new_hits:
                                break  
                            for new_resp in new_hits:
                                new_preview_url = new_resp['previewURL']
                                new_filename = preview_url.split('/')[-1]
                                print(new_filename)
                                new_topic_name = new_preview_url.split('/')[-1].split('-')[0]

                                new_score = lexical_similarity(query, new_topic_name)
                                print("Score between:", new_topic_name, " and ", query, " is ", new_score)
                                if new_score >= 0.4:
                                    #if new_filename not in image_names_used:
                                    images.append(new_resp)
                                    #else:
                                    #    print('file already in metadata')
                        else:
                            break
            return images
        else:
            print(f"No images found for query: {query}")
            return []
    else:
        print(f"Error: Failed to retrieve images for query: {query}")
        return []
    
metadata=pd.read_excel("metadata.xlsx")

images= search_pixabay_images("nutrition","41475535-6d87f1c0e99d7a58bc22bfbda",metadata)

fresh-fruits-2305192_150.jpg
Score between: fresh  and  nutrition  is  0.25
fresh-fruits-2305192_150.jpg
Score between: berries  and  nutrition  is  0.42857142857142855
fresh-fruits-2305192_150.jpg
Score between: oranges  and  nutrition  is  0.42857142857142855
fresh-fruits-2305192_150.jpg
Score between: herbs  and  nutrition  is  0.6666666666666666
vegetables-1085063_150.jpg
Score between: vegetables  and  nutrition  is  0.46153846153846156
olive-oil-968657_150.jpg
Score between: olive  and  nutrition  is  0.5882352941176471

In [33]:
images

[{'id': 2277,
  'pageURL': 'https://pixabay.com/photos/berries-fruits-food-blackberries-2277/',
  'type': 'photo',
  'tags': 'berries, fruits, laptop wallpaper',
  'previewURL': 'https://cdn.pixabay.com/photo/2010/12/13/10/05/berries-2277_150.jpg',
  'previewWidth': 150,
  'previewHeight': 99,
  'webformatURL': 'https://pixabay.com/get/gcd56e02908323c67c5d40fafd07162c7bd1b94f5587cea648dba4e7ee94ecc4d18a9b434c6e3b214f4fa080dd7e1decc_640.jpg',
  'webformatWidth': 640,
  'webformatHeight': 426,
  'largeImageURL': 'https://pixabay.com/get/g17ebacb92b431f3e26b4414d3957b5d8942e4078cfce41b9c951af8398c939681489e2aed27a270195c218ac291528d1_1280.jpg',
  'imageWidth': 4752,
  'imageHeight': 3168,
  'imageSize': 2113812,
  'views': 1062467,
  'downloads': 590522,
  'collections': 1963,
  'likes': 2079,
  'comments': 406,
  'user_id': 14,
  'user': 'PublicDomainPictures',
  'userImageURL': 'https://cdn.pixabay.com/user/2012/03/08/00-13-48-597_250x250.jpg'},
 {'id': 1995056,
  'pageURL': 'https://pixabay.com/photos/oranges-citrus-fruits-fruits-1995056/',
  'type': 'photo',
  'tags': 'oranges, citrus fruits, fruits',
  'previewURL': 'https://cdn.pixabay.com/photo/2017/01/20/15/06/oranges-1995056_150.jpg',
  'previewWidth': 150,
  'previewHeight': 97,
  'webformatURL': 'https://pixabay.com/get/gc25c103fcb84ebe9f10c382d10d341147c4404cc58183167e83f6129b0e74085690f8e3455664e7f8141f115b5f9a62d9740ad1f60cc69c8a7ed90f676b92996_640.jpg',
  'webformatWidth': 640,
  'webformatHeight': 417,
  'largeImageURL': 'https://pixabay.com/get/g6cc11c558305cc0014e6d3c310d0acd2aa76298b86fc9efcec2a8c96bd530335b040ced178055e99541642aea61b2437b9bb43ecfe823db81d40d276d72563d4_1280.jpg',
  'imageWidth': 4980,
  'imageHeight': 3245,
  'imageSize': 2515891,
  'views': 476848,
  'downloads': 341748,
  'collections': 1075,
  'likes': 1097,
  'comments': 163,
  'user_id': 2364555,
  'user': 'NoName_13',
  'userImageURL': 'https://cdn.pixabay.com/user/2022/12/12/07-40-59-226_250x250.jpg'},
 {'id': 906140,
  'pageURL': 'https://pixabay.com/photos/herbs-natural-pharmaceutical-green-906140/',
  'type': 'photo',
  'tags': 'herbs, natural, pharmaceutical',
  'previewURL': 'https://cdn.pixabay.com/photo/2015/08/25/03/50/herbs-906140_150.jpg',
  'previewWidth': 112,
  'previewHeight': 150,
  'webformatURL': 'https://pixabay.com/get/g6744d7252e398f64420ea52a9e7bb54b3c2f27b6f8a6302a7530280e74a1fbf28dbbc143c115174485ce66ba57699dc3_640.jpg',
  'webformatWidth': 480,
  'webformatHeight': 640,
  'largeImageURL': 'https://pixabay.com/get/g0128cb4f6e3e2d5cdec8cec8bc86d0d0d99f38180447a67f3e26875e6113f0a0f760e3c5884f1a2c6acc37ae585ca8fa94e5174628e2ffbac29aeedc76410243_1280.jpg',
  'imageWidth': 3529,
  'imageHeight': 4705,
  'imageSize': 2306981,
  'views': 596001,
  'downloads': 434993,
  'collections': 1107,
  'likes': 915,
  'comments': 175,
  'user_id': 1334070,
  'user': 'kerdkanno',
  'userImageURL': 'https://cdn.pixabay.com/user/2015/10/03/22-05-02-560_250x250.jpg'},
 {'id': 1085063,
  'pageURL': 'https://pixabay.com/photos/vegetables-fruits-food-ingredients-1085063/',
  'type': 'photo',
  'tags': 'vegetables, fruits, food',
  'previewURL': 'https://cdn.pixabay.com/photo/2015/12/09/17/11/vegetables-1085063_150.jpg',
  'previewWidth': 150,
  'previewHeight': 98,
  'webformatURL': 'https://pixabay.com/get/gfaec9bda946dd18d47c3ff2546d7569cbd4a7edae97e3664d0f6229e2b6ef3e7e611adb2f4c0ff34b2adae1f3e7711c6f15c05b5fb7ce27c287954444315a814_640.jpg',
  'webformatWidth': 640,
  'webformatHeight': 422,
  'largeImageURL': 'https://pixabay.com/get/gbbdd55e02be5d6e5ab53a38eb49a68b8b9fc0249c7ccac1b783d3b1ffc5896b4ac033dca5bf7414c6a9b50eafe9334319eb03998931762ab59c06676a85c60b2_1280.jpg',
  'imageWidth': 4050,
  'imageHeight': 2676,
  'imageSize': 1814596,
  'views': 677749,
  'downloads': 389701,
  'collections': 1029,
  'likes': 1196,
  'comments': 292,
  'user_id': 1643989,
  'user': 'dbreen',
  'userImageURL': 'https://cdn.pixabay.com/user/2015/11/14/15-22-41-548_250x250.jpg'},
 {'id': 968657,
  'pageURL': 'https://pixabay.com/photos/olive-oil-olives-food-oil-natural-968657/',
  'type': 'photo',
  'tags': 'olive oil, olives, food',
  'previewURL': 'https://cdn.pixabay.com/photo/2015/10/02/15/59/olive-oil-968657_150.jpg',
  'previewWidth': 150,
  'previewHeight': 99,
  'webformatURL': 'https://pixabay.com/get/gdfd3faef5bd3702dfa65f7b7dcce139952fb73b533eee053de69d9e54edf57e3ac593fbe23726a37244902ee248990f6_640.jpg',
  'webformatWidth': 640,
  'webformatHeight': 426,
  'largeImageURL': 'https://pixabay.com/get/g57e05172d679f971f9c353731fa92de0115054bf12b25c70ebb8d239adc1e371253699fafba4703f797f4db910106c5318ca8a64d78da1b0f4d07d3a22f98df5_1280.jpg',
  'imageWidth': 5472,
  'imageHeight': 3648,
  'imageSize': 2155622,
  'views': 653109,
  'downloads': 387220,
  'collections': 1257,
  'likes': 1600,
  'comments': 724,
  'user_id': 282134,
  'user': 'stevepb',
  'userImageURL': 'https://cdn.pixabay.com/user/2015/09/15/20-33-27-452_250x250.jpg'}]

In [4]:
import boto3
from botocore.exceptions import ClientError
import json
session = boto3.Session(region_name='eu-west-1')
s3 = session.client('s3',aws_access_key_id="AKIAUJXLE2HEOGWEMCEX",aws_secret_access_key="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")
try:
    response = s3.get_object(Bucket='soulchain-dev1-output-video', Key='video_info.json')

    existing_data_all = json.loads(response['Body'].read())
except ClientError as e:
    if e.response['Error']['Code'] == 'NoSuchKey':
        existing_data_all = []
    else:
        raise

In [5]:
existing_data_all

[{'video_id': 'video70',
  'user_id': 'user7',
  'date_created': '2024-05-13T15:24:19.578265',
  'video_key': 'generated_videos/video70/final_video.mp4',
  'video_type': 'image',
  'video_parts': [{'key': 1,
    'duration': 2.74,
    'media_key': 'datalake_media/image-bread-2796393_150.jpg-1b0ffe96-fbec-4bc3-9c6d-0e43965b52a7',
    'audio_key': 'generated_videos/video70/audio1',
    'text': 'Wondering how protein impacts blood sugar levels?',
    'subtitles': 'Vous vous demandez comment les protéines affectent le taux de sucre dans le sang?',
    'video_part_key': 'generated_videos/video70/video70_part_1.mp4'},
   {'key': 2,
    'duration': 6.11,
    'media_key': 'datalake_media/image-soup-2897649_150.jpg-7f2bb2f3-d555-42ee-b089-fcec7a849eea',
    'audio_key': 'generated_videos/video70/audio2',
    'text': 'Protein plays a crucial role for those managing diabetes, stabilizing glucose levels after meals.',
    'subtitles': 'Les protéines jouent un rôle crucial pour ceux qui gèrent le diabète, stabilisant les niveaux de glucose après les repas.',
    'video_part_key': 'generated_videos/video70/video70_part_2.mp4'},
   {'key': 3,
    'duration': 1.62,
    'media_key': 'datalake_media/image-diabetes-1724617_150.jpg-8344c298-2de3-40f7-a4b1-bdb1abfc1a06',
    'audio_key': 'generated_videos/video70/audio3',
    'text': 'When you consume protein',
    'subtitles': 'Lorsque vous consommez des protéines',
    'video_part_key': 'generated_videos/video70/video70_part_3.mp4'},
   {'key': 4,
    'duration': 5.69,
    'media_key': 'datalake_media/image-insulin-2110059_150.jpg-3f7f5053-6446-4a0c-b690-8fbd96572eac',
    'audio_key': 'generated_videos/video70/audio4',
    'text': ' it doesn’t just fill you up—it also triggers an insulin response that helps moderate blood sugar spikes.',
    'subtitles': "Il ne se contente pas de vous remplir — il déclenche également une réponse à l'insuline qui aide à modérées pics de sucre dans le sang.",
    'video_part_key': 'generated_videos/video70/video70_part_4.mp4'}]},
 {'video_id': 'video700',
  'user_id': 'user70',
  'date_created': '2024-05-13T15:54:04.682953',
  'video_key': 'generated_videos/video700/final_video.mp4',
  'video_type': 'video',
  'video_parts': [{'key': 1,
    'duration': 2.69,
    'media_key': 'datalake_media/video-11713-231759032_large.mp4-f6067d48-840f-42dc-9810-776c9360c617',
    'audio_key': 'generated_videos/video700/audio1',
    'text': 'Wondering how protein impacts blood sugar levels?',
    'subtitles': 'Wondering how protein impacts blood sugar levels?',
    'video_part_key': 'generated_videos/video700/video700_part_1.mp4'},
   {'key': 2,
    'duration': 5.88,
    'media_key': 'datalake_media/video-174944-852206099_large.mp4-e1cb6747-5c69-43c7-bc26-80ad5c5018fc',
    'audio_key': 'generated_videos/video700/audio2',
    'text': 'Protein plays a crucial role for those managing diabetes, stabilizing glucose levels after meals.',
    'subtitles': 'Protein plays a crucial role for those managing diabetes, stabilizing glucose levels after meals.',
    'video_part_key': 'generated_videos/video700/video700_part_2.mp4'},
   {'key': 3,
    'duration': 1.62,
    'media_key': 'datalake_media/video-16685-274413239_large.mp4-818f3e69-6095-4422-a6df-8985c4497bb0',
    'audio_key': 'generated_videos/video700/audio3',
    'text': 'When you consume protein',
    'subtitles': 'When you consume protein',
    'video_part_key': 'generated_videos/video700/video700_part_3.mp4'},
   {'key': 4,
    'duration': 5.85,
    'media_key': 'datalake_media/video-167841-837754506_large.mp4-05cd68cf-c101-4409-b1ee-8806f5ac8824',
    'audio_key': 'generated_videos/video700/audio4',
    'text': ' it doesn’t just fill you up—it also triggers an insulin response that helps moderate blood sugar spikes.',
    'subtitles': ' it doesn’t just fill you up—it also triggers an insulin response that helps moderate blood sugar spikes.',
    'video_part_key': 'generated_videos/video700/video700_part_4.mp4'}]}]

In [27]:
from io import BytesIO
import io
import numpy as np
import tempfile
import cv2
import uuid
import boto3
import cv2
import tempfile
import json
import io
from moviepy.editor import VideoFileClip, AudioFileClip, CompositeAudioClip

from io import BytesIO
import numpy as np
import cv2
import boto3
import json
from moviepy.editor import VideoFileClip, AudioFileClip, CompositeAudioClip

def generate_final_video(s3, video_id, background_music_file):
    # Download background music
    with tempfile.NamedTemporaryFile(suffix='.mp3', delete=False) as temp_audio_file:
        s3.download_file("soulchain-dev1-output-video", f"background_music/{background_music_file}", temp_audio_file.name)
        background_music = AudioFileClip(temp_audio_file.name)
        background_music = background_music.volumex(0.2)

    # Get video information
    bucket = "soulchain-dev1-output-video"
    key = "video_info.json"
    response = s3.get_object(Bucket=bucket, Key=key)
    data = json.loads(response["Body"].read().decode("utf-8"))

    topic_clips = [
        part["video_part_key"] for video in data if video["video_id"] == video_id
        for part in video["video_parts"]
    ]

    # Process video clips
    frames = []
    for key in topic_clips:
        obj = s3.get_object(Bucket='soulchain-dev1-output-video', Key=key)
        video_buffer = io.BytesIO(obj['Body'].read())
        video_buffer.seek(0)
        
        # Read video with moviepy
        video_clip = VideoFileClip(video_buffer)
        frames.append(video_clip.read_frame())

    # Release resources from moviepy clips
    for clip in frames:
        clip.close()

    # Concatenate frames (assuming all frames have the same size)
    final_clip = cv2.hconcat(frames)

    # Write final video
    fourcc = cv2.VideoWriter_fourcc(*'mp4v')  # Video codec
    fps = 24  # Frames per second
    out_size = 1990,1800
  # Width, Height (reversed order)
    with tempfile.NamedTemporaryFile(suffix='.mp4', delete=False) as final_video_file:
        final_video = cv2.VideoWriter(final_video_file.name, fourcc, fps, out_size)
        final_video.write(final_clip)
        final_video.release()

    # Upload final video to S3
    with open(final_video_file.name, "rb") as f:
        s3.upload_fileobj(f, 'soulchain-dev1-output-video', f"generated_videos/{video_id}/final_video.mp4")

    return f"generated_videos/{video_id}/final_video.mp4"

In [32]:
session = boto3.Session(region_name='eu-west-1')
s3 = session.client('s3',aws_access_key_id="AKIAUJXLE2HEM4YQVOSA",aws_secret_access_key="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")

generate_final_video(s3, 'video_user1', "in_the_forest.mp3")

ValueError: max() arg is an empty sequence

In [34]:
from moviepy.editor import VideoFileClip, AudioFileClip, concatenate_videoclips, CompositeAudioClip, CompositeVideoClip


def generate_final_video(s3, video_id, background_music_file):
    with tempfile.NamedTemporaryFile(suffix='.mp3') as temp_audio_file:
        s3.download_file("soulchain-dev1-output-video", f"background_music/{background_music_file}", temp_audio_file.name)
        background_music = AudioFileClip(temp_audio_file.name)
        background_music = background_music.volumex(0.2)
        
        bucket = "soulchain-dev1-output-video"
        key = "video_info.json"
        response = s3.get_object(Bucket=bucket, Key=key)
        data = json.loads(response["Body"].read().decode("utf-8"))
        
        topic_clips = [
            part["video_part_key"] for video in data if video["video_id"] == video_id
            for part in video["video_parts"]
        ]
        
        clips = []
        for key in topic_clips:
            obj = s3.get_object(Bucket='soulchain-dev1-output-video', Key=key)
            video_buffer = io.BytesIO(obj['Body'].read())
            video_buffer.seek(0)
            with tempfile.NamedTemporaryFile(delete=False, suffix='.mp4') as temp_video_file:
                temp_video_file.write(video_buffer.read())
                temp_video_file.seek(0)
                clips.append(VideoFileClip(temp_video_file.name))
        
        final_video = concatenate_videoclips(clips, method="compose")
        
        background_music = background_music.subclip(0, final_video.duration)
        final_video = final_video.set_audio(CompositeAudioClip([final_video.audio, background_music]))
        
        with tempfile.NamedTemporaryFile(delete=False, suffix='.mp4') as final_video_file:
            final_video.write_videofile(final_video_file.name, audio_codec='aac')
            final_video_file.seek(0)
            
            # Upload final video to S3
            with open(final_video_file.name, "rb") as f:
                s3.upload_fileobj(f, 'soulchain-dev1-output-video', f"generated_videos/{video_id}/final_video.mp4")
        
        # Clean up resources
        for clip in clips:
            clip.close()
    
    return f"generated_videos/{video_id}/final_video.mp4"


session = boto3.Session(region_name='eu-west-1')
s3 = session.client('s3',aws_access_key_id="AKIAUJXLE2HEM4YQVOSA",aws_secret_access_key="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")

generate_final_video(s3, 'video_user_test1', "in_the_forest.mp3")

Moviepy - Building video /var/folders/ys/s5c8y6vx2n95hnjtr5vs5h000000gn/T/tmpt2qmz5r7.mp4.
MoviePy - Writing audio in tmpt2qmz5r7TEMP_MPY_wvf_snd.mp4

MoviePy - Done.
Moviepy - Writing video /var/folders/ys/s5c8y6vx2n95hnjtr5vs5h000000gn/T/tmpt2qmz5r7.mp4

Moviepy - Done !
Moviepy - video ready /var/folders/ys/s5c8y6vx2n95hnjtr5vs5h000000gn/T/tmpt2qmz5r7.mp4

'generated_videos/video_user_test1/final_video.mp4'